<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>3.0.3</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>Provide a SemanticVersion class to parse, compare, format semantic versions</Description>
    <PackageTags>semver, semantic-versioning, version, parsing, comparison</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../common/CultureInsensitiveTypeAttribute.cs" />
  </ItemGroup>
</Project>
