using Meziantou.Framework.SyntaxHighlighting.Engine;

namespace Meziantou.Framework.SyntaxHighlighting.Languages;

internal static class Php
{
    public static CompiledMode Instance { get; } = Compiler.Compile(CreateMode());

    private static Mode CreateMode()
    {
        var root = new Mode { Keywords = Keywords.FromMap(new Dictionary<string, string[]>(StringComparer.Ordinal) { ["keyword"] = ["__CLASS__", "__DIR__", "__FILE__", "__FUNCTION__", "__COMPILER_HALT_OFFSET__", "__LINE__", "__METHOD__", "__NAMESPACE__", "__TRAIT__", "die", "echo", "exit", "include", "include_once", "print", "require", "require_once", "array", "abstract", "and", "as", "binary", "bool", "boolean", "break", "callable", "case", "catch", "class", "clone", "const", "continue", "declare", "default", "do", "double", "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif", "endswitch", "endwhile", "enum", "eval", "extends", "final", "finally", "float", "for", "foreach", "from", "global", "goto", "if", "implements", "instanceof", "insteadof", "int", "integer", "interface", "isset", "iterable", "list", "match|0", "mixed", "new", "never", "object", "or", "private", "protected", "public", "readonly", "real", "return", "string", "switch", "throw", "trait", "try", "unset", "use", "var", "void", "while", "xor", "yield"], ["literal"] = ["false", "FALSE", "null", "NULL", "true", "TRUE"], ["built_in"] = ["Error|0", "AppendIterator", "ArgumentCountError", "ArithmeticError", "ArrayIterator", "ArrayObject", "AssertionError", "BadFunctionCallException", "BadMethodCallException", "CachingIterator", "CallbackFilterIterator", "CompileError", "Countable", "DirectoryIterator", "DivisionByZeroError", "DomainException", "EmptyIterator", "ErrorException", "Exception", "FilesystemIterator", "FilterIterator", "GlobIterator", "InfiniteIterator", "InvalidArgumentException", "IteratorIterator", "LengthException", "LimitIterator", "LogicException", "MultipleIterator", "NoRewindIterator", "OutOfBoundsException", "OutOfRangeException", "OuterIterator", "OverflowException", "ParentIterator", "ParseError", "RangeException", "RecursiveArrayIterator", "RecursiveCachingIterator", "RecursiveCallbackFilterIterator", "RecursiveDirectoryIterator", "RecursiveFilterIterator", "RecursiveIterator", "RecursiveIteratorIterator", "RecursiveRegexIterator", "RecursiveTreeIterator", "RegexIterator", "RuntimeException", "SeekableIterator", "SplDoublyLinkedList", "SplFileInfo", "SplFileObject", "SplFixedArray", "SplHeap", "SplMaxHeap", "SplMinHeap", "SplObjectStorage", "SplObserver", "SplPriorityQueue", "SplQueue", "SplStack", "SplSubject", "SplTempFileObject", "TypeError", "UnderflowException", "UnexpectedValueException", "UnhandledMatchError", "ArrayAccess", "BackedEnum", "Closure", "Fiber", "Generator", "Iterator", "IteratorAggregate", "Serializable", "Stringable", "Throwable", "Traversable", "UnitEnum", "WeakReference", "WeakMap", "Directory", "__PHP_Incomplete_Class", "parent", "php_user_filter", "self", "static", "stdClass"] }) };
        var attribute = new Mode { End = "]", EndScope = "meta", Keywords = Keywords.FromMap(new Dictionary<string, string[]>(StringComparer.Ordinal) { ["literal"] = ["false", "null", "true"], ["keyword"] = ["new", "array"] }), BeginParts = ["#\\[\\s*\\\\?(?:(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])|[A-Z]+(?![A-Za-z0-9])(?![$]))"], BeginScope = new Dictionary<int, string> { [1] = "meta" } };
        var nestedArray = new Mode { Begin = "\\[", End = "]", Keywords = Keywords.FromMap(new Dictionary<string, string[]>(StringComparer.Ordinal) { ["literal"] = ["false", "null", "true"], ["keyword"] = ["new", "array"] }) };
        var namedArgument = new Mode { Scope = "attr", Match = "[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])(?=:)(?=(?!::))" };
        var classMemberAccess = new Mode { };
        var staticConstant = new Mode { BeginParts = ["::(?=(?!class\\b))", "[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])\\b(?!\\()"], BeginScope = new Dictionary<int, string> { [2] = "variable.constant" } };
        var classKeyword = new Mode { BeginParts = ["::", "class"], BeginScope = new Dictionary<int, string> { [2] = "variable.language" } };
        var classStaticConstant = new Mode { BeginParts = ["(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])", "::(?=(?!class\\b))", "[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])\\b(?!\\()"], BeginScope = new Dictionary<int, string> { [1] = "title.class", [3] = "variable.constant" } };
        var classStaticMember = new Mode { BeginParts = ["(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])", "::(?=(?!class\\b))"], BeginScope = new Dictionary<int, string> { [1] = "title.class" } };
        var classClassKeyword = new Mode { BeginParts = ["(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])", "::", "class"], BeginScope = new Dictionary<int, string> { [1] = "title.class", [3] = "variable.language" } };
        var blockComment = new Mode { Scope = "comment", Begin = "/\\*", End = "\\*/" };
        var blockCommentDocTag = new Mode { Scope = "doctag", Begin = "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", End = "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", ExcludeBegin = true };
        var blockCommentSentence = new Mode { Begin = "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}" };
        var stringWrapper = new Mode { Scope = "string" };
        var doubleQuotedString = new Mode { Scope = "string", Begin = "\"", End = "\"" };
        var escapeSequence = new Mode { Begin = "\\\\[\\s\\S]" };
        var substitution = new Mode { Scope = "subst" };
        var variableInString = new Mode { Begin = "\\$\\w+" };
        var bracedVariable = new Mode { Begin = "\\{\\$", End = "\\}" };
        var singleQuotedString = new Mode { Scope = "string", Begin = "'", End = "'" };
        var heredoc = new Mode { Begin = "<<<[ \\t]*(?:(\\w+)|\"(\\w+)\")\\n", End = "[ \\t]*(\\w+)\\b", EndSameAsBegin = true };
        var nowdoc = new Mode { Begin = "<<<[ \\t]*'(\\w+)'\\n", End = "[ \\t]*(\\w+)\\b", EndSameAsBegin = true };
        var number = new Mode { Scope = "number" };
        var binaryNumber = new Mode { Begin = "\\b0[bB][01]+(?:_[01]+)*\\b" };
        var octalNumber = new Mode { Begin = "\\b0[oO][0-7]+(?:_[0-7]+)*\\b" };
        var hexNumber = new Mode { Begin = "\\b0[xX][\\da-fA-F]+(?:_[\\da-fA-F]+)*\\b" };
        var decimalNumber = new Mode { Begin = "(?:\\b\\d+(?:_\\d+)*(\\.(?:\\d+(?:_\\d+)*))?|\\B\\.\\d+)(?:[eE][+-]?\\d+)?" };
        var classNameWrapper = new Mode { };
        var newExpression = new Mode { BeginParts = ["new", "[ \t\n]+", "(?!Error\\b|AppendIterator\\b|ArgumentCountError\\b|ArithmeticError\\b|ArrayIterator\\b|ArrayObject\\b|AssertionError\\b|BadFunctionCallException\\b|BadMethodCallException\\b|CachingIterator\\b|CallbackFilterIterator\\b|CompileError\\b|Countable\\b|DirectoryIterator\\b|DivisionByZeroError\\b|DomainException\\b|EmptyIterator\\b|ErrorException\\b|Exception\\b|FilesystemIterator\\b|FilterIterator\\b|GlobIterator\\b|InfiniteIterator\\b|InvalidArgumentException\\b|IteratorIterator\\b|LengthException\\b|LimitIterator\\b|LogicException\\b|MultipleIterator\\b|NoRewindIterator\\b|OutOfBoundsException\\b|OutOfRangeException\\b|OuterIterator\\b|OverflowException\\b|ParentIterator\\b|ParseError\\b|RangeException\\b|RecursiveArrayIterator\\b|RecursiveCachingIterator\\b|RecursiveCallbackFilterIterator\\b|RecursiveDirectoryIterator\\b|RecursiveFilterIterator\\b|RecursiveIterator\\b|RecursiveIteratorIterator\\b|RecursiveRegexIterator\\b|RecursiveTreeIterator\\b|RegexIterator\\b|RuntimeException\\b|SeekableIterator\\b|SplDoublyLinkedList\\b|SplFileInfo\\b|SplFileObject\\b|SplFixedArray\\b|SplHeap\\b|SplMaxHeap\\b|SplMinHeap\\b|SplObjectStorage\\b|SplObserver\\b|SplPriorityQueue\\b|SplQueue\\b|SplStack\\b|SplSubject\\b|SplTempFileObject\\b|TypeError\\b|UnderflowException\\b|UnexpectedValueException\\b|UnhandledMatchError\\b|ArrayAccess\\b|BackedEnum\\b|Closure\\b|Fiber\\b|Generator\\b|Iterator\\b|IteratorAggregate\\b|Serializable\\b|Stringable\\b|Throwable\\b|Traversable\\b|UnitEnum\\b|WeakReference\\b|WeakMap\\b|Directory\\b|__PHP_Incomplete_Class\\b|parent\\b|php_user_filter\\b|self\\b|static\\b|stdClass\\b)", "(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])"], BeginScope = new Dictionary<int, string> { [1] = "keyword", [4] = "title.class" } };
        var typeRef = new Mode { Scope = "meta" };
        var pascalCaseName = new Mode { Match = "(\\\\?[A-Z][a-z0-9_\\x7f-\\xff]+|\\\\?[A-Z]+(?=[A-Z][a-z0-9_\\x7f-\\xff])){1,}(?![A-Za-z0-9])(?![$])" };
        var upperCaseName = new Mode { Match = "[A-Z]+(?![A-Za-z0-9])(?![$])" };
        var hashComment = new Mode { Scope = "comment", Begin = "#", End = "$" };
        var hashCommentDocTag = new Mode { Scope = "doctag", Begin = "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", End = "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", ExcludeBegin = true };
        var hashCommentSentence = new Mode { Begin = "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}" };
        var lineComment = new Mode { Scope = "comment", Begin = "//", End = "$" };
        var lineCommentDocTag = new Mode { Scope = "doctag", Begin = "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", End = "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", ExcludeBegin = true };
        var lineCommentSentence = new Mode { Begin = "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}" };
        var phpDocComment = new Mode { Scope = "comment", Begin = "/\\*", End = "\\*/" };
        var phpDocAnnotation = new Mode { Scope = "doctag", Match = "@[A-Za-z]+" };
        var phpDocDocTagMarker = new Mode { Scope = "doctag", Begin = "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", End = "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", ExcludeBegin = true };
        var phpDocSentence = new Mode { Begin = "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}" };
        var haltCompiler = new Mode { Match = "__halt_compiler\\(\\);", Keywords = Keywords.FromWords(["__halt_compiler"]) };
        var afterHaltComment = new Mode { Scope = "comment", End = "\\b\\B" };
        var phpCloseTag = new Mode { Scope = "meta", Match = "\\?>", EndsParent = true };
        var phpTag = new Mode { Scope = "meta" };
        var phpOpenTag = new Mode { Begin = "<\\?php" };
        var phpShortEchoTag = new Mode { Begin = "<\\?=" };
        var phpShortTag = new Mode { Begin = "<\\?" };
        var phpCloseTagMeta = new Mode { Begin = "\\?>" };
        var thisVariable = new Mode { Scope = "variable.language", Match = "\\$this\\b" };
        var variableRef = new Mode { Scope = "variable", Match = "\\$+[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])" };
        var functionInvocation = new Mode { BeginParts = ["\\b", "(?!fn\\b|function\\b|__CLASS__\\b|__DIR__\\b|__FILE__\\b|__FUNCTION__\\b|__COMPILER_HALT_OFFSET__\\b|__LINE__\\b|__METHOD__\\b|__NAMESPACE__\\b|__TRAIT__\\b|die\\b|echo\\b|exit\\b|include\\b|include_once\\b|print\\b|require\\b|require_once\\b|array\\b|abstract\\b|and\\b|as\\b|binary\\b|bool\\b|boolean\\b|break\\b|callable\\b|case\\b|catch\\b|class\\b|clone\\b|const\\b|continue\\b|declare\\b|default\\b|do\\b|double\\b|else\\b|elseif\\b|empty\\b|enddeclare\\b|endfor\\b|endforeach\\b|endif\\b|endswitch\\b|endwhile\\b|enum\\b|eval\\b|extends\\b|final\\b|finally\\b|float\\b|for\\b|foreach\\b|from\\b|global\\b|goto\\b|if\\b|implements\\b|instanceof\\b|insteadof\\b|int\\b|integer\\b|interface\\b|isset\\b|iterable\\b|list\\b|match\\b|mixed\\b|new\\b|never\\b|object\\b|or\\b|private\\b|protected\\b|public\\b|readonly\\b|real\\b|return\\b|string\\b|switch\\b|throw\\b|trait\\b|try\\b|unset\\b|use\\b|var\\b|void\\b|while\\b|xor\\b|yield|Error\\b|AppendIterator\\b|ArgumentCountError\\b|ArithmeticError\\b|ArrayIterator\\b|ArrayObject\\b|AssertionError\\b|BadFunctionCallException\\b|BadMethodCallException\\b|CachingIterator\\b|CallbackFilterIterator\\b|CompileError\\b|Countable\\b|DirectoryIterator\\b|DivisionByZeroError\\b|DomainException\\b|EmptyIterator\\b|ErrorException\\b|Exception\\b|FilesystemIterator\\b|FilterIterator\\b|GlobIterator\\b|InfiniteIterator\\b|InvalidArgumentException\\b|IteratorIterator\\b|LengthException\\b|LimitIterator\\b|LogicException\\b|MultipleIterator\\b|NoRewindIterator\\b|OutOfBoundsException\\b|OutOfRangeException\\b|OuterIterator\\b|OverflowException\\b|ParentIterator\\b|ParseError\\b|RangeException\\b|RecursiveArrayIterator\\b|RecursiveCachingIterator\\b|RecursiveCallbackFilterIterator\\b|RecursiveDirectoryIterator\\b|RecursiveFilterIterator\\b|RecursiveIterator\\b|RecursiveIteratorIterator\\b|RecursiveRegexIterator\\b|RecursiveTreeIterator\\b|RegexIterator\\b|RuntimeException\\b|SeekableIterator\\b|SplDoublyLinkedList\\b|SplFileInfo\\b|SplFileObject\\b|SplFixedArray\\b|SplHeap\\b|SplMaxHeap\\b|SplMinHeap\\b|SplObjectStorage\\b|SplObserver\\b|SplPriorityQueue\\b|SplQueue\\b|SplStack\\b|SplSubject\\b|SplTempFileObject\\b|TypeError\\b|UnderflowException\\b|UnexpectedValueException\\b|UnhandledMatchError\\b|ArrayAccess\\b|BackedEnum\\b|Closure\\b|Fiber\\b|Generator\\b|Iterator\\b|IteratorAggregate\\b|Serializable\\b|Stringable\\b|Throwable\\b|Traversable\\b|UnitEnum\\b|WeakReference\\b|WeakMap\\b|Directory\\b|__PHP_Incomplete_Class\\b|parent\\b|php_user_filter\\b|self\\b|static\\b|stdClass\\b)", "[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])", "[ \t\n]*", "(?=(?=\\())"], BeginScope = new Dictionary<int, string> { [3] = "title.function.invoke" } };
        var callArgs = new Mode { Begin = "\\(", End = "\\)", Keywords = Keywords.FromMap(new Dictionary<string, string[]>(StringComparer.Ordinal) { ["keyword"] = ["__CLASS__", "__DIR__", "__FILE__", "__FUNCTION__", "__COMPILER_HALT_OFFSET__", "__LINE__", "__METHOD__", "__NAMESPACE__", "__TRAIT__", "die", "echo", "exit", "include", "include_once", "print", "require", "require_once", "array", "abstract", "and", "as", "binary", "bool", "boolean", "break", "callable", "case", "catch", "class", "clone", "const", "continue", "declare", "default", "do", "double", "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif", "endswitch", "endwhile", "enum", "eval", "extends", "final", "finally", "float", "for", "foreach", "from", "global", "goto", "if", "implements", "instanceof", "insteadof", "int", "integer", "interface", "isset", "iterable", "list", "match|0", "mixed", "new", "never", "object", "or", "private", "protected", "public", "readonly", "real", "return", "string", "switch", "throw", "trait", "try", "unset", "use", "var", "void", "while", "xor", "yield"], ["literal"] = ["false", "FALSE", "null", "NULL", "true", "TRUE"], ["built_in"] = ["Error|0", "AppendIterator", "ArgumentCountError", "ArithmeticError", "ArrayIterator", "ArrayObject", "AssertionError", "BadFunctionCallException", "BadMethodCallException", "CachingIterator", "CallbackFilterIterator", "CompileError", "Countable", "DirectoryIterator", "DivisionByZeroError", "DomainException", "EmptyIterator", "ErrorException", "Exception", "FilesystemIterator", "FilterIterator", "GlobIterator", "InfiniteIterator", "InvalidArgumentException", "IteratorIterator", "LengthException", "LimitIterator", "LogicException", "MultipleIterator", "NoRewindIterator", "OutOfBoundsException", "OutOfRangeException", "OuterIterator", "OverflowException", "ParentIterator", "ParseError", "RangeException", "RecursiveArrayIterator", "RecursiveCachingIterator", "RecursiveCallbackFilterIterator", "RecursiveDirectoryIterator", "RecursiveFilterIterator", "RecursiveIterator", "RecursiveIteratorIterator", "RecursiveRegexIterator", "RecursiveTreeIterator", "RegexIterator", "RuntimeException", "SeekableIterator", "SplDoublyLinkedList", "SplFileInfo", "SplFileObject", "SplFixedArray", "SplHeap", "SplMaxHeap", "SplMinHeap", "SplObjectStorage", "SplObserver", "SplPriorityQueue", "SplQueue", "SplStack", "SplSubject", "SplTempFileObject", "TypeError", "UnderflowException", "UnexpectedValueException", "UnhandledMatchError", "ArrayAccess", "BackedEnum", "Closure", "Fiber", "Generator", "Iterator", "IteratorAggregate", "Serializable", "Stringable", "Throwable", "Traversable", "UnitEnum", "WeakReference", "WeakMap", "Directory", "__PHP_Incomplete_Class", "parent", "php_user_filter", "self", "static", "stdClass"] }) };
        var constDeclaration = new Mode { BeginParts = ["const", "\\s", "[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(?![A-Za-z0-9])(?![$])"], BeginScope = new Dictionary<int, string> { [1] = "keyword", [3] = "variable.constant" } };
        var functionDecl = new Mode { Scope = "function", End = "[;{]", BeginKeywords = ["fn", "function"], Illegal = "[$%\\[]", ExcludeEnd = true };
        var useTraitInClass = new Mode { BeginKeywords = ["use"] };
        var titleIdentifier = new Mode { Scope = "title", Begin = "[a-zA-Z_]\\w*" };
        var arrowReturn = new Mode { Begin = "=>", EndsParent = true };
        var functionParams = new Mode { Scope = "params", Begin = "\\(", End = "\\)", ExcludeBegin = true, ExcludeEnd = true, Keywords = Keywords.FromMap(new Dictionary<string, string[]>(StringComparer.Ordinal) { ["keyword"] = ["__CLASS__", "__DIR__", "__FILE__", "__FUNCTION__", "__COMPILER_HALT_OFFSET__", "__LINE__", "__METHOD__", "__NAMESPACE__", "__TRAIT__", "die", "echo", "exit", "include", "include_once", "print", "require", "require_once", "array", "abstract", "and", "as", "binary", "bool", "boolean", "break", "callable", "case", "catch", "class", "clone", "const", "continue", "declare", "default", "do", "double", "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif", "endswitch", "endwhile", "enum", "eval", "extends", "final", "finally", "float", "for", "foreach", "from", "global", "goto", "if", "implements", "instanceof", "insteadof", "int", "integer", "interface", "isset", "iterable", "list", "match|0", "mixed", "new", "never", "object", "or", "private", "protected", "public", "readonly", "real", "return", "string", "switch", "throw", "trait", "try", "unset", "use", "var", "void", "while", "xor", "yield"], ["literal"] = ["false", "FALSE", "null", "NULL", "true", "TRUE"], ["built_in"] = ["Error|0", "AppendIterator", "ArgumentCountError", "ArithmeticError", "ArrayIterator", "ArrayObject", "AssertionError", "BadFunctionCallException", "BadMethodCallException", "CachingIterator", "CallbackFilterIterator", "CompileError", "Countable", "DirectoryIterator", "DivisionByZeroError", "DomainException", "EmptyIterator", "ErrorException", "Exception", "FilesystemIterator", "FilterIterator", "GlobIterator", "InfiniteIterator", "InvalidArgumentException", "IteratorIterator", "LengthException", "LimitIterator", "LogicException", "MultipleIterator", "NoRewindIterator", "OutOfBoundsException", "OutOfRangeException", "OuterIterator", "OverflowException", "ParentIterator", "ParseError", "RangeException", "RecursiveArrayIterator", "RecursiveCachingIterator", "RecursiveCallbackFilterIterator", "RecursiveDirectoryIterator", "RecursiveFilterIterator", "RecursiveIterator", "RecursiveIteratorIterator", "RecursiveRegexIterator", "RecursiveTreeIterator", "RegexIterator", "RuntimeException", "SeekableIterator", "SplDoublyLinkedList", "SplFileInfo", "SplFileObject", "SplFixedArray", "SplHeap", "SplMaxHeap", "SplMinHeap", "SplObjectStorage", "SplObserver", "SplPriorityQueue", "SplQueue", "SplStack", "SplSubject", "SplTempFileObject", "TypeError", "UnderflowException", "UnexpectedValueException", "UnhandledMatchError", "ArrayAccess", "BackedEnum", "Closure", "Fiber", "Generator", "Iterator", "IteratorAggregate", "Serializable", "Stringable", "Throwable", "Traversable", "UnitEnum", "WeakReference", "WeakMap", "Directory", "__PHP_Incomplete_Class", "parent", "php_user_filter", "self", "static", "stdClass"] }) };
        var classDecl = new Mode { Scope = "class", End = "\\{", ExcludeEnd = true };
        var classExtendsImplements = new Mode { BeginKeywords = ["extends", "implements"] };
        var enumDecl = new Mode { BeginKeywords = ["enum"], Illegal = "[($\"]" };
        var classInterfaceTrait = new Mode { BeginKeywords = ["class", "interface", "trait"], Illegal = "[:($\"]" };
        var namespaceDecl = new Mode { End = ";", BeginKeywords = ["namespace"], Illegal = "[.']" };
        var classNameTitle = new Mode { Scope = "title.class", Begin = "[a-zA-Z_]\\w*" };
        var useStatement = new Mode { End = ";", BeginKeywords = ["use"] };
        var useKeyword = new Mode { Scope = "keyword", Match = "\\b(as|const|function)\\b" };

        root.Contains = [attribute, hashComment, lineComment, phpDocComment, haltCompiler, phpTag, thisVariable, variableRef, functionInvocation, classMemberAccess, constDeclaration, classNameWrapper, functionDecl, classDecl, namespaceDecl, useStatement, stringWrapper, number];
        attribute.Contains = [nestedArray, namedArgument, classMemberAccess, blockComment, stringWrapper, number, classNameWrapper, typeRef];
        nestedArray.Contains = [nestedArray, namedArgument, classMemberAccess, blockComment, stringWrapper, number, classNameWrapper];
        classMemberAccess.Variants = [staticConstant, classKeyword, classStaticConstant, classStaticMember, classClassKeyword];
        blockComment.Contains = [blockCommentDocTag, blockCommentSentence];
        stringWrapper.Variants = [doubleQuotedString, singleQuotedString, heredoc, nowdoc];
        doubleQuotedString.Contains = [escapeSequence, substitution];
        substitution.Variants = [variableInString, bracedVariable];
        singleQuotedString.Contains = [escapeSequence];
        heredoc.Contains = [escapeSequence, substitution];
        number.Variants = [binaryNumber, octalNumber, hexNumber, decimalNumber];
        classNameWrapper.Variants = [newExpression];
        typeRef.Variants = [pascalCaseName, upperCaseName];
        hashComment.Contains = [hashCommentDocTag, hashCommentSentence];
        lineComment.Contains = [lineCommentDocTag, lineCommentSentence];
        phpDocComment.Contains = [phpDocAnnotation, phpDocDocTagMarker, phpDocSentence];
        haltCompiler.Starts = afterHaltComment;
        afterHaltComment.Contains = [phpCloseTag];
        phpTag.Variants = [phpOpenTag, phpShortEchoTag, phpShortTag, phpCloseTagMeta];
        functionInvocation.Contains = [callArgs];
        callArgs.Contains = [namedArgument, variableRef, classMemberAccess, blockComment, stringWrapper, number, classNameWrapper, functionInvocation];
        functionDecl.Contains = [useTraitInClass, titleIdentifier, arrowReturn, functionParams];
        functionParams.Contains = [functionParams, attribute, variableRef, classMemberAccess, blockComment, stringWrapper, number];
        classDecl.Contains = [classExtendsImplements, titleIdentifier];
        classDecl.Variants = [enumDecl, classInterfaceTrait];
        namespaceDecl.Contains = [classNameTitle];
        useStatement.Contains = [useKeyword, titleIdentifier];

        return root;
    }
}
