<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.SyntaxHighlighting/Meziantou.Framework.SyntaxHighlighting.csproj" />
    <Compile Include="../../common/ThreadCpuStopwatch.cs" Link="ThreadCpuStopwatch.cs" />
  </ItemGroup>

</Project>