# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  status:
    project:
      default: false
    patch:
      default: false

comment:
  layout: "diff, files" # https://docs.codecov.com/docs/pull-request-comments#layout
  require_changes: yes  # https://docs.codecov.com/docs/pull-request-comments#requiring-changes
