<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>2.0.1</Version>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <Description>HAR 1.2 (HTTP Archive) format parser and writer</Description>
    <PackageTags>har, http-archive, http, parser, serialization</PackageTags>
  </PropertyGroup>

</Project>
