<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <IsTrimmable>true</IsTrimmable>
    <RootNamespace>Meziantou.Framework.Diagnostics</RootNamespace>
    <Version>1.0.0</Version>
    <Description>Create a memory dump of the current process on Windows, Linux, and macOS</Description>
    <PackageTags>diagnostics, memory-dump, minidump, createdump, troubleshooting</PackageTags>
  </PropertyGroup>

</Project>
