<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>2.0.4</Version>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <Description>Provide types to cache http response as described in RFC 7234</Description>
  </PropertyGroup>

</Project>
