<Project Sdk="Meziantou.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <IsPackable>false</IsPackable>

    <IncludeDefaultTestReferences>false</IncludeDefaultTestReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tomlyn\Tomlyn.csproj" />
    <ProjectReference Include="..\..\src\Tomlyn.SourceGeneration\Tomlyn.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="twitter.toml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
