<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework</RootNamespace>
    <Version>4.0.1</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>Command-line argument parsing, argument escaping, and interactive console prompts</Description>
    <PackageTags>command-line, cli, arguments, parser, console, prompt</PackageTags>
    <DefineConstants>$(DefineConstants);CommandLineBuilder_PUBLIC</DefineConstants>
  </PropertyGroup>

</Project>
