<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.AtlassianDataFormat.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.AtlassianDataFormat/Meziantou.Framework.AtlassianDataFormat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData/**/*">
      <LogicalName>$([System.String]::new('%(RelativeDir)').Replace('\','/'))%(FileName)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
