<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.HtmlToMarkdownTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.HtmlToMarkdown/Meziantou.Framework.HtmlToMarkdown.csproj" />
    <ProjectReference Include="../../src/Meziantou.Framework.Markdown/Meziantou.Framework.Markdown.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData/**/*" />
  </ItemGroup>

</Project>
