<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>2.0.8</Version>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <Description>Provide Redis persistence provider for Meziantou.Framework.Http.Caching</Description>
    <PackageTags>http, caching, redis, httpclient</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Meziantou.Framework.Http.Caching/Meziantou.Framework.Http.Caching.csproj" />
  </ItemGroup>

</Project>
