<Project Sdk="Meziantou.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFramework);netstandard2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoWarn>$(NoWarn);RS1041</NoWarn>
    <IncludeRoslynHelpers>true</IncludeRoslynHelpers>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/TagInfo.cs" Link="TagInfo.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/TagResolver.cs" Link="TagResolver.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/TypeArgumentComments.cs" Link="TypeArgumentComments.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/ValueTagComment.cs" Link="ValueTagComment.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/ValueTagCommentKind.cs" Link="ValueTagCommentKind.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/ValueTagDiagnostics.cs" Link="ValueTagDiagnostics.cs" />
    <Compile Include="../Meziantou.Framework.TaggedValues.Analyzer/ValueTagTargetKind.cs" Link="ValueTagTargetKind.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
