<Project Sdk="Meziantou.NET.Sdk.Test">
  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.Language.Toml.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.Language.Toml/Meziantou.Framework.Language.Toml.csproj" />
  </ItemGroup>
</Project>
