<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <IsTrimmable>true</IsTrimmable>
    <Description>Types and extension methods to help with threading</Description>
    <Version>3.1.0</Version>
    <RootNamespace>Meziantou.Framework</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Meziantou.Framework.Threading.Tests" />
  </ItemGroup>

</Project>
