using Xunit.Sdk;

namespace Meziantou.Framework.PublicApiGenerator.MSBuild.Tests;

public sealed class PublicApiGeneratorMsBuildTests(PublicApiGeneratorMsBuildPackageFixture fixture) : IClassFixture<PublicApiGeneratorMsBuildPackageFixture>
{
    [Fact]
    public async Task GenerateOnBuild_SingleTarget_GeneratesFile()
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("single");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        temporaryDirectory.CreateTextFile("single/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <PublicApiGeneratorOutputPath>PublicApi/PublicApi.g.cs</PublicApiGeneratorOutputPath>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("single/Sample.cs", """
            public class Sample
            {
                public void A()
                {
                }
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 0);

        var generatedFilePath = projectDirectory / "PublicApi" / "PublicApi.g.cs";
        Assert.True(File.Exists(generatedFilePath));
        var content = await File.ReadAllTextAsync(generatedFilePath, XunitCancellationToken);
        Assert.Contains("public class Sample", content, StringComparison.Ordinal);
        Assert.Contains("public void A() { }", content, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("SingleFile")]
    [InlineData("OneFilePerNamespace")]
    [InlineData("OneFilePerType")]
    public async Task GenerateOnBuild_SingleTarget_SupportsOutputModes(string fileLayout)
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("output-mode");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        var outputPath = fileLayout is "SingleFile" ? "PublicApi/PublicApi.g.cs" : "PublicApi";
        temporaryDirectory.CreateTextFile("output-mode/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <PublicApiGeneratorOutputPath>{{outputPath}}</PublicApiGeneratorOutputPath>
                <PublicApiGeneratorFileLayout>{{fileLayout}}</PublicApiGeneratorFileLayout>
                <PublicApiGeneratorIncludeAutoGeneratedComment>false</PublicApiGeneratorIncludeAutoGeneratedComment>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("output-mode/Sample.cs", """
            public class GlobalType
            {
            }

            namespace Demo
            {
                public class Other
                {
                }

                public class Sample
                {
                }
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 0);

        switch (fileLayout)
        {
            case "SingleFile":
                {
                    var generatedFilePath = projectDirectory / "PublicApi" / "PublicApi.g.cs";
                    Assert.True(File.Exists(generatedFilePath));
                    var content = await File.ReadAllTextAsync(generatedFilePath, XunitCancellationToken);
                    Assert.Contains("public class GlobalType", content, StringComparison.Ordinal);
                    Assert.Contains("public class Other", content, StringComparison.Ordinal);
                    Assert.Contains("public class Sample", content, StringComparison.Ordinal);
                    break;
                }
            case "OneFilePerNamespace":
                Assert.True(File.Exists(projectDirectory / "PublicApi" / "Demo.g.cs"));
                Assert.True(File.Exists(projectDirectory / "PublicApi" / "GlobalNamespace.g.cs"));
                break;
            case "OneFilePerType":
                Assert.True(File.Exists(projectDirectory / "PublicApi" / "Demo.Other.g.cs"));
                Assert.True(File.Exists(projectDirectory / "PublicApi" / "Demo.Sample.g.cs"));
                Assert.True(File.Exists(projectDirectory / "PublicApi" / "GlobalType.g.cs"));
                break;
            default:
                throw new XunitException($"Unsupported file layout '{fileLayout}'.");
        }
    }

    [Fact]
    public async Task GenerateOnBuild_MultiTarget_MergesTargetOutputs()
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("multi");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        temporaryDirectory.CreateTextFile("multi/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
                <PublicApiGeneratorOutputPath>obj/PublicApi/PublicApi.g.cs</PublicApiGeneratorOutputPath>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("multi/Sample.cs", """
            public class Sample
            {
                public void A()
                {
                }

            #if NET10_0
                public void B()
                {
                }
            #endif
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 0);

        var generatedFilePath = projectDirectory / "obj" / "PublicApi" / "PublicApi.g.cs";
        Assert.True(File.Exists(generatedFilePath));
        var content = await File.ReadAllTextAsync(generatedFilePath, XunitCancellationToken);
        Assert.Contains("public class Sample", content, StringComparison.Ordinal);
        Assert.Contains("public void A() { }", content, StringComparison.Ordinal);
        Assert.Contains("#if NET10_0", content, StringComparison.Ordinal);
        Assert.Contains("public void B() { }", content, StringComparison.Ordinal);
    }

    [Fact]
    public async Task GenerateOnBuild_MissingOutputPath_FailsBuild()
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("missing-output");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        temporaryDirectory.CreateTextFile("missing-output/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("missing-output/Sample.cs", """
            public class Sample
            {
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        var buildResult = await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 1);
        var buildOutput = string.Join('\n', buildResult.Output);
        Assert.Contains("PublicApiGeneratorOutputPath", buildOutput, StringComparison.Ordinal);
    }

    [Fact]
    public async Task VerifyNoChangeOnBuild_UpToDateFile_Succeeds()
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("validate-up-to-date");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        temporaryDirectory.CreateTextFile("validate-up-to-date/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <PublicApiGeneratorOutputPath>obj/PublicApi/PublicApi.g.cs</PublicApiGeneratorOutputPath>
                <PublicApiGeneratorIncludeAutoGeneratedComment>false</PublicApiGeneratorIncludeAutoGeneratedComment>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("validate-up-to-date/Sample.cs", """
            public class Sample
            {
                public void A()
                {
                }
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo", "/p:PublicApiGeneratorVerifyNoChangeOnBuild=true"], expectedExitCode: 0);
    }

    [Fact]
    public async Task VerifyNoChangeOnBuild_OutOfDateFile_FailsWithoutOverwriting()
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        var projectDirectory = temporaryDirectory.CreateDirectory("validate-out-of-date");
        CreateGlobalJson(projectDirectory, fixture.DotnetSdkVersion);
        CreateNuGetConfig(projectDirectory, fixture.PackagesDirectory);

        temporaryDirectory.CreateTextFile("validate-out-of-date/Sample.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <PublicApiGeneratorOutputPath>obj/PublicApi/PublicApi.g.cs</PublicApiGeneratorOutputPath>
                <PublicApiGeneratorIncludeAutoGeneratedComment>false</PublicApiGeneratorIncludeAutoGeneratedComment>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Meziantou.Framework.PublicApiGenerator.MSBuild" Version="{{fixture.PackageVersion}}" PrivateAssets="all" />
              </ItemGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile("validate-out-of-date/Sample.cs", """
            public class Sample
            {
                public void A()
                {
                }
            }
            """);

        await RunDotNetCommand(projectDirectory, ["restore", "--disable-build-servers"], expectedExitCode: 0);
        await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo"], expectedExitCode: 0);

        var generatedFilePath = projectDirectory / "obj" / "PublicApi" / "PublicApi.g.cs";
        await File.WriteAllTextAsync(generatedFilePath, "// stale", XunitCancellationToken);

        var buildResult = await RunDotNetCommand(projectDirectory, ["build", "--no-restore", "--disable-build-servers", "-nologo", "/p:PublicApiGeneratorVerifyNoChangeOnBuild=true"], expectedExitCode: 1);
        var buildOutput = string.Join('\n', buildResult.Output);
        Assert.Contains("out of date", buildOutput, StringComparison.Ordinal);
        Assert.Equal("// stale", await File.ReadAllTextAsync(generatedFilePath, XunitCancellationToken));
    }

    private static void CreateGlobalJson(FullPath projectDirectory, string dotnetSdkVersion)
    {
        File.WriteAllText(projectDirectory / "global.json", $$"""
            {
              "sdk": {
                "version": "{{dotnetSdkVersion}}",
                "rollForward": "latestFeature"
              }
            }
            """);
    }

    private static void CreateNuGetConfig(FullPath projectDirectory, FullPath packagesDirectory)
    {
        var packagesCachePath = packagesDirectory / "global-packages";
        File.WriteAllText(projectDirectory / "NuGet.config", $$"""
            <?xml version="1.0" encoding="utf-8"?>
            <configuration>
              <config>
                <add key="globalPackagesFolder" value="{{packagesCachePath}}" />
              </config>
              <packageSources>
                <clear />
                <add key="local" value="{{packagesDirectory}}" />
                <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
              </packageSources>
              <packageSourceMapping>
                <packageSource key="local">
                  <package pattern="Meziantou.Framework.PublicApiGenerator.MSBuild*" />
                </packageSource>
                <packageSource key="nuget.org">
                  <package pattern="*" />
                </packageSource>
              </packageSourceMapping>
            </configuration>
            """);
    }

    private static async Task<BufferedProcessResult> RunDotNetCommand(FullPath workingDirectory, IReadOnlyList<string> arguments, int expectedExitCode)
    {
        var result = await ProcessWrapper.Create("dotnet")
            .WithArguments(arguments)
            .WithWorkingDirectory(workingDirectory)
            .WithEnvironmentVariables(env => env.Set("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1"))
            .WithValidation(ProcessValidationMode.None)
            .ExecuteBufferedAsync(XunitCancellationToken);

        if (result.ExitCode != expectedExitCode)
        {
            var output = string.Join('\n', result.Output);
            throw new XunitException($"Command failed: dotnet {string.Join(' ', arguments)}\nExpected exit code: {expectedExitCode}\nActual exit code: {result.ExitCode}\nOutput:\n{output}");
        }

        return result;
    }

}
