namespace Meziantou.Framework.AtlassianDataFormat;

/// <summary>Identifies the type of an <see cref="AdfNode"/>.</summary>
public enum AdfNodeKind
{
    /// <summary>A node type that is not part of the supported schema.</summary>
    Unknown = 0,
    Paragraph,
    Heading,
    Blockquote,
    CodeBlock,
    Rule,
    BulletList,
    OrderedList,
    ListItem,
    Panel,
    Table,
    TableRow,
    TableCell,
    TableHeader,
    Expand,
    NestedExpand,
    TaskList,
    TaskItem,
    DecisionList,
    DecisionItem,
    MediaGroup,
    MediaSingle,
    Media,
    MediaInline,
    Caption,
    LayoutSection,
    LayoutColumn,
    BlockCard,
    EmbedCard,
    InlineCard,
    Extension,
    BodiedExtension,
    InlineExtension,
    Text,
    HardBreak,
    Emoji,
    Mention,
    Date,
    Status,
    Placeholder,
}
