<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>1.0.0</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>Parse the Atlassian Document Format (ADF) used by Jira, Confluence, and Bitbucket, and convert it to Markdown</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Meziantou.Framework.AtlassianDataFormat.Tests" />
  </ItemGroup>

</Project>
