// <auto-generated/>
// Target Frameworks: net10.0, net11.0
#nullable enable

namespace Meziantou.AspNetCore
{
    public static class NoCacheApplicationBuilderExtensions
    {
        public static Microsoft.AspNetCore.Builder.IApplicationBuilder UseNoCache(this Microsoft.AspNetCore.Builder.IApplicationBuilder app) => throw null;
    }

    public sealed class NoCacheMiddleware
    {
        public NoCacheMiddleware(Microsoft.AspNetCore.Http.RequestDelegate next) { }
        public System.Threading.Tasks.Task InvokeAsync(Microsoft.AspNetCore.Http.HttpContext context) => throw null;
    }
}
namespace Meziantou.AspNetCore.Diagnostics
{
    public sealed class MiddlewarePipelineDebugEndpoint
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public Microsoft.AspNetCore.Http.Endpoint? Endpoint { get => throw null; init { } }
        public string? DisplayName { get => throw null; init { } }
        public required string EndpointType { get => throw null; init { } }
        public string? RoutePattern { get => throw null; init { } }
        public int? Order { get => throw null; init { } }
        public required System.Collections.Generic.IReadOnlyList<string> HttpMethods { get => throw null; init { } }
    }

    public sealed class MiddlewarePipelineDebugInfoProvider
    {
        public MiddlewarePipelineDebugInfoProvider(System.IServiceProvider serviceProvider) { }
        public Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugSnapshot GetSnapshot() => throw null;
    }

    public sealed class MiddlewarePipelineDebugMiddleware
    {
        public required string Name { get => throw null; init { } }
        public string? DelegateType { get => throw null; init { } }
        public string? DelegateMethod { get => throw null; init { } }
        public required System.Collections.Generic.IReadOnlyList<Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugPipeline> Branches { get => throw null; init { } }
    }

    public sealed class MiddlewarePipelineDebugPipeline
    {
        public required System.Collections.Generic.IReadOnlyList<Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugMiddleware> Middlewares { get => throw null; init { } }
    }

    public sealed class MiddlewarePipelineDebugSnapshot
    {
        public required Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugPipeline Pipeline { get => throw null; init { } }
        public required bool IsPipelineCaptured { get => throw null; init { } }
        public required System.Collections.Generic.IReadOnlyList<Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugEndpoint> Endpoints { get => throw null; init { } }
        public override string ToString() => throw null;
    }

    public static class MiddlewarePipelineDebuggingServiceCollectionExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddMiddlewarePipelineDebugging(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) => throw null;
    }

    public static class MiddlewarePipelineDebuggingWebApplicationExtensions
    {
        public static Meziantou.AspNetCore.Diagnostics.MiddlewarePipelineDebugSnapshot GetMiddlewarePipelineDebugSnapshot(this Microsoft.AspNetCore.Builder.WebApplication app) => throw null;
        [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This method maps a delegate endpoint, which may use reflection and is not trim-safe.")]
        [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("This method maps a delegate endpoint that serializes the snapshot with reflection-based JSON serialization.")]
        public static Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMiddlewarePipelineDebugEndpoint(this Microsoft.AspNetCore.Builder.WebApplication app, string pattern = "/_debug/pipeline", bool developmentOnly = true) => throw null;
    }
}
