// <auto-generated/>
#nullable enable

namespace Meziantou.Framework.DnsFilter
{
    public readonly struct DnsClientInfo
    {
        public System.Net.IPAddress? Address { get => throw null; init { } }
        public string? Name { get => throw null; init { } }
        public System.Collections.Generic.IReadOnlyList<string>? Tags { get => throw null; init { } }
    }

    public enum DnsFilterAction
    {
        Block = 0,
        Allow = 1
    }

    public sealed class DnsFilterEngine
    {
        public DnsFilterEngine(global::Meziantou.Framework.DnsFilter.DnsFilterRuleSet ruleSet) { }
        public void Reload(global::Meziantou.Framework.DnsFilter.DnsFilterRuleSet ruleSet) { }
        public global::Meziantou.Framework.DnsFilter.DnsFilterResult Evaluate(string domain, global::Meziantou.Framework.DnsFilter.DnsFilterQueryType queryType = 1, global::Meziantou.Framework.DnsFilter.DnsClientInfo client = null) => throw null;
    }

    public enum DnsFilterListFormat
    {
        AutoDetect = 0,
        Hosts = 1,
        DomainsOnly = 2,
        AdBlock = 3
    }

    public static class DnsFilterListReader
    {
        public static System.Collections.Generic.IReadOnlyList<global::Meziantou.Framework.DnsFilter.DnsFilterRule> Parse(System.IO.TextReader reader, global::Meziantou.Framework.DnsFilter.DnsFilterListFormat format = 0) => throw null;
        public static System.Collections.Generic.IReadOnlyList<global::Meziantou.Framework.DnsFilter.DnsFilterRule> Parse(string text, global::Meziantou.Framework.DnsFilter.DnsFilterListFormat format = 0) => throw null;
    }

    public enum DnsFilterQueryType
    {
        A = 1,
        NS = 2,
        CNAME = 5,
        SOA = 6,
        PTR = 12,
        MX = 15,
        TXT = 16,
        AAAA = 28,
        SRV = 33,
        HTTPS = 65,
        ANY = 255
    }

    public sealed class DnsFilterResult
    {
        public static global::Meziantou.Framework.DnsFilter.DnsFilterResult NotMatched { get => throw null; }
        public bool IsMatched { get => throw null; }
        public global::Meziantou.Framework.DnsFilter.DnsFilterAction Action { get => throw null; }
        public global::Meziantou.Framework.DnsFilter.DnsFilterRule? MatchingRule { get => throw null; }
        public global::Meziantou.Framework.DnsFilter.DnsFilterRewriteRule? Rewrite { get => throw null; }
    }

    public enum DnsFilterRewriteResponseCode
    {
        NoError = 0,
        NameError = 1,
        Refused = 2
    }

    public sealed class DnsFilterRewriteRule
    {
        public global::Meziantou.Framework.DnsFilter.DnsFilterRewriteResponseCode ResponseCode { get => throw null; init { } }
        public global::Meziantou.Framework.DnsFilter.DnsFilterQueryType? RecordType { get => throw null; init { } }
        public string? Value { get => throw null; init { } }
    }

    public sealed class DnsFilterRule
    {
        public required string OriginalText { get => throw null; init { } }
        public required global::Meziantou.Framework.DnsFilter.DnsFilterAction Action { get => throw null; init { } }
        public bool IsImportant { get => throw null; init { } }
        public bool IsBadFilter { get => throw null; init { } }
        public System.Collections.Generic.IReadOnlyCollection<global::Meziantou.Framework.DnsFilter.DnsFilterQueryType>? AllowedDnsTypes { get => throw null; init { } }
        public System.Collections.Generic.IReadOnlyCollection<global::Meziantou.Framework.DnsFilter.DnsFilterQueryType>? ExcludedDnsTypes { get => throw null; init { } }
        public System.Collections.Generic.IReadOnlyCollection<string>? DenyAllowDomains { get => throw null; init { } }
        public global::Meziantou.Framework.DnsFilter.DnsFilterRewriteRule? Rewrite { get => throw null; init { } }
    }

    public sealed class DnsFilterRuleSet
    {
        public System.Collections.Generic.IReadOnlyList<global::Meziantou.Framework.DnsFilter.DnsFilterRule> Rules { get => throw null; }
        public void Add(global::Meziantou.Framework.DnsFilter.DnsFilterRule rule) { }
        public void AddRange(System.Collections.Generic.IEnumerable<global::Meziantou.Framework.DnsFilter.DnsFilterRule> rules) { }
        public void AddFromList(System.IO.TextReader reader, global::Meziantou.Framework.DnsFilter.DnsFilterListFormat format = 0) { }
        public void AddFromList(string text, global::Meziantou.Framework.DnsFilter.DnsFilterListFormat format = 0) { }
        public void Clear() { }
    }
}
