// <auto-generated/>
#nullable enable

namespace Meziantou.Framework
{
    public class TextChunker
    {
        public static Meziantou.Framework.TextChunker Lines { get => throw null; }
        public static Meziantou.Framework.TextChunker Words { get => throw null; }
        public static Meziantou.Framework.TextChunker Characters { get => throw null; }
        public virtual System.Collections.Generic.IEnumerable<string> Chunk(System.ReadOnlySpan<char> value) => throw null;
    }

    public static class TextDiff
    {
        public static Meziantou.Framework.TextDiffResult ComputeDiff(string oldText, string newText, Meziantou.Framework.TextDiffOptions? options = null) => throw null;
        public static Meziantou.Framework.TextDiffHierarchyResult ComputeHierarchyDiff(string oldText, string newText, System.Collections.Generic.IReadOnlyList<Meziantou.Framework.TextChunker> chunkers, Meziantou.Framework.TextDiffOptions? options = null) => throw null;
    }

    public enum TextDiffAlgorithm
    {
        Myers = 0,
        Patience = 1,
        Histogram = 2,
        HuntSzymanski = 3
    }

    public readonly struct TextDiffEntry : System.IEquatable<Meziantou.Framework.TextDiffEntry>
    {
        public Meziantou.Framework.TextDiffOperation Operation { get => throw null; }
        public string Text { get => throw null; }
        public TextDiffEntry(Meziantou.Framework.TextDiffOperation operation, string text) { }
        public bool Equals(Meziantou.Framework.TextDiffEntry other) => throw null;
        public override bool Equals(object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public static bool operator ==(Meziantou.Framework.TextDiffEntry left, Meziantou.Framework.TextDiffEntry right) => throw null;
        public static bool operator !=(Meziantou.Framework.TextDiffEntry left, Meziantou.Framework.TextDiffEntry right) => throw null;
        public override string ToString() => throw null;
    }

    public sealed class TextDiffHierarchyEntry
    {
        public Meziantou.Framework.TextDiffHierarchyOperation Operation { get => throw null; }
        public string? OldText { get => throw null; }
        public string? NewText { get => throw null; }
        public System.Collections.Generic.IReadOnlyList<Meziantou.Framework.TextDiffHierarchyEntry> Children { get => throw null; }
        public TextDiffHierarchyEntry(Meziantou.Framework.TextDiffHierarchyOperation operation, string? oldText, string? newText, System.Collections.Generic.IReadOnlyList<Meziantou.Framework.TextDiffHierarchyEntry>? children = null) { }
    }

    public enum TextDiffHierarchyOperation
    {
        Equal = 0,
        Insert = 1,
        Delete = 2,
        Replace = 3
    }

    public sealed class TextDiffHierarchyResult
    {
        public System.Collections.Generic.IReadOnlyList<Meziantou.Framework.TextDiffHierarchyEntry> Entries { get => throw null; }
        public bool HasDifferences { get => throw null; }
    }

    public enum TextDiffOperation
    {
        Equal = 0,
        Insert = 1,
        Delete = 2
    }

    public sealed class TextDiffOptions
    {
        public Meziantou.Framework.TextDiffAlgorithm Algorithm { get => throw null; set { } }
        public Meziantou.Framework.TextChunker Chunker { get => throw null; set { } }
        public bool IgnoreCase { get => throw null; set { } }
        public bool IgnoreWhitespace { get => throw null; set { } }
        public bool IgnoreEndOfLine { get => throw null; set { } }
    }

    public sealed class TextDiffResult
    {
        public System.Collections.Generic.IReadOnlyList<Meziantou.Framework.TextDiffEntry> Entries { get => throw null; }
        public bool HasDifferences { get => throw null; }
        public override string ToString() => throw null;
    }
}
