// <auto-generated/>
#nullable enable

namespace Meziantou.AspNetCore.Components
{
    public class AnchorNavigation : Microsoft.AspNetCore.Components.ComponentBase, System.IAsyncDisposable
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        protected override void OnInitialized() { }
        protected override System.Threading.Tasks.Task OnAfterRenderAsync(bool firstRender) => throw null;
        public System.Threading.Tasks.ValueTask DisposeAsync() => throw null;
    }

    public sealed class ClipboardService
    {
        public ClipboardService(Microsoft.JSInterop.IJSRuntime jsRuntime) { }
        public System.Threading.Tasks.ValueTask<string> ReadTextAsync(System.Threading.CancellationToken cancellationToken = null) => throw null;
        public System.Threading.Tasks.ValueTask WriteTextAsync(string text, System.Threading.CancellationToken cancellationToken = null) => throw null;
    }

    public static class ClipboardServiceExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddClipboard(this Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection) => throw null;
    }

    public class DataGrid<TRowData> : Microsoft.AspNetCore.Components.ComponentBase
    {
        public System.Collections.Generic.Dictionary<string, object>? TableAttributes { get => throw null; set { } }
        public System.Collections.Generic.IEnumerable<T0>? Items { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? ChildContent { get => throw null; set { } }
        public System.Func<T0, int, string?>? RowClass { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder? __builder) { }
        protected override void OnAfterRender(bool firstRender) { }
    }

    public class DataGridColumn<TRowData> : Microsoft.AspNetCore.Components.ComponentBase
    {
        public global::Meziantou.AspNetCore.Components.DataGrid<T0>? OwnerGrid { get => throw null; set { } }
        public string? Title { get => throw null; set { } }
        public System.Linq.Expressions.Expression<System.Func<T0, object>>? Expression { get => throw null; set { } }
        public string? Format { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment<T0>? ChildContent { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder? __builder) { }
        protected override void OnInitialized() { }
        protected override void OnParametersSet() { }
    }

    public class GenericForm<TModel> : Microsoft.AspNetCore.Components.ComponentBase
    {
        public T0 Model { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.EventCallback<T0> ModelChanged { get => throw null; set { } }
        public bool EnableFieldValidation { get => throw null; set { } }
        public string? EditorClass { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment<global::Meziantou.AspNetCore.Components.GenericFormField<T0>>? FieldTemplate { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder? __builder) { }
        protected override void OnParametersSet() { }
    }

    public sealed class GenericFormField<TModel>
    {
        public System.Reflection.PropertyInfo Property { get => throw null; }
        public string EditorId { get => throw null; }
        public T0 Owner { get => throw null; }
        public string DisplayName { get => throw null; }
        public int DisplayOrder { get => throw null; }
        public string? Description { get => throw null; }
        public string? Prompt { get => throw null; }
        public System.Type PropertyType { get => throw null; }
        public object? Value { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment EditorTemplate { get => throw null; }
        public Microsoft.AspNetCore.Components.RenderFragment? FieldValidationTemplate { get => throw null; }
        public event System.EventHandler? ValueChanged;
    }

    public class InfiniteScrolling<T> : Microsoft.AspNetCore.Components.ComponentBase, System.IAsyncDisposable
    {
        public global::Meziantou.AspNetCore.Components.InfiniteScrollingItemsProviderRequestDelegate<T0>? ItemsProvider { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment<T0>? ItemTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? LoadingTemplate { get => throw null; set { } }
        public string LastItemIndicatorElement { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) { }
        public System.Threading.Tasks.Task LoadMoreItems() => throw null;
        public System.Threading.Tasks.Task RefreshDataAsync() => throw null;
        protected override void OnParametersSet() { }
        protected override System.Threading.Tasks.Task OnAfterRenderAsync(bool firstRender) => throw null;
        public System.Threading.Tasks.ValueTask DisposeAsync() => throw null;
    }

    public sealed class InfiniteScrollingItemsProviderRequest
    {
        public int StartIndex { get => throw null; }
        public System.Threading.CancellationToken CancellationToken { get => throw null; }
        public InfiniteScrollingItemsProviderRequest(int startIndex, System.Threading.CancellationToken cancellationToken) { }
    }

    public delegate System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<T0>> InfiniteScrollingItemsProviderRequestDelegate<T>(global::Meziantou.AspNetCore.Components.InfiniteScrollingItemsProviderRequest context);

    public class InputDateTime<TValue> : Microsoft.AspNetCore.Components.Forms.InputDate<T0>
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) { }
        protected override string FormatValueAsString(T0 value) => throw null;
        protected override bool TryParseValueFromString(string? value, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 result, [System.Diagnostics.CodeAnalysis.NotNullWhen(false)] out string? validationErrorMessage) => throw null;
    }

    public sealed class InputEnumSelect<TEnum> : Microsoft.AspNetCore.Components.Forms.InputBase<T0>
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) { }
        protected override bool TryParseValueFromString(string? value, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 result, [System.Diagnostics.CodeAnalysis.NotNullWhen(false)] out string? validationErrorMessage) => throw null;
    }

    public class InputGuid<TValue> : Microsoft.AspNetCore.Components.Forms.InputBase<T0>
    {
        public string ParsingErrorMessage { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.ElementReference? Element { get => throw null; protected set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) { }
        protected override string FormatValueAsString(T0 value) => throw null;
        protected override bool TryParseValueFromString(string? value, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 result, [System.Diagnostics.CodeAnalysis.NotNullWhen(false)] out string? validationErrorMessage) => throw null;
    }

    public class InputUrl<TValue> : Microsoft.AspNetCore.Components.Forms.InputBase<T0>
    {
        public string ParsingErrorMessage { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.ElementReference? Element { get => throw null; protected set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) { }
        protected override string FormatValueAsString(T0 value) => throw null;
        protected override bool TryParseValueFromString(string? value, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out T0 result, [System.Diagnostics.CodeAnalysis.NotNullWhen(false)] out string? validationErrorMessage) => throw null;
    }

    public class LoadingIndicator : Microsoft.AspNetCore.Components.ComponentBase
    {
        public bool IsLoading { get => throw null; set { } }
        public string LoadingText { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? LoadingTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? ChildContent { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder? __builder) { }
    }

    public static class NavigationManagerExtensions
    {
        public static string? GetQueryStringParameterValue(this Microsoft.AspNetCore.Components.NavigationManager navigationManager, string parameterName) => throw null;
        public static System.Collections.Generic.IReadOnlyList<string> GetQueryStringParameterValues(this Microsoft.AspNetCore.Components.NavigationManager navigationManager, string parameterName) => throw null;
        public static void UpdateUrlUsingParameters(this Microsoft.AspNetCore.Components.NavigationManager navigationManager, Microsoft.AspNetCore.Components.IComponent component, bool replaceHistory = false) { }
    }

    [System.AttributeUsage]
    [System.Obsolete("Use SupplyParameterFromQueryAttribute instead")]
    public sealed class QueryStringParameterAttribute : System.Attribute
    {
        public string? Name { get => throw null; }
        public QueryStringParameterAttribute(string name) { }
    }

    public sealed class QueryStringService
    {
        public QueryStringService(Microsoft.AspNetCore.Components.NavigationManager navigationManager, Microsoft.JSInterop.IJSRuntime jsRuntime) { }
        public void SetParametersFromQueryString<T>(TMethod0 component) where T : Microsoft.AspNetCore.Components.IComponent { }
        public System.Threading.Tasks.ValueTask UpdateQueryString<T>(TMethod0 component, bool reloadPage = true, System.Threading.CancellationToken cancellationToken = null) where T : Microsoft.AspNetCore.Components.IComponent => throw null;
    }

    public static class QueryStringServiceExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddQueryStringParameters(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) => throw null;
    }

    public class Repeater<T> : Microsoft.AspNetCore.Components.ComponentBase
    {
        public System.Collections.Generic.IEnumerable<T0>? Items { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? LoadingTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment<Microsoft.AspNetCore.Components.RenderFragment> RepeaterContainerTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment<T0>? ItemTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? ItemSeparatorTemplate { get => throw null; set { } }
        public Microsoft.AspNetCore.Components.RenderFragment? EmptyTemplate { get => throw null; set { } }
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder? __builder) { }
        protected override void OnParametersSet() { }
    }

    public sealed class TimeZoneService : System.IAsyncDisposable
    {
        public TimeZoneService(Microsoft.JSInterop.IJSRuntime jsRuntime) { }
        public System.Threading.Tasks.ValueTask<System.TimeSpan> GetOffsetAsync() => throw null;
        public System.Threading.Tasks.ValueTask<System.DateTimeOffset> GetLocalDateTimeAsync(System.DateTimeOffset dateTime) => throw null;
        public System.Threading.Tasks.ValueTask<System.DateTimeOffset> GetUtcDateTimeAsync(System.DateTime dateTime) => throw null;
        public System.Threading.Tasks.ValueTask DisposeAsync() => throw null;
    }

    public static class TimeZoneServiceExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddTimeZoneServices(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) => throw null;
    }

    public class _Imports
    {
        protected void Execute() { }
    }
}
