// <auto-generated/>
// Target Frameworks: net10.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework
{
    public interface ILocalizationProvider
    {
        string GetString(string name, System.Globalization.CultureInfo? culture);
    }

    public static class LocalizationProvider
    {
        public static Meziantou.Framework.ILocalizationProvider Current { get => throw null; set { } }
    }

    public readonly struct RelativeDate : System.IComparable, System.IComparable<Meziantou.Framework.RelativeDate>, System.IEquatable<Meziantou.Framework.RelativeDate>, System.IFormattable
    {
        public RelativeDate(System.DateTime dateTime, System.TimeProvider? timeProvider) { }
        public RelativeDate(System.DateTime dateTime) { }
        public static Meziantou.Framework.RelativeDate Get(System.DateTime dateTime) => throw null;
        public static Meziantou.Framework.RelativeDate Get(System.DateTimeOffset dateTime) => throw null;
        public static Meziantou.Framework.RelativeDate Get(System.DateTime dateTime, System.TimeProvider? timeProvider) => throw null;
        public static Meziantou.Framework.RelativeDate Get(System.DateTimeOffset dateTime, System.TimeProvider? timeProvider) => throw null;
        public override string ToString() => throw null;
        public string ToString(string? format, System.IFormatProvider? formatProvider) => throw null;
        int System.IComparable.CompareTo(object? obj) => throw null;
        public int CompareTo(Meziantou.Framework.RelativeDate other) => throw null;
        public override bool Equals(object? obj) => throw null;
        public bool Equals(Meziantou.Framework.RelativeDate other) => throw null;
        public override int GetHashCode() => throw null;
        public static bool operator ==(Meziantou.Framework.RelativeDate date1, Meziantou.Framework.RelativeDate date2) => throw null;
        public static bool operator !=(Meziantou.Framework.RelativeDate date1, Meziantou.Framework.RelativeDate date2) => throw null;
        public static bool operator <(Meziantou.Framework.RelativeDate left, Meziantou.Framework.RelativeDate right) => throw null;
        public static bool operator <=(Meziantou.Framework.RelativeDate left, Meziantou.Framework.RelativeDate right) => throw null;
        public static bool operator >(Meziantou.Framework.RelativeDate left, Meziantou.Framework.RelativeDate right) => throw null;
        public static bool operator >=(Meziantou.Framework.RelativeDate left, Meziantou.Framework.RelativeDate right) => throw null;
    }
}
