// <auto-generated/>
// Target Frameworks: net10.0, net11.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework.Win32
{
    public static class RecentDocuments
    {
        [System.Runtime.Versioning.SupportedOSPlatform("windows5.1.2600")]
        public static void AddToRecentDocuments(string path) { }
        [System.Runtime.Versioning.SupportedOSPlatform("windows5.1.2600")]
        public static void ClearRecentDocuments() { }
    }
}
