// <auto-generated/>
// Target Frameworks: net10.0, net11.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework
{
    [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("ObjectMethodExecutor performs reflection on arbitrary types.")]
    public sealed class ObjectMethodExecutor
    {
        public bool IsMethodAsync { get => throw null; }
        public static Meziantou.Framework.ObjectMethodExecutor Create(System.Reflection.MethodInfo methodInfo) => throw null;
        public static Meziantou.Framework.ObjectMethodExecutor Create(System.Reflection.MethodInfo methodInfo, object[]? parameterDefaultValues) => throw null;
        public object? Execute(object? target, object?[]? parameters) => throw null;
        public Meziantou.Framework.ObjectMethodExecutorAwaitable ExecuteAsync(object? target, object?[]? parameters) => throw null;
    }

    public readonly struct ObjectMethodExecutorAwaitable
    {
        public Awaiter GetAwaiter() => throw null;
        public readonly struct Awaiter : System.Runtime.CompilerServices.ICriticalNotifyCompletion, System.Runtime.CompilerServices.INotifyCompletion
        {
            public bool IsCompleted { get => throw null; }
            public Awaiter(object customAwaiter, System.Func<object, bool> isCompletedMethod, System.Func<object, object?> getResultMethod, System.Action<object, System.Action> onCompletedMethod, System.Action<object, System.Action> unsafeOnCompletedMethod) { }
            public object? GetResult() => throw null;
            public void OnCompleted(System.Action continuation) { }
            public void UnsafeOnCompleted(System.Action continuation) { }
        }
    }
}
