// <auto-generated/>
// Target Frameworks: net10.0, net11.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework.Yamlish
{
    public abstract class YamlishAttribute : System.Attribute
    {
    }

    public abstract class YamlishConverter<T> : Meziantou.Framework.Yamlish.YamlishConverter
    {
        public sealed override bool CanConvert(System.Type typeToConvert) => throw null;
        public abstract T Read(Meziantou.Framework.Yamlish.YamlishNode node, Meziantou.Framework.Yamlish.YamlishSerializerOptions options);
        public abstract Meziantou.Framework.Yamlish.YamlishNode Write(T value, Meziantou.Framework.Yamlish.YamlishSerializerOptions options);
        public sealed override object? Read(Meziantou.Framework.Yamlish.YamlishNode node, System.Type typeToConvert, Meziantou.Framework.Yamlish.YamlishSerializerOptions options) => throw null;
        public sealed override Meziantou.Framework.Yamlish.YamlishNode Write(object value, System.Type typeToConvert, Meziantou.Framework.Yamlish.YamlishSerializerOptions options) => throw null;
    }

    public abstract class YamlishConverterFactory : Meziantou.Framework.Yamlish.YamlishConverter
    {
        public abstract Meziantou.Framework.Yamlish.YamlishConverter? CreateConverter(System.Type typeToConvert, Meziantou.Framework.Yamlish.YamlishSerializerOptions options);
        public sealed override object? Read(Meziantou.Framework.Yamlish.YamlishNode node, System.Type typeToConvert, Meziantou.Framework.Yamlish.YamlishSerializerOptions options) => throw null;
        public sealed override Meziantou.Framework.Yamlish.YamlishNode Write(object value, System.Type typeToConvert, Meziantou.Framework.Yamlish.YamlishSerializerOptions options) => throw null;
    }

    [System.AttributeUsage(System.AttributeTargets.Interface | System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public sealed class YamlishDerivedTypeAttribute : Meziantou.Framework.Yamlish.YamlishAttribute
    {
        public System.Type DerivedType { get => throw null; }
        public string TypeDiscriminator { get => throw null; }
        public YamlishDerivedTypeAttribute(System.Type derivedType) { }
        public YamlishDerivedTypeAttribute(System.Type derivedType, string typeDiscriminator) { }
        public YamlishDerivedTypeAttribute(System.Type derivedType, int typeDiscriminator) { }
    }

    public sealed class YamlishDocument
    {
        public Meziantou.Framework.Yamlish.YamlishNode Root { get => throw null; }
        public YamlishDocument(Meziantou.Framework.Yamlish.YamlishNode root) { }
        public static Meziantou.Framework.Yamlish.YamlishDocument Parse(string content) => throw null;
        public static Meziantou.Framework.Yamlish.YamlishDocument Parse(System.IO.TextReader reader) => throw null;
        public void WriteTo(System.IO.TextWriter writer) { }
        public override string ToString() => throw null;
    }

    [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property)]
    public sealed class YamlishIgnoreAttribute : Meziantou.Framework.Yamlish.YamlishAttribute
    {
        public Meziantou.Framework.Yamlish.YamlishIgnoreCondition Condition { get => throw null; set { } }
    }

    public enum YamlishIgnoreCondition
    {
        Never = 0,
        Always = 1,
        WhenWritingDefault = 2,
        WhenWritingNull = 3
    }

    public sealed class YamlishMapping : Meziantou.Framework.Yamlish.YamlishNode, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Meziantou.Framework.Yamlish.YamlishNode>>, System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<string, Meziantou.Framework.Yamlish.YamlishNode>>, System.Collections.Generic.IReadOnlyDictionary<string, Meziantou.Framework.Yamlish.YamlishNode>, System.Collections.IEnumerable
    {
        public Meziantou.Framework.Yamlish.YamlishNodeKind Kind { get => throw null; }
        public int Count { get => throw null; }
        public System.Collections.Generic.IEnumerable<string> Keys { get => throw null; }
        public System.Collections.Generic.IEnumerable<Meziantou.Framework.Yamlish.YamlishNode> Values { get => throw null; }
        public Meziantou.Framework.Yamlish.YamlishNode this[string key] { get => throw null; }
        public YamlishMapping(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Meziantou.Framework.Yamlish.YamlishNode>> entries) { }
        public void Add(string key, Meziantou.Framework.Yamlish.YamlishNode value) { }
        public bool ContainsKey(string key) => throw null;
        public bool TryGetValue(string key, out Meziantou.Framework.Yamlish.YamlishNode value) => throw null;
        public System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<string, Meziantou.Framework.Yamlish.YamlishNode>> GetEnumerator() => throw null;
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null;
    }

    public abstract class YamlishNamingPolicy
    {
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy CamelCase { get => throw null; }
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy SnakeCaseLower { get => throw null; }
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy SnakeCaseUpper { get => throw null; }
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy KebabCaseLower { get => throw null; }
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy KebabCaseUpper { get => throw null; }
        public static Meziantou.Framework.Yamlish.YamlishNamingPolicy PascalCase { get => throw null; }
        public abstract string ConvertName(string name);
    }

    public abstract class YamlishNode
    {
        public Meziantou.Framework.Yamlish.YamlishNodeKind Kind { get; }
        public override string ToString() => throw null;
    }

    public enum YamlishNodeKind
    {
        Scalar = 0,
        Mapping = 1,
        Sequence = 2
    }

    public enum YamlishObjectCreationHandling
    {
        Replace = 0,
        Populate = 1
    }

    [System.AttributeUsage(System.AttributeTargets.Interface | System.AttributeTargets.Struct | System.AttributeTargets.Class, Inherited = false)]
    public sealed class YamlishPolymorphicAttribute : Meziantou.Framework.Yamlish.YamlishAttribute
    {
        public string TypeDiscriminatorPropertyName { get => throw null; set { } }
    }

    [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property)]
    public sealed class YamlishPropertyNameAttribute : Meziantou.Framework.Yamlish.YamlishAttribute
    {
        public string Name { get => throw null; }
        public YamlishPropertyNameAttribute(string name) { }
    }

    public sealed class YamlishScalar : Meziantou.Framework.Yamlish.YamlishNode
    {
        public Meziantou.Framework.Yamlish.YamlishNodeKind Kind { get => throw null; }
        public string Value { get => throw null; }
        public YamlishScalar(string value) { }
    }

    public sealed class YamlishSequence : Meziantou.Framework.Yamlish.YamlishNode, System.Collections.Generic.IEnumerable<Meziantou.Framework.Yamlish.YamlishNode>, System.Collections.Generic.IReadOnlyCollection<Meziantou.Framework.Yamlish.YamlishNode>, System.Collections.Generic.IReadOnlyList<Meziantou.Framework.Yamlish.YamlishNode>, System.Collections.IEnumerable
    {
        public Meziantou.Framework.Yamlish.YamlishNodeKind Kind { get => throw null; }
        public int Count { get => throw null; }
        public Meziantou.Framework.Yamlish.YamlishNode this[int index] { get => throw null; }
        public YamlishSequence(System.Collections.Generic.IEnumerable<Meziantou.Framework.Yamlish.YamlishNode> items) { }
        public void Add(Meziantou.Framework.Yamlish.YamlishNode item) { }
        public System.Collections.Generic.IEnumerator<Meziantou.Framework.Yamlish.YamlishNode> GetEnumerator() => throw null;
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null;
    }

    public static class YamlishSerializer
    {
        public static string Serialize<T>(T value, Meziantou.Framework.Yamlish.YamlishSerializerOptions? options = null) => throw null;
        public static string Serialize(object? value, System.Type type, Meziantou.Framework.Yamlish.YamlishSerializerOptions? options = null) => throw null;
        public static T Deserialize<T>(string content, Meziantou.Framework.Yamlish.YamlishSerializerOptions? options = null) => throw null;
        public static object? Deserialize(string content, System.Type type, Meziantou.Framework.Yamlish.YamlishSerializerOptions? options = null) => throw null;
    }

    public sealed class YamlishSerializerOptions
    {
        public bool IsReadOnly { get => throw null; }
        public System.Collections.Generic.IList<Meziantou.Framework.Yamlish.YamlishConverter> Converters { get => throw null; }
        public Meziantou.Framework.Yamlish.YamlishNamingPolicy? PropertyNamingPolicy { get => throw null; set { } }
        public System.StringComparer PropertyNameComparer { get => throw null; set { } }
        public int IndentSize { get => throw null; set { } }
        public char IndentCharacter { get => throw null; set { } }
        public string NewLine { get => throw null; set { } }
        public int MaxDepth { get => throw null; set { } }
        public Meziantou.Framework.Yamlish.YamlishIgnoreCondition DefaultIgnoreCondition { get => throw null; set { } }
        public bool IncludeFields { get => throw null; set { } }
        public bool IgnoreReadOnlyFields { get => throw null; set { } }
        public bool IgnoreReadOnlyProperties { get => throw null; set { } }
        public Meziantou.Framework.Yamlish.YamlishObjectCreationHandling PreferredObjectCreationHandling { get => throw null; set { } }
        public bool AllowDuplicateProperties { get => throw null; set { } }
        public bool RespectRequiredConstructorParameters { get => throw null; set { } }
        public bool RespectNullableAnnotations { get => throw null; set { } }
        public void AddAttribute(System.Type type, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddAttribute(System.Type type, string memberName, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddAttribute(System.Reflection.PropertyInfo member, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddAttribute(System.Reflection.FieldInfo member, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddAttribute<T>(System.Linq.Expressions.Expression<System.Func<T, object>> member, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddPropertyAttribute(System.Func<System.Reflection.PropertyInfo, bool> condition, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddFieldAttribute(System.Func<System.Reflection.FieldInfo, bool> condition, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void AddTypeAttribute(System.Func<System.Type, bool> condition, Meziantou.Framework.Yamlish.YamlishAttribute attribute) { }
        public void MakeReadOnly() { }
    }
}
