// <auto-generated/>
// Target Frameworks: net10.0, net11.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework
{
    public static class AnsiTextProcessor
    {
        public static string RemoveAnsiSequences(string value) => throw null;
        public static string RemoveAnsiSequences(System.ReadOnlySpan<char> value) => throw null;
        public static bool ContainsAnsiSequences(string value) => throw null;
        public static bool ContainsAnsiSequences(System.ReadOnlySpan<char> value) => throw null;
        public static ParsedText ParseTextWithAnsiStyles(string text) => throw null;
        public sealed class AnsiColor : System.IEquatable<AnsiColor>
        {
            public AnsiColorKind Kind { get => throw null; init { } }
            public byte Red { get => throw null; init { } }
            public byte Green { get => throw null; init { } }
            public byte Blue { get => throw null; init { } }
            public byte IndexedValue { get => throw null; init { } }
            public AnsiColor(AnsiColorKind Kind, byte Red, byte Green, byte Blue, byte IndexedValue) { }
            public static AnsiColor FromIndexed(int value) => throw null;
            public static AnsiColor FromRgb(byte red, byte green, byte blue) => throw null;
            public override string ToString() => throw null;
            public static bool operator !=(AnsiColor? left, AnsiColor? right) => throw null;
            public static bool operator ==(AnsiColor? left, AnsiColor? right) => throw null;
            public override int GetHashCode() => throw null;
            public override bool Equals(object? obj) => throw null;
            public bool Equals(AnsiColor? other) => throw null;
            public void Deconstruct(out AnsiColorKind Kind, out byte Red, out byte Green, out byte Blue, out byte IndexedValue) => throw null;
        }
        public enum AnsiColorKind
        {
            Indexed = 0,
            Rgb = 1
        }
        public sealed class AnsiStyle : System.IEquatable<AnsiStyle>
        {
            public AnsiColor? Foreground { get => throw null; init { } }
            public AnsiColor? Background { get => throw null; init { } }
            public bool Bold { get => throw null; init { } }
            public bool Italic { get => throw null; init { } }
            public bool Underline { get => throw null; init { } }
            public bool Inverse { get => throw null; init { } }
            public static AnsiStyle None { get => throw null; }
            public AnsiStyle(AnsiColor? Foreground, AnsiColor? Background, bool Bold, bool Italic, bool Underline, bool Inverse) { }
            public override string ToString() => throw null;
            public static bool operator !=(AnsiStyle? left, AnsiStyle? right) => throw null;
            public static bool operator ==(AnsiStyle? left, AnsiStyle? right) => throw null;
            public override int GetHashCode() => throw null;
            public override bool Equals(object? obj) => throw null;
            public bool Equals(AnsiStyle? other) => throw null;
            public void Deconstruct(out AnsiColor? Foreground, out AnsiColor? Background, out bool Bold, out bool Italic, out bool Underline, out bool Inverse) => throw null;
        }
        public sealed class ParsedText : System.IEquatable<ParsedText>
        {
            public string Text { get => throw null; init { } }
            public System.Collections.Generic.IReadOnlyList<TextRun> Runs { get => throw null; init { } }
            public ParsedText(string Text, System.Collections.Generic.IReadOnlyList<TextRun> Runs) { }
            public override string ToString() => throw null;
            public static bool operator !=(ParsedText? left, ParsedText? right) => throw null;
            public static bool operator ==(ParsedText? left, ParsedText? right) => throw null;
            public override int GetHashCode() => throw null;
            public override bool Equals(object? obj) => throw null;
            public bool Equals(ParsedText? other) => throw null;
            public void Deconstruct(out string Text, out System.Collections.Generic.IReadOnlyList<TextRun> Runs) => throw null;
        }
        public sealed class TextRun : System.IEquatable<TextRun>
        {
            public int Start { get => throw null; init { } }
            public int End { get => throw null; init { } }
            public AnsiStyle Style { get => throw null; init { } }
            public TextRun(int Start, int End, AnsiStyle Style) { }
            public override string ToString() => throw null;
            public static bool operator !=(TextRun? left, TextRun? right) => throw null;
            public static bool operator ==(TextRun? left, TextRun? right) => throw null;
            public override int GetHashCode() => throw null;
            public override bool Equals(object? obj) => throw null;
            public bool Equals(TextRun? other) => throw null;
            public void Deconstruct(out int Start, out int End, out AnsiStyle Style) => throw null;
        }
    }
}
