// <auto-generated/>
// Target Frameworks: net10.0, net11.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework.Http
{
    public sealed class HstsClientHandler : System.Net.Http.DelegatingHandler
    {
        public HstsClientHandler(System.Net.Http.HttpMessageHandler innerHandler) { }
        public HstsClientHandler(System.Net.Http.HttpMessageHandler innerHandler, Meziantou.Framework.Http.HstsDomainPolicyCollection configuration) { }
        protected override System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) => throw null;
    }

    public sealed class HstsDomainPolicy
    {
        public string Host { get => throw null; }
        public System.DateTimeOffset ExpiresAt { get => throw null; }
        public bool IncludeSubdomains { get => throw null; }
        public override string ToString() => throw null;
    }

    public sealed class HstsDomainPolicyCollection : System.Collections.Generic.IEnumerable<Meziantou.Framework.Http.HstsDomainPolicy>, System.Collections.IEnumerable
    {
        public static Meziantou.Framework.Http.HstsDomainPolicyCollection Default { get => throw null; }
        public HstsDomainPolicyCollection(bool includePreloadDomains = true) { }
        public HstsDomainPolicyCollection(System.TimeProvider? timeProvider, bool includePreloadDomains = true) { }
        public void Add(string host, System.TimeSpan maxAge, bool includeSubdomains) { }
        public void Add(string host, System.DateTimeOffset expiresAt, bool includeSubdomains) { }
        public bool MustUpgradeRequest(string host) => throw null;
        public bool MustUpgradeRequest(System.ReadOnlySpan<char> host) => throw null;
        public System.Collections.Generic.IEnumerator<Meziantou.Framework.Http.HstsDomainPolicy> GetEnumerator() => throw null;
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null;
    }
}
