// <auto-generated/>
// Target Frameworks: net10.0, net11.0
#nullable enable

namespace Meziantou.Framework.Imaging
{
    public abstract class AutoCropAnalysis
    {
        public bool Success { get => throw null; }
        public Meziantou.Framework.Imaging.Size CanvasSize { get => throw null; }
        public Meziantou.Framework.Imaging.Rectangle Bounds { get => throw null; }
        public Meziantou.Framework.Imaging.Rgba64 BackgroundColor { get => throw null; }
        public double WeightX { get => throw null; }
        public double WeightY { get => throw null; }
    }

    public sealed class AutoCropAnalysis<TPixel> : Meziantou.Framework.Imaging.AutoCropAnalysis where TPixel : struct
    {
        public TPixel BackgroundColor { get => throw null; }
    }

    public sealed class AutoCropOptions
    {
        public static Meziantou.Framework.Imaging.AutoCropOptions Default { get => throw null; }
        public int PaddingX { get => throw null; init { } }
        public int PaddingY { get => throw null; init { } }
        public int ColorThreshold { get => throw null; init { } }
        public double? BucketThreshold { get => throw null; init { } }
        public Meziantou.Framework.Imaging.AutoCropPaddingMode PaddingMode { get => throw null; init { } }
        public bool AnalyzeWeights { get => throw null; init { } }
    }

    public enum AutoCropPaddingMode
    {
        Expand = 0,
        Contain = 1,
    }

    public struct Bgra32 : System.IEquatable<Meziantou.Framework.Imaging.Bgra32>
    {
        public byte B;
        public byte G;
        public byte R;
        public byte A;
        public Bgra32(byte r, byte g, byte b, byte a = 255) { }
        public readonly bool Equals(Meziantou.Framework.Imaging.Bgra32 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Bgra32 left, Meziantou.Framework.Imaging.Bgra32 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Bgra32 left, Meziantou.Framework.Imaging.Bgra32 right) => throw null;
    }

    public enum ConvolutionEdgeMode
    {
        Clamp = 0,
        Mirror = 1,
        Wrap = 2,
        Zero = 3,
    }

    public sealed class ConvolutionKernel
    {
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public double this[int x, int y] { get => throw null; }
        public ConvolutionKernel(int width, int height, System.ReadOnlySpan<double> values) { }
    }

    public sealed class ConvolutionOptions
    {
        public Meziantou.Framework.Imaging.ConvolutionKernel Kernel { get => throw null; }
        public Meziantou.Framework.Imaging.ConvolutionEdgeMode EdgeMode { get => throw null; init { } }
        public bool PreserveAlpha { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ConvolutionWorkingSpace WorkingSpace { get => throw null; init { } }
        public ConvolutionOptions(Meziantou.Framework.Imaging.ConvolutionKernel kernel) { }
    }

    public enum ConvolutionWorkingSpace
    {
        Encoded = 0,
        LinearSrgb = 1,
    }

    public enum FlipMode
    {
        Horizontal = 0,
        Vertical = 1,
    }

    public readonly struct FrameDuration : System.IComparable, System.IComparable<Meziantou.Framework.Imaging.FrameDuration>, System.IEquatable<Meziantou.Framework.Imaging.FrameDuration>
    {
        public static Meziantou.Framework.Imaging.FrameDuration Zero { get => throw null; }
        public long Numerator { get => throw null; }
        public long Denominator { get => throw null; }
        public bool IsZero { get => throw null; }
        public double TotalSeconds { get => throw null; }
        public double TotalMilliseconds { get => throw null; }
        public FrameDuration(long numerator, long denominator) { }
        public static Meziantou.Framework.Imaging.FrameDuration FromMilliseconds(long milliseconds) => throw null;
        public static Meziantou.Framework.Imaging.FrameDuration FromTimeSpan(System.TimeSpan value) => throw null;
        public System.TimeSpan ToTimeSpan() => throw null;
        public bool Equals(Meziantou.Framework.Imaging.FrameDuration other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public int CompareTo(Meziantou.Framework.Imaging.FrameDuration other) => throw null;
        public int CompareTo(object? obj) => throw null;
        public override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
        public static bool operator <(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
        public static bool operator <=(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
        public static bool operator >(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
        public static bool operator >=(Meziantou.Framework.Imaging.FrameDuration left, Meziantou.Framework.Imaging.FrameDuration right) => throw null;
    }

    public struct Gray16 : System.IEquatable<Meziantou.Framework.Imaging.Gray16>
    {
        public ushort Value;
        public Gray16(ushort value) { }
        public readonly bool Equals(Meziantou.Framework.Imaging.Gray16 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Gray16 left, Meziantou.Framework.Imaging.Gray16 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Gray16 left, Meziantou.Framework.Imaging.Gray16 right) => throw null;
    }

    public struct Gray8 : System.IEquatable<Meziantou.Framework.Imaging.Gray8>
    {
        public byte Value;
        public Gray8(byte value) { }
        public readonly bool Equals(Meziantou.Framework.Imaging.Gray8 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Gray8 left, Meziantou.Framework.Imaging.Gray8 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Gray8 left, Meziantou.Framework.Imaging.Gray8 right) => throw null;
    }

    public sealed class IccColorTransform
    {
        public int SourceChannelCount { get => throw null; }
        public int DestinationChannelCount { get => throw null; }
        public static Meziantou.Framework.Imaging.IccColorTransform Create(Meziantou.Framework.Imaging.Metadata.IccProfile source, Meziantou.Framework.Imaging.Metadata.IccProfile destination, Meziantou.Framework.Imaging.IccColorTransformOptions? options = null) => throw null;
        public void Convert(System.ReadOnlySpan<byte> source, System.Span<byte> destination) { }
        public void Convert(System.ReadOnlySpan<ushort> source, System.Span<ushort> destination) { }
        public void Convert(System.ReadOnlySpan<float> source, System.Span<float> destination) { }
    }

    public sealed class IccColorTransformOptions
    {
        public static Meziantou.Framework.Imaging.IccColorTransformOptions Default { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.IccRenderingIntent Intent { get => throw null; init { } }
        public bool BlackPointCompensation { get => throw null; init { } }
    }

    public abstract class Image : System.IDisposable
    {
        public const int FormatDetectionPrefixLength = 18;
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public abstract Meziantou.Framework.Imaging.PixelFormat PixelFormat { get; }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.ImageMetadata Metadata { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.AnimationMetadata? Animation { get => throw null; set { } }
        public abstract Meziantou.Framework.Imaging.ImageFrameCollection Frames { get; }
        public abstract Meziantou.Framework.Imaging.ImageFrame? PosterFrame { get; }
        public bool IsAnimated { get => throw null; }
        public abstract Meziantou.Framework.Imaging.Image Clone();
        public Meziantou.Framework.Imaging.Image<TPixel> CloneAs<TPixel>(Meziantou.Framework.Imaging.PixelConversionOptions? options = null) where TPixel : struct => throw null;
        public abstract Meziantou.Framework.Imaging.Image CloneFrame(int index);
        public abstract Meziantou.Framework.Imaging.Image ClonePosterFrame();
        public abstract Meziantou.Framework.Imaging.ImageFrame AppendFrame();
        public abstract Meziantou.Framework.Imaging.ImageFrame AppendFrame(Meziantou.Framework.Imaging.ImageFrame source);
        public abstract Meziantou.Framework.Imaging.ImageFrame InsertFrame(int index, Meziantou.Framework.Imaging.ImageFrame source);
        public void RemoveFrame(int index) { }
        public void MoveFrame(int sourceIndex, int destinationIndex) { }
        public abstract Meziantou.Framework.Imaging.ImageFrame SetPosterFrame(Meziantou.Framework.Imaging.ImageFrame source);
        public bool RemovePosterFrame() => throw null;
        public void Save(string path, Meziantou.Framework.Imaging.Formats.ImageEncoder? encoder = null) { }
        public void Save(System.IO.Stream stream, Meziantou.Framework.Imaging.Formats.ImageEncoder encoder) { }
        public System.Threading.Tasks.Task SaveAsync(string path, Meziantou.Framework.Imaging.Formats.ImageEncoder? encoder = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public System.Threading.Tasks.Task SaveAsync(System.IO.Stream stream, Meziantou.Framework.Imaging.Formats.ImageEncoder encoder, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public void Dispose() { }
        public static Meziantou.Framework.Imaging.ImageFormat DetectFormat(System.ReadOnlySpan<byte> prefix) => throw null;
        public static Meziantou.Framework.Imaging.ImageInfo Identify(string path, Meziantou.Framework.Imaging.ImageIdentifyOptions? options = null) => throw null;
        public static Meziantou.Framework.Imaging.ImageInfo Identify(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageIdentifyOptions? options = null) => throw null;
        public static Meziantou.Framework.Imaging.ImageInfo Identify(System.ReadOnlySpan<byte> data, Meziantou.Framework.Imaging.ImageIdentifyOptions? options = null) => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.ImageInfo> IdentifyAsync(string path, Meziantou.Framework.Imaging.ImageIdentifyOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.ImageInfo> IdentifyAsync(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageIdentifyOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static Meziantou.Framework.Imaging.Image Load(string path, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) => throw null;
        public static Meziantou.Framework.Imaging.Image Load(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) => throw null;
        public static Meziantou.Framework.Imaging.Image Load(System.ReadOnlySpan<byte> data, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) => throw null;
        public static Meziantou.Framework.Imaging.Image<TPixel> Load<TPixel>(string path, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.Image<TPixel> Load<TPixel>(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.Image<TPixel> Load<TPixel>(System.ReadOnlySpan<byte> data, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) where TPixel : struct => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.Image> LoadAsync(string path, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.Image> LoadAsync(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.Image<TPixel>> LoadAsync<TPixel>(string path, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null, System.Threading.CancellationToken cancellationToken = null) where TPixel : struct => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.Image<TPixel>> LoadAsync<TPixel>(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageDecodeOptions? options = null, System.Threading.CancellationToken cancellationToken = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.Image<TPixel> ImportPixelData<TPixel>(System.ReadOnlySpan<TPixel> source, int width, int height, int strideInPixels = 0, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.Image<TPixel> ImportPixelBytes<TPixel>(System.ReadOnlySpan<byte> source, int width, int height, int strideInBytes = 0, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.ImageReader<TPixel> OpenReader<TPixel>(string path, Meziantou.Framework.Imaging.ImageReaderOptions? options = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.ImageReader<TPixel> OpenReader<TPixel>(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageReaderOptions? options = null) where TPixel : struct => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.ImageReader<TPixel>> OpenReaderAsync<TPixel>(string path, Meziantou.Framework.Imaging.ImageReaderOptions? options = null, System.Threading.CancellationToken cancellationToken = null) where TPixel : struct => throw null;
        public static System.Threading.Tasks.Task<Meziantou.Framework.Imaging.ImageReader<TPixel>> OpenReaderAsync<TPixel>(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageReaderOptions? options = null, System.Threading.CancellationToken cancellationToken = null) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.ImageWriter<TPixel> CreateWriter<TPixel>(string path, Meziantou.Framework.Imaging.ImageWriterOptions options) where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.ImageWriter<TPixel> CreateWriter<TPixel>(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageWriterOptions options) where TPixel : struct => throw null;
    }

    public sealed class ImageCollection : System.IDisposable
    {
        public Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.ImageCollectionKind Kind { get => throw null; }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; }
        public int Count { get => throw null; }
        public System.Collections.Generic.IReadOnlyList<Meziantou.Framework.Imaging.ImageCollectionEntry> Entries { get => throw null; }
        public Meziantou.Framework.Imaging.ImageCollectionEntry this[int index] { get => throw null; }
        public static Meziantou.Framework.Imaging.ImageCollection Create(Meziantou.Framework.Imaging.ImageCollectionKind kind, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) => throw null;
        public static Meziantou.Framework.Imaging.ImageCollection Load(string path, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) => throw null;
        public static Meziantou.Framework.Imaging.ImageCollection Load(System.IO.Stream stream, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) => throw null;
        public static Meziantou.Framework.Imaging.ImageCollection Load(System.ReadOnlySpan<byte> data, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) => throw null;
        public Meziantou.Framework.Imaging.ImageCollectionEntry SelectBySize(Meziantou.Framework.Imaging.Size size) => throw null;
        public Meziantou.Framework.Imaging.ImageCollectionEntry Add(Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.Point? hotspot = null) => throw null;
        public Meziantou.Framework.Imaging.ImageCollectionEntry Insert(int index, Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.Point? hotspot = null) => throw null;
        public void RemoveAt(int index) { }
        public void Move(int sourceIndex, int destinationIndex) { }
        public void Save(string path, Meziantou.Framework.Imaging.Formats.ImageEncoder? encoder = null) { }
        public void Save(System.IO.Stream stream, Meziantou.Framework.Imaging.Formats.ImageEncoder encoder) { }
        public void Dispose() { }
    }

    public sealed class ImageCollectionEntry
    {
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public Meziantou.Framework.Imaging.PixelFormat PixelFormat { get => throw null; }
        public Meziantou.Framework.Imaging.ImageColorModel ColorModel { get => throw null; }
        public int BitsPerComponent { get => throw null; }
        public bool MayHaveTransparency { get => throw null; }
        public Meziantou.Framework.Imaging.ImageFormat PayloadFormat { get => throw null; }
        public Meziantou.Framework.Imaging.Point? Hotspot { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.ImageMetadata Metadata { get => throw null; }
        public Meziantou.Framework.Imaging.Image Decode(Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) => throw null;
        public Meziantou.Framework.Imaging.Image<TPixel> Decode<TPixel>(Meziantou.Framework.Imaging.ImageDecodeOptions? options = null) where TPixel : struct => throw null;
    }

    public enum ImageCollectionKind
    {
        Unknown = 0,
        Pages = 1,
        Representations = 2,
    }

    public enum ImageColorModel
    {
        Unknown = 0,
        Grayscale = 1,
        GrayscaleAlpha = 2,
        Rgb = 3,
        Rgba = 4,
        Indexed = 5,
        YCbCr = 6,
    }

    public sealed class ImageConfiguration
    {
        public static Meziantou.Framework.Imaging.ImageConfiguration Default { get => throw null; }
        public Meziantou.Framework.Imaging.ImageResourceLimits Limits { get => throw null; init { } }
        public int MaxDegreeOfParallelism { get => throw null; init { } }
    }

    public sealed class ImageDecodeOptions
    {
        public static Meziantou.Framework.Imaging.ImageDecodeOptions Default { get => throw null; }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; init { } }
        public int? FrameLimit { get => throw null; init { } }
        public Meziantou.Framework.Imaging.PixelConversionOptions Conversion { get => throw null; init { } }
    }

    public class ImageException : System.Exception
    {
        public ImageException(string? message) { }
        public ImageException(string? message, System.Exception? innerException) { }
    }

    public enum ImageFormat
    {
        Unknown = 0,
        Png = 1,
        Gif = 2,
        Jpeg = 3,
        WebP = 4,
        Qoi = 5,
        Bmp = 6,
        Tga = 7,
        Pnm = 8,
        Tiff = 9,
        Ico = 10,
        Cur = 11,
    }

    public abstract class ImageFrame
    {
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public abstract Meziantou.Framework.Imaging.PixelFormat PixelFormat { get; }
        public Meziantou.Framework.Imaging.Metadata.FrameMetadata Metadata { get => throw null; }
        public void ProcessPixelBytes(Meziantou.Framework.Imaging.PixelBytesAction action) { }
        public void ProcessPixelBytes<TState>(TState state, Meziantou.Framework.Imaging.PixelBytesAction<TState> action) where TState : allows ref struct { }
        public void CopyPixelBytesTo(System.Span<byte> destination, int strideInBytes = 0) { }
    }

    public abstract class ImageFrameCollection : System.Collections.Generic.IEnumerable<Meziantou.Framework.Imaging.ImageFrame>, System.Collections.Generic.IReadOnlyCollection<Meziantou.Framework.Imaging.ImageFrame>, System.Collections.Generic.IReadOnlyList<Meziantou.Framework.Imaging.ImageFrame>, System.Collections.IEnumerable
    {
        public abstract int Count { get; }
        public abstract Meziantou.Framework.Imaging.ImageFrame this[int index] { get; }
        public int IndexOf(Meziantou.Framework.Imaging.ImageFrame frame) => throw null;
        public bool Contains(Meziantou.Framework.Imaging.ImageFrame frame) => throw null;
        public Enumerator GetEnumerator() => throw null;
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null;
        public struct Enumerator : System.Collections.Generic.IEnumerator<Meziantou.Framework.Imaging.ImageFrame>, System.Collections.IEnumerator, System.IDisposable
        {
            public readonly Meziantou.Framework.Imaging.ImageFrame Current { get => throw null; }
            public bool MoveNext() => throw null;
            public void Reset() { }
            public readonly void Dispose() { }
        }
    }

    public sealed class ImageFrameCollection<TPixel> : Meziantou.Framework.Imaging.ImageFrameCollection, System.Collections.Generic.IEnumerable<Meziantou.Framework.Imaging.ImageFrame<TPixel>>, System.Collections.Generic.IReadOnlyCollection<Meziantou.Framework.Imaging.ImageFrame<TPixel>>, System.Collections.Generic.IReadOnlyList<Meziantou.Framework.Imaging.ImageFrame<TPixel>>, System.Collections.IEnumerable where TPixel : struct
    {
        public override int Count { get => throw null; }
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel> this[int index] { get => throw null; }
        public Enumerator<TPixel> GetEnumerator() => throw null;
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null;
        public struct Enumerator<TPixel> : System.Collections.Generic.IEnumerator<Meziantou.Framework.Imaging.ImageFrame<TPixel>>, System.Collections.IEnumerator, System.IDisposable where TPixel : struct
        {
            public readonly Meziantou.Framework.Imaging.ImageFrame<TPixel> Current { get => throw null; }
            public bool MoveNext() => throw null;
            public void Reset() { }
            public readonly void Dispose() { }
        }
    }

    public sealed class ImageFrame<TPixel> : Meziantou.Framework.Imaging.ImageFrame where TPixel : struct
    {
        public override Meziantou.Framework.Imaging.PixelFormat PixelFormat { get => throw null; }
        public TPixel this[int x, int y] { get => throw null; set { } }
        public void ProcessPixelRows(Meziantou.Framework.Imaging.PixelRowsAction<TPixel> action) { }
        public void ProcessPixelRows<TState>(TState state, Meziantou.Framework.Imaging.PixelRowsAction<TPixel, TState> action) where TState : allows ref struct { }
        public void CopyPixelDataTo(System.Span<TPixel> destination, int strideInPixels = 0) { }
    }

    public enum ImageIdentifyMode
    {
        Header = 0,
        FullScan = 1,
    }

    public sealed class ImageIdentifyOptions
    {
        public static Meziantou.Framework.Imaging.ImageIdentifyOptions Default { get => throw null; }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ImageIdentifyMode Mode { get => throw null; init { } }
    }

    public sealed class ImageInfo
    {
        public Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public int? CollectionEntryCount { get => throw null; }
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public Meziantou.Framework.Imaging.PixelFormat PixelFormat { get => throw null; }
        public Meziantou.Framework.Imaging.ImageColorModel ColorModel { get => throw null; }
        public int BitsPerComponent { get => throw null; }
        public int? FrameCount { get => throw null; }
        public bool? IsAnimated { get => throw null; }
        public bool? HasPosterFrame { get => throw null; }
        public bool? MayHaveTransparency { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.AnimationMetadata? Animation { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.ImageMetadata Metadata { get => throw null; }
        public Meziantou.Framework.Imaging.ImageIdentifyMode IdentifyMode { get => throw null; }
    }

    public static class ImageProcessingExtensions
    {
        public static void Crop(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.Rectangle rectangle, System.Threading.CancellationToken cancellationToken = null) { }
        public static Meziantou.Framework.Imaging.AutoCropAnalysis AnalyzeAutoCrop(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.AutoCropOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static Meziantou.Framework.Imaging.AutoCropAnalysis<TPixel> AnalyzeAutoCrop<TPixel>(this Meziantou.Framework.Imaging.Image<TPixel> image, Meziantou.Framework.Imaging.AutoCropOptions? options = null, System.Threading.CancellationToken cancellationToken = null) where TPixel : struct => throw null;
        public static bool AutoCrop(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.AutoCropOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static bool AutoCrop(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.AutoCropAnalysis analysis, Meziantou.Framework.Imaging.AutoCropOptions? options = null, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public static void Resize(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.ResizeOptions options, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Rotate(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.RotateMode mode, System.Threading.CancellationToken cancellationToken = null) { }
        public static void AutoOrient(this Meziantou.Framework.Imaging.Image image, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Flip(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.FlipMode mode, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Flip(this Meziantou.Framework.Imaging.ImageFrame frame, Meziantou.Framework.Imaging.FlipMode mode, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Grayscale(this Meziantou.Framework.Imaging.Image image, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Grayscale(this Meziantou.Framework.Imaging.ImageFrame frame, System.Threading.CancellationToken cancellationToken = null) { }
        public static void ConvertColorProfile(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.Metadata.IccProfile destinationProfile, Meziantou.Framework.Imaging.IccColorTransformOptions? options = null, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Convolve(this Meziantou.Framework.Imaging.Image image, Meziantou.Framework.Imaging.ConvolutionOptions options, System.Threading.CancellationToken cancellationToken = null) { }
        public static void Convolve(this Meziantou.Framework.Imaging.ImageFrame frame, Meziantou.Framework.Imaging.ConvolutionOptions options, System.Threading.CancellationToken cancellationToken = null) { }
    }

    public sealed class ImageReaderOptions
    {
        public static Meziantou.Framework.Imaging.ImageReaderOptions Default { get => throw null; }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; init { } }
        public int? FrameLimit { get => throw null; init { } }
        public Meziantou.Framework.Imaging.PixelConversionOptions Conversion { get => throw null; init { } }
        public bool LeaveOpen { get => throw null; init { } }
    }

    public sealed class ImageReader<TPixel> : System.IAsyncDisposable, System.IDisposable where TPixel : struct
    {
        public Meziantou.Framework.Imaging.ImageInfo Info { get => throw null; }
        public int FramesRead { get => throw null; }
        public Meziantou.Framework.Imaging.Image<TPixel>? ReadPosterFrame() => throw null;
        public System.Threading.Tasks.ValueTask<Meziantou.Framework.Imaging.Image<TPixel>?> ReadPosterFrameAsync(System.Threading.CancellationToken cancellationToken = null) => throw null;
        public Meziantou.Framework.Imaging.Image<TPixel>? ReadFrame() => throw null;
        public System.Threading.Tasks.ValueTask<Meziantou.Framework.Imaging.Image<TPixel>?> ReadFrameAsync(System.Threading.CancellationToken cancellationToken = null) => throw null;
        public bool ReadFrameInto(Meziantou.Framework.Imaging.Image<TPixel> destination) => throw null;
        public System.Threading.Tasks.ValueTask<bool> ReadFrameIntoAsync(Meziantou.Framework.Imaging.Image<TPixel> destination, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public void Dispose() { }
        public System.Threading.Tasks.ValueTask DisposeAsync() => throw null;
    }

    public class ImageResourceLimitException : Meziantou.Framework.Imaging.ImageException
    {
        public Meziantou.Framework.Imaging.ImageResourceLimitKind Kind { get => throw null; }
        public long Limit { get => throw null; }
        public long? Requested { get => throw null; }
        public ImageResourceLimitException(string? message) { }
        public ImageResourceLimitException(string? message, System.Exception? innerException) { }
        public ImageResourceLimitException(Meziantou.Framework.Imaging.ImageResourceLimitKind kind, long limit, long? requested) { }
    }

    public enum ImageResourceLimitKind
    {
        Unknown = 0,
        Width = 1,
        Height = 2,
        FramePixels = 3,
        Frames = 4,
        TotalPixels = 5,
        EncodedBytes = 6,
        MetadataBytes = 7,
        LiveAllocationBytes = 8,
    }

    public sealed class ImageResourceLimits
    {
        public const int DefaultMaxDimension = 32768;
        public const long DefaultMaxFramePixels = 100000000L;
        public const int DefaultMaxFrames = 1000;
        public const long DefaultMaxTotalPixels = 1000000000L;
        public const long DefaultMaxEncodedBytes = 268435456L;
        public const long DefaultMaxMetadataBytes = 16777216L;
        public const long DefaultMaxLiveAllocationBytes = 536870912L;
        public static Meziantou.Framework.Imaging.ImageResourceLimits Default { get => throw null; }
        public int MaxWidth { get => throw null; init { } }
        public int MaxHeight { get => throw null; init { } }
        public long MaxFramePixels { get => throw null; init { } }
        public int MaxFrames { get => throw null; init { } }
        public long MaxTotalPixels { get => throw null; init { } }
        public long MaxEncodedBytes { get => throw null; init { } }
        public long MaxMetadataBytes { get => throw null; init { } }
        public long MaxLiveAllocationBytes { get => throw null; init { } }
    }

    public sealed class ImageWriterOptions
    {
        public Meziantou.Framework.Imaging.Size CanvasSize { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.ImageEncoder? Encoder { get => throw null; init { } }
        public int? ExpectedFrameCount { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Metadata.ImageMetadata? Metadata { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Metadata.AnimationMetadata? Animation { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ImageConfiguration Configuration { get => throw null; init { } }
        public bool LeaveOpen { get => throw null; init { } }
        public ImageWriterOptions(Meziantou.Framework.Imaging.Size canvasSize) { }
        public ImageWriterOptions(int width, int height) { }
    }

    public sealed class ImageWriter<TPixel> : System.IAsyncDisposable, System.IDisposable where TPixel : struct
    {
        public Meziantou.Framework.Imaging.Size CanvasSize { get => throw null; }
        public Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public int FramesWritten { get => throw null; }
        public void WritePosterFrame(Meziantou.Framework.Imaging.ImageFrame<TPixel> frame) { }
        public System.Threading.Tasks.ValueTask WritePosterFrameAsync(Meziantou.Framework.Imaging.ImageFrame<TPixel> frame, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public void WriteFrame(Meziantou.Framework.Imaging.ImageFrame<TPixel> frame) { }
        public System.Threading.Tasks.ValueTask WriteFrameAsync(Meziantou.Framework.Imaging.ImageFrame<TPixel> frame, System.Threading.CancellationToken cancellationToken = null) => throw null;
        public void Complete() { }
        public System.Threading.Tasks.ValueTask CompleteAsync(System.Threading.CancellationToken cancellationToken = null) => throw null;
        public void Dispose() { }
        public System.Threading.Tasks.ValueTask DisposeAsync() => throw null;
    }

    public sealed class Image<TPixel> : Meziantou.Framework.Imaging.Image where TPixel : struct
    {
        public override Meziantou.Framework.Imaging.PixelFormat PixelFormat { get => throw null; }
        public virtual Meziantou.Framework.Imaging.ImageFrameCollection<TPixel> Frames { get => throw null; }
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel>? PosterFrame { get => throw null; }
        public Image(int width, int height, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) { }
        public Image(int width, int height, TPixel fill, Meziantou.Framework.Imaging.ImageConfiguration? configuration = null) { }
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.Image<TPixel> Clone() => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.Image<TPixel> CloneFrame(int index) => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.Image<TPixel> ClonePosterFrame() => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel> AppendFrame() => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel> AppendFrame(Meziantou.Framework.Imaging.ImageFrame source) => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel> InsertFrame(int index, Meziantou.Framework.Imaging.ImageFrame source) => throw null;
        [System.Runtime.CompilerServices.PreserveBaseOverrides]
        public virtual Meziantou.Framework.Imaging.ImageFrame<TPixel> SetPosterFrame(Meziantou.Framework.Imaging.ImageFrame source) => throw null;
    }

    public class InvalidImageContentException : Meziantou.Framework.Imaging.ImageException
    {
        public Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public InvalidImageContentException(string? message) { }
        public InvalidImageContentException(string? message, System.Exception? innerException) { }
        public InvalidImageContentException(string? message, Meziantou.Framework.Imaging.ImageFormat format, System.Exception? innerException = null) { }
    }

    public ref struct PixelAccessor<TPixel> where TPixel : struct
    {
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public System.Span<TPixel> GetRowSpan(int y) => throw null;
    }

    public ref struct PixelBytesAccessor
    {
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public Meziantou.Framework.Imaging.PixelFormat PixelFormat { get => throw null; }
        public int RowLength { get => throw null; }
        public System.Span<byte> GetRowSpan(int y) => throw null;
    }

    public delegate void PixelBytesAction(Meziantou.Framework.Imaging.PixelBytesAccessor pixels);

    public delegate void PixelBytesAction<TState>(Meziantou.Framework.Imaging.PixelBytesAccessor pixels, TState state) where TState : allows ref struct;

    public sealed class PixelConversionOptions
    {
        public static Meziantou.Framework.Imaging.PixelConversionOptions Default { get => throw null; }
        public Meziantou.Framework.Imaging.Rgba64? BackgroundColor { get => throw null; init { } }
        public bool DiscardIncompatibleColorProfile { get => throw null; init { } }
    }

    public enum PixelFormat
    {
        Unknown = 0,
        Rgba32 = 1,
        Bgra32 = 2,
        Rgb24 = 3,
        Rgba64 = 4,
        Gray8 = 5,
        Gray16 = 6,
    }

    public static class PixelFormats
    {
        public static System.Collections.Generic.IReadOnlyList<Meziantou.Framework.Imaging.PixelFormat> All { get => throw null; }
        public static bool IsSupported<TPixel>() where TPixel : struct => throw null;
        public static Meziantou.Framework.Imaging.PixelFormat GetPixelFormat<TPixel>() where TPixel : struct => throw null;
        public static System.Type GetPixelType(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
        public static int GetBytesPerPixel(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
        public static int GetBitsPerComponent(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
        public static int GetComponentCount(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
        public static bool HasAlpha(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
        public static bool IsGrayscale(Meziantou.Framework.Imaging.PixelFormat format) => throw null;
    }

    public delegate void PixelRowsAction<TPixel>(Meziantou.Framework.Imaging.PixelAccessor<TPixel> pixels) where TPixel : struct;

    public delegate void PixelRowsAction<TPixel, TState>(Meziantou.Framework.Imaging.PixelAccessor<TPixel> pixels, TState state) where TPixel : struct where TState : allows ref struct;

    public readonly struct Point : System.IEquatable<Meziantou.Framework.Imaging.Point>
    {
        public static Meziantou.Framework.Imaging.Point Empty { get => throw null; }
        public int X { get => throw null; }
        public int Y { get => throw null; }
        public Point(int x, int y) { }
        public void Deconstruct(out int x, out int y) => throw null;
        public bool Equals(Meziantou.Framework.Imaging.Point other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Point left, Meziantou.Framework.Imaging.Point right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Point left, Meziantou.Framework.Imaging.Point right) => throw null;
    }

    public readonly struct Rectangle : System.IEquatable<Meziantou.Framework.Imaging.Rectangle>
    {
        public static Meziantou.Framework.Imaging.Rectangle Empty { get => throw null; }
        public int X { get => throw null; }
        public int Y { get => throw null; }
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public int Left { get => throw null; }
        public int Top { get => throw null; }
        public int Right { get => throw null; }
        public int Bottom { get => throw null; }
        public Meziantou.Framework.Imaging.Point Location { get => throw null; }
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public bool IsEmpty { get => throw null; }
        public Rectangle(int x, int y, int width, int height) { }
        public Rectangle(Meziantou.Framework.Imaging.Point location, Meziantou.Framework.Imaging.Size size) { }
        public static Meziantou.Framework.Imaging.Rectangle FromLTRB(int left, int top, int right, int bottom) => throw null;
        public static Meziantou.Framework.Imaging.Rectangle Intersect(Meziantou.Framework.Imaging.Rectangle a, Meziantou.Framework.Imaging.Rectangle b) => throw null;
        public bool Contains(Meziantou.Framework.Imaging.Point point) => throw null;
        public bool Contains(Meziantou.Framework.Imaging.Rectangle rectangle) => throw null;
        public bool IntersectsWith(Meziantou.Framework.Imaging.Rectangle rectangle) => throw null;
        public bool Equals(Meziantou.Framework.Imaging.Rectangle other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Rectangle left, Meziantou.Framework.Imaging.Rectangle right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Rectangle left, Meziantou.Framework.Imaging.Rectangle right) => throw null;
    }

    public enum ResamplingFilter
    {
        NearestNeighbor = 0,
        Bilinear = 1,
        Bicubic = 2,
        Lanczos3 = 3,
    }

    public enum ResizeAnchor
    {
        Center = 0,
        TopLeft = 1,
        Top = 2,
        TopRight = 3,
        Left = 4,
        Right = 5,
        BottomLeft = 6,
        Bottom = 7,
        BottomRight = 8,
    }

    public enum ResizeMode
    {
        Contain = 0,
        Stretch = 1,
        Cover = 2,
    }

    public sealed class ResizeOptions
    {
        public Meziantou.Framework.Imaging.Size Size { get => throw null; }
        public Meziantou.Framework.Imaging.ResizeMode Mode { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ResizeAnchor Anchor { get => throw null; init { } }
        public bool AllowUpscaling { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ResamplingFilter Filter { get => throw null; init { } }
        public Meziantou.Framework.Imaging.ResizeWorkingSpace WorkingSpace { get => throw null; init { } }
        public ResizeOptions(int width, int height) { }
        public ResizeOptions(Meziantou.Framework.Imaging.Size size) { }
    }

    public enum ResizeWorkingSpace
    {
        Encoded = 0,
        LinearSrgb = 1,
    }

    public struct Rgb24 : System.IEquatable<Meziantou.Framework.Imaging.Rgb24>
    {
        public byte R;
        public byte G;
        public byte B;
        public Rgb24(byte r, byte g, byte b) { }
        public readonly bool Equals(Meziantou.Framework.Imaging.Rgb24 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Rgb24 left, Meziantou.Framework.Imaging.Rgb24 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Rgb24 left, Meziantou.Framework.Imaging.Rgb24 right) => throw null;
    }

    public struct Rgba32 : System.IEquatable<Meziantou.Framework.Imaging.Rgba32>
    {
        public byte R;
        public byte G;
        public byte B;
        public byte A;
        public Rgba32(byte r, byte g, byte b, byte a = 255) { }
        public readonly Meziantou.Framework.Imaging.Rgba64 ToRgba64() => throw null;
        public readonly bool Equals(Meziantou.Framework.Imaging.Rgba32 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static implicit operator Meziantou.Framework.Imaging.Rgba64(Meziantou.Framework.Imaging.Rgba32 value) => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Rgba32 left, Meziantou.Framework.Imaging.Rgba32 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Rgba32 left, Meziantou.Framework.Imaging.Rgba32 right) => throw null;
    }

    public struct Rgba64 : System.IEquatable<Meziantou.Framework.Imaging.Rgba64>
    {
        public ushort R;
        public ushort G;
        public ushort B;
        public ushort A;
        public Rgba64(ushort r, ushort g, ushort b, ushort a = 65535) { }
        public static Meziantou.Framework.Imaging.Rgba64 FromRgba32(Meziantou.Framework.Imaging.Rgba32 value) => throw null;
        public readonly bool Equals(Meziantou.Framework.Imaging.Rgba64 other) => throw null;
        public readonly override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public readonly override int GetHashCode() => throw null;
        public readonly override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Rgba64 left, Meziantou.Framework.Imaging.Rgba64 right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Rgba64 left, Meziantou.Framework.Imaging.Rgba64 right) => throw null;
    }

    public enum RotateMode
    {
        None = 0,
        Rotate90 = 90,
        Rotate180 = 180,
        Rotate270 = 270,
    }

    public readonly struct Size : System.IEquatable<Meziantou.Framework.Imaging.Size>
    {
        public static Meziantou.Framework.Imaging.Size Empty { get => throw null; }
        public int Width { get => throw null; }
        public int Height { get => throw null; }
        public bool IsEmpty { get => throw null; }
        public long Area { get => throw null; }
        public Size(int width, int height) { }
        public void Deconstruct(out int width, out int height) => throw null;
        public bool Equals(Meziantou.Framework.Imaging.Size other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public override string ToString() => throw null;
        public static bool operator ==(Meziantou.Framework.Imaging.Size left, Meziantou.Framework.Imaging.Size right) => throw null;
        public static bool operator !=(Meziantou.Framework.Imaging.Size left, Meziantou.Framework.Imaging.Size right) => throw null;
    }

    public class UnknownImageFormatException : Meziantou.Framework.Imaging.ImageException
    {
        public UnknownImageFormatException(string? message) { }
        public UnknownImageFormatException(string? message, System.Exception? innerException) { }
    }

    public class UnsupportedImageFeatureException : Meziantou.Framework.Imaging.ImageException
    {
        public Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public string? Feature { get => throw null; }
        public UnsupportedImageFeatureException(string? message) { }
        public UnsupportedImageFeatureException(string? message, System.Exception? innerException) { }
        public UnsupportedImageFeatureException(string? message, Meziantou.Framework.Imaging.ImageFormat format, string? feature) { }
    }
}
namespace Meziantou.Framework.Imaging.Formats
{
    public sealed class BmpEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.BmpPixelLayout PixelLayout { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Rgba64? BackgroundColor { get => throw null; init { } }
        public bool AllowBitDepthReduction { get => throw null; init { } }
    }

    public enum BmpPixelLayout
    {
        Auto = 0,
        Bgr24 = 1,
        Bgra32 = 2,
    }

    public enum FrameDurationRounding
    {
        RequireExact = 0,
        RoundToNearest = 1,
    }

    public enum GifAlphaMode
    {
        Threshold = 0,
        Flatten = 1,
    }

    public enum GifDithering
    {
        None = 0,
        FloydSteinberg = 1,
    }

    public sealed class GifEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.GifAlphaMode AlphaMode { get => throw null; init { } }
        public byte AlphaThreshold { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Rgba64? BackgroundColor { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.GifDithering Dithering { get => throw null; init { } }
        public int MaxColors { get => throw null; init { } }
        public bool Interlaced { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.FrameDurationRounding DurationRounding { get => throw null; init { } }
    }

    public sealed class IcoEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public const int MaxDimension = 256;
        public const int AutoDibMaxDimension = 64;
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.IconKind Kind { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.IconPayloadFormat PayloadFormat { get => throw null; init { } }
    }

    public enum IconKind
    {
        None = 0,
        Icon = 1,
        Cursor = 2,
    }

    public enum IconPayloadFormat
    {
        Auto = 0,
        Png = 1,
        Dib = 2,
    }

    public abstract class ImageEncoder
    {
        public abstract Meziantou.Framework.Imaging.ImageFormat Format { get; }
        public Meziantou.Framework.Imaging.Formats.MetadataHandling MetadataHandling { get => throw null; init { } }
    }

    public enum JpegChromaSubsampling
    {
        Auto = 0,
        Ratio444 = 1,
        Ratio422 = 2,
        Ratio420 = 3,
    }

    public sealed class JpegEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public int Quality { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.JpegChromaSubsampling ChromaSubsampling { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Rgba64? BackgroundColor { get => throw null; init { } }
        public bool AllowBitDepthReduction { get => throw null; init { } }
    }

    public enum MetadataHandling
    {
        Strict = 0,
        DiscardUnsupported = 1,
        Strip = 2,
    }

    public enum PngAnimationMode
    {
        Auto = 0,
        Static = 1,
        Animated = 2,
    }

    public sealed class PngEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.PngAnimationMode AnimationMode { get => throw null; init { } }
        public System.IO.Compression.CompressionLevel CompressionLevel { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.PngFilter Filter { get => throw null; init { } }
        public bool Interlaced { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.FrameDurationRounding DurationRounding { get => throw null; init { } }
    }

    public enum PngFilter
    {
        Adaptive = 0,
        None = 1,
        Sub = 2,
        Up = 3,
        Average = 4,
        Paeth = 5,
    }

    public sealed class PnmEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.PnmEncoding Encoding { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Rgba64? BackgroundColor { get => throw null; init { } }
    }

    public enum PnmEncoding
    {
        Binary = 0,
        Plain = 1,
    }

    public sealed class QoiEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public bool AllowBitDepthReduction { get => throw null; init { } }
    }

    public enum TgaCompression
    {
        None = 0,
        RunLength = 1,
    }

    public sealed class TgaEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.TgaCompression Compression { get => throw null; init { } }
        public bool AllowBitDepthReduction { get => throw null; init { } }
    }

    public enum TiffCompression
    {
        None = 0,
        Deflate = 1,
    }

    public sealed class TiffEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public const int DefaultStripBytes = 65536;
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.TiffCompression Compression { get => throw null; init { } }
        public bool BigTiff { get => throw null; init { } }
        public bool BigEndian { get => throw null; init { } }
        public int RowsPerStrip { get => throw null; init { } }
    }

    public enum WebPCompression
    {
        Lossless = 0,
        Lossy = 1,
    }

    public sealed class WebPEncoder : Meziantou.Framework.Imaging.Formats.ImageEncoder
    {
        public override Meziantou.Framework.Imaging.ImageFormat Format { get => throw null; }
        public Meziantou.Framework.Imaging.Formats.WebPCompression Compression { get => throw null; init { } }
        public int Quality { get => throw null; init { } }
        public int Effort { get => throw null; init { } }
        public bool ClearTransparentColors { get => throw null; init { } }
        public bool AllowBitDepthReduction { get => throw null; init { } }
        public Meziantou.Framework.Imaging.Formats.FrameDurationRounding DurationRounding { get => throw null; init { } }
    }
}
namespace Meziantou.Framework.Imaging.Metadata
{
    public sealed class AnimationMetadata
    {
        public int? TotalPlays { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.AnimationMetadata Clone() => throw null;
    }

    public enum ColorTransferFunction
    {
        Srgb = 0,
        Linear = 1,
    }

    public enum ExifOrientation
    {
        TopLeft = 1,
        TopRight = 2,
        BottomRight = 3,
        BottomLeft = 4,
        LeftTop = 5,
        RightTop = 6,
        RightBottom = 7,
        LeftBottom = 8,
    }

    public sealed class ExifProfile
    {
        public Meziantou.Framework.Imaging.Metadata.MetadataBlob Data { get => throw null; }
        public ExifProfile(Meziantou.Framework.Imaging.Metadata.MetadataBlob data) { }
    }

    public sealed class FrameMetadata
    {
        public Meziantou.Framework.Imaging.FrameDuration Duration { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.FrameMetadata Clone() => throw null;
    }

    public sealed class IccProfile
    {
        public static Meziantou.Framework.Imaging.Metadata.IccProfile Srgb { get => throw null; }
        public static Meziantou.Framework.Imaging.Metadata.IccProfile SrgbGray { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.MetadataBlob Data { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.IccProfileColorSpace ColorSpace { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.IccProfileClass ProfileClass { get => throw null; }
        public System.Version Version { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.IccRenderingIntent? RenderingIntent { get => throw null; }
        public IccProfile(Meziantou.Framework.Imaging.Metadata.MetadataBlob data) { }
    }

    public enum IccProfileClass
    {
        Unknown = 0,
        Input = 1,
        Display = 2,
        Output = 3,
        DeviceLink = 4,
        ColorSpace = 5,
        Abstract = 6,
        NamedColor = 7,
        Other = 8,
    }

    public enum IccProfileColorSpace
    {
        Unknown = 0,
        Gray = 1,
        Rgb = 2,
        Cmyk = 3,
        Other = 4,
    }

    public enum IccRenderingIntent
    {
        Perceptual = 0,
        RelativeColorimetric = 1,
        Saturation = 2,
        AbsoluteColorimetric = 3,
    }

    public sealed class ImageMetadata
    {
        public Meziantou.Framework.Imaging.ImageFormat SourceFormat { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.ExifOrientation Orientation { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.ImageResolution? Resolution { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.IccProfile? IccProfile { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.ColorTransferFunction TransferFunction { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.ExifProfile? ExifProfile { get => throw null; set { } }
        public Meziantou.Framework.Imaging.Metadata.XmpProfile? XmpProfile { get => throw null; set { } }
        public System.Collections.Generic.IList<Meziantou.Framework.Imaging.Metadata.ImageTextEntry> TextEntries { get => throw null; }
        public Meziantou.Framework.Imaging.Metadata.ImageMetadata Clone() => throw null;
    }

    public sealed class ImageResolution : System.IEquatable<Meziantou.Framework.Imaging.Metadata.ImageResolution>
    {
        public double HorizontalDpi { get => throw null; }
        public double VerticalDpi { get => throw null; }
        public ImageResolution(double horizontalDpi, double verticalDpi) { }
        public bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] Meziantou.Framework.Imaging.Metadata.ImageResolution? other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public override string ToString() => throw null;
    }

    public sealed class ImageTextEntry : System.IEquatable<Meziantou.Framework.Imaging.Metadata.ImageTextEntry>
    {
        public const string CommentKeyword = "Comment";
        public string Keyword { get => throw null; }
        public string Value { get => throw null; }
        public string? LanguageTag { get => throw null; }
        public string? TranslatedKeyword { get => throw null; }
        public ImageTextEntry(string keyword, string value, string? languageTag = null, string? translatedKeyword = null) { }
        public bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] Meziantou.Framework.Imaging.Metadata.ImageTextEntry? other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
        public override string ToString() => throw null;
    }

    public sealed class MetadataBlob : System.IEquatable<Meziantou.Framework.Imaging.Metadata.MetadataBlob>
    {
        public int Length { get => throw null; }
        public System.ReadOnlyMemory<byte> Memory { get => throw null; }
        public System.ReadOnlySpan<byte> Span { get => throw null; }
        public MetadataBlob(System.ReadOnlySpan<byte> data) { }
        public byte[] ToArray() => throw null;
        public bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] Meziantou.Framework.Imaging.Metadata.MetadataBlob? other) => throw null;
        public override bool Equals([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] object? obj) => throw null;
        public override int GetHashCode() => throw null;
    }

    public sealed class XmpProfile
    {
        public Meziantou.Framework.Imaging.Metadata.MetadataBlob Data { get => throw null; }
        public XmpProfile(Meziantou.Framework.Imaging.Metadata.MetadataBlob data) { }
    }
}
