// <auto-generated/>
// Target Frameworks: net10.0, net8.0, net9.0
#nullable enable

namespace Meziantou.Framework.Win32
{
    [System.Runtime.Versioning.SupportedOSPlatform("windows5.1.2600")]
    public static class LsaPrivateData
    {
        public static void RemoveValue(string key) { }
        public static void SetValue(string key, string? value) { }
        public static string? GetValue(string key) => throw null;
    }
}
