<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework</RootNamespace>
    <Version>3.0.1</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>Stopwatch without any allocation</Description>
    <PackageTags>stopwatch, timing, performance, allocation-free, struct</PackageTags>
  </PropertyGroup>

</Project>
