using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Meziantou.Framework.FixedString.Generator;

[Generator]
public sealed class FixedStringSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs", SourceText.From(
                """
                // <auto-generated/>
                #pragma warning disable
                namespace Microsoft.CodeAnalysis
                {
                    internal sealed partial class EmbeddedAttribute : global::System.Attribute
                    {
                    }
                }
                """, Encoding.UTF8));

            context.AddSource("FixedStringAttribute.g.cs", SourceText.From(
                """
                // <auto-generated/>
                #pragma warning disable
                [global::Microsoft.CodeAnalysis.Embedded]
                [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                internal partial class FixedStringAttribute : global::System.Attribute
                {
                    public FixedStringAttribute(int length)
                    {
                        Length = length;
                    }

                    public int Length { get; }
                }
                """, Encoding.UTF8));
        });

        var candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "FixedStringAttribute",
                predicate: static (syntaxNode, _) => syntaxNode is StructDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetTarget(ctx, cancellationToken))
            .Where(static item => item is not null);

        context.RegisterSourceOutput(candidates, static (context, target) => Generate(context, target!));
    }

    private static FixedStringTypeInfo? GetTarget(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetNode is not StructDeclarationSyntax declaration)
            return null;

        if (!declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            return null;

        if (context.TargetSymbol is not INamedTypeSymbol targetTypeSymbol)
            return null;

        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length != 1)
                continue;

            if (attribute.ConstructorArguments[0].Value is int length and > 0)
            {
                var fixedStringInterface = context.SemanticModel.Compilation.GetTypeByMetadataName("Meziantou.Framework.FixedString.IFixedString`1");
                var fixedStringNonGenericInterface = context.SemanticModel.Compilation.GetTypeByMetadataName("Meziantou.Framework.FixedString.IFixedString");
                return new FixedStringTypeInfo(targetTypeSymbol, length, fixedStringInterface is not null, fixedStringNonGenericInterface is not null);
            }
        }

        return null;
    }

    private static void Generate(SourceProductionContext context, FixedStringTypeInfo target)
    {
        var hintName = target.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "", StringComparison.Ordinal)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('.', '_')
            .Replace('+', '_') + ".g.cs";

        var source = GenerateSource(target);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(FixedStringTypeInfo target)
    {
        var sb = new StringBuilder();
        var indent = 0;

        AppendLine("// <auto-generated/>");
        AppendLine("#nullable enable");
        AppendLine("using System;");
        AppendLine("using System.ComponentModel;");
        AppendLine("using System.Runtime.CompilerServices;");
        AppendLine("using System.Runtime.InteropServices;");
        AppendLine();

        var namespaceName = target.Type.ContainingNamespace.IsGlobalNamespace
            ? null
            : target.Type.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            AppendLine($"namespace {namespaceName}");
            AppendLine("{");
            indent++;
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var containingType = target.Type.ContainingType; containingType is not null; containingType = containingType.ContainingType)
        {
            containingTypes.Push(containingType);
        }

        foreach (var containingType in containingTypes)
        {
            AppendLine($"{GetAccessibility(containingType.DeclaredAccessibility)} partial {GetTypeKeyword(containingType)} {containingType.Name}{GetTypeParameters(containingType)}");
            AppendLine("{");
            indent++;
        }

        var fullTypeName = target.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var simpleTypeName = target.Type.Name + GetTypeParameters(target.Type);
        var implementedInterfaces = new List<string>
        {
            $"global::System.IEquatable<{fullTypeName}>",
            "global::System.ISpanFormattable",
        };

        if (target.ImplementsIFixedStringGeneric)
        {
            implementedInterfaces.Add($"global::Meziantou.Framework.FixedString.IFixedString<{fullTypeName}>");
        }

        AppendLine("[global::System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute]");
        AppendLine($"{GetAccessibility(target.Type.DeclaredAccessibility)} partial struct {target.Type.Name}{GetTypeParameters(target.Type)} : {string.Join(", ", implementedInterfaces)}");
        AppendLine("{");
        indent++;

        AppendLine("public static int MaxLength");
        AppendLine("{");
        indent++;
        AppendLine($"get => {target.Length};");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("private short _length;");
        AppendLine("#pragma warning disable CS0169");
        for (var i = 0; i < target.Length; i++)
        {
            AppendLine($"private short _c{i};");
        }

        AppendLine("#pragma warning restore CS0169");
        AppendLine();

        AppendLine($"public {simpleTypeName}(int literalLength, int formattedCount)");
        AppendLine("{");
        indent++;
        AppendLine("_length = 0;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine($"public {simpleTypeName}(string value)");
        AppendLine("{");
        indent++;
        AppendLine("_length = 0;");
        AppendLine("AppendLiteral(value);");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("public int Length");
        AppendLine("{");
        indent++;
        AppendLine("get => _length;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("public void Clear() => _length = 0;");
        AppendLine();

        AppendLine("public void AppendLiteral(ReadOnlySpan<char> value)");
        AppendLine("{");
        indent++;
        AppendLine("if (value.Length > MaxLength - _length)");
        AppendLine("{");
        indent++;
        AppendLine("ThrowValueTooLong();");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("value.CopyTo(AsRemainingSpan());");
        AppendLine("_length += (short)value.Length;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted(string value) => AppendLiteral(value);");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted(string value, int alignment)");
        AppendLine("{");
        indent++;
        AppendLine("var startPosition = _length;");
        AppendLine("AppendFormatted(value);");
        AppendLine("AppendOrInsertAlignment(startPosition, alignment);");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted<T>(T value) where T : ISpanFormattable");
        AppendLine("{");
        indent++;
        AppendLine("var span = AsRemainingSpan();");
        AppendLine("if (!value.TryFormat(span, out var charsWritten, ReadOnlySpan<char>.Empty, null))");
        AppendLine("{");
        indent++;
        AppendLine("ThrowValueTooLong();");
        indent--;
        AppendLine("}");
        AppendLine("_length += (short)charsWritten;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted<T>(T value, string? format) where T : ISpanFormattable");
        AppendLine("{");
        indent++;
        AppendLine("var span = AsRemainingSpan();");
        AppendLine("if (!value.TryFormat(span, out var charsWritten, format, null))");
        AppendLine("{");
        indent++;
        AppendLine("ThrowValueTooLong();");
        indent--;
        AppendLine("}");
        AppendLine("_length += (short)charsWritten;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted<T>(T value, int alignment) where T : ISpanFormattable");
        AppendLine("{");
        indent++;
        AppendLine("var startPosition = _length;");
        AppendLine("AppendFormatted(value);");
        AppendLine("AppendOrInsertAlignment(startPosition, alignment);");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public void AppendFormatted<T>(T value, int alignment, string? format) where T : ISpanFormattable");
        AppendLine("{");
        indent++;
        AppendLine("var startPosition = _length;");
        AppendLine("AppendFormatted(value, format);");
        AppendLine("AppendOrInsertAlignment(startPosition, alignment);");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine($"public bool Equals({simpleTypeName} other) => _length == other._length && AsSpan().SequenceEqual(other.AsSpan());");
        AppendLine();

        AppendLine("public override bool Equals(object? obj) => obj is " + simpleTypeName + " other && Equals(other);");
        AppendLine();

        AppendLine("public override int GetHashCode()");
        AppendLine("{");
        indent++;
        AppendLine("var hash = unchecked((int)2166136261);");
        AppendLine("foreach (var c in AsSpan())");
        AppendLine("{");
        indent++;
        AppendLine("hash ^= c;");
        AppendLine("hash *= 16777619;");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("return hash;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("public readonly ReadOnlySpan<char> AsSpan() => MemoryMarshal.CreateSpan(ref Unsafe.As<short, char>(ref Unsafe.AsRef(_c0)), _length);");
        AppendLine();
        if (target.ImplementsIFixedStringNonGeneric)
        {
            AppendLine("Span<char> global::Meziantou.Framework.FixedString.IFixedString.GetUnsafeFullSpan() => AsUnsafeFullSpan();");
            AppendLine();
        }

        AppendLine($"public static implicit operator {simpleTypeName}(string value) => new(value);");
        AppendLine();
        AppendLine("public override string ToString() => ToString(null, null);");
        AppendLine();
        AppendLine("public string ToString(string? format, IFormatProvider? formatProvider) => _length == 0 ? string.Empty : new string(AsSpan());");
        AppendLine();

        AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        AppendLine("public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
        AppendLine("{");
        indent++;
        AppendLine("if (destination.Length < _length)");
        AppendLine("{");
        indent++;
        AppendLine("charsWritten = 0;");
        AppendLine("return false;");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("AsSpan().CopyTo(destination);");
        AppendLine("charsWritten = _length;");
        AppendLine("return true;");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("private Span<char> AsUnsafeFullSpan() => MemoryMarshal.CreateSpan(ref Unsafe.As<short, char>(ref _c0), MaxLength);");
        AppendLine();
        AppendLine("private Span<char> AsRemainingSpan() => AsUnsafeFullSpan().Slice(_length);");
        AppendLine();

        AppendLine("private void AppendOrInsertAlignment(int startPosition, int alignment)");
        AppendLine("{");
        indent++;
        AppendLine("if (alignment == 0)");
        AppendLine("{");
        indent++;
        AppendLine("return;");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("var length = _length - startPosition;");
        AppendLine("var padAfter = false;");
        AppendLine("if (alignment < 0)");
        AppendLine("{");
        indent++;
        AppendLine("padAfter = true;");
        AppendLine("alignment = -alignment;");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("var numberOfCharsToAppendOrInsert = alignment - length;");
        AppendLine("if (numberOfCharsToAppendOrInsert <= 0)");
        AppendLine("{");
        indent++;
        AppendLine("return;");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("if (numberOfCharsToAppendOrInsert > MaxLength - _length)");
        AppendLine("{");
        indent++;
        AppendLine("ThrowValueTooLong();");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("if (padAfter)");
        AppendLine("{");
        indent++;
        AppendLine("AsRemainingSpan().Slice(0, numberOfCharsToAppendOrInsert).Fill(' ');");
        AppendLine("_length += (short)numberOfCharsToAppendOrInsert;");
        indent--;
        AppendLine("}");
        AppendLine("else");
        AppendLine("{");
        indent++;
        AppendLine("var endPositionFill = startPosition + numberOfCharsToAppendOrInsert;");
        AppendLine("var span = AsUnsafeFullSpan();");
        AppendLine("if (length > 0)");
        AppendLine("{");
        indent++;
        AppendLine("span.Slice(startPosition, length).CopyTo(span.Slice(endPositionFill, length));");
        indent--;
        AppendLine("}");
        AppendLine();
        AppendLine("span.Slice(startPosition, numberOfCharsToAppendOrInsert).Fill(' ');");
        AppendLine("_length += (short)numberOfCharsToAppendOrInsert;");
        indent--;
        AppendLine("}");
        indent--;
        AppendLine("}");
        AppendLine();

        AppendLine("private static void ThrowValueTooLong() => throw new ArgumentException(\"The value is too long to fit in this fixed string.\");");

        indent--;
        AppendLine("}");

        while (containingTypes.Count > 0)
        {
            containingTypes.Pop();
            indent--;
            AppendLine("}");
        }

        if (namespaceName is not null)
        {
            indent--;
            AppendLine("}");
        }

        return sb.ToString();

        void AppendLine(string text = "")
        {
            if (text.Length == 0)
            {
                sb.AppendLine();
                return;
            }

            sb.Append(' ', indent * 4);
            sb.AppendLine(text);
        }
    }

    private static string GetTypeKeyword(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
            return symbol.TypeKind == TypeKind.Struct ? "record struct" : "record";

        return symbol.TypeKind switch
        {
            TypeKind.Struct => "struct",
            _ => "class",
        };
    }

    private static string GetAccessibility(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal",
        };
    }

    private static string GetTypeParameters(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
            return string.Empty;

        return "<" + string.Join(", ", symbol.TypeParameters.Select(static t => t.Name)) + ">";
    }

    private sealed record FixedStringTypeInfo(INamedTypeSymbol Type, int Length, bool ImplementsIFixedStringGeneric, bool ImplementsIFixedStringNonGeneric);
}
