using System.Collections.Immutable;
using System.Reflection;
using System.Reflection.Metadata;

namespace Meziantou.Framework.PublicApiGenerator;

internal sealed partial class PublicApiMetadataReader
{
    private const string IsReadOnlyAttributeFullName = "System.Runtime.CompilerServices.IsReadOnlyAttribute";
    private const string RequiredMemberAttributeFullName = "System.Runtime.CompilerServices.RequiredMemberAttribute";
    private const string ExtensionAttributeFullName = "System.Runtime.CompilerServices.ExtensionAttribute";

    private ImmutableArray<PublicApiMember> ReadMembers(TypeDefinitionHandle typeDefinitionHandle, TypeDefinition typeDefinition)
    {
        var explicitImplementations = BuildMethodImplementationMap(typeDefinition);
        var result = ImmutableArray.CreateBuilder<PublicApiMember>();
        foreach (var fieldHandle in typeDefinition.GetFields())
        {
            var field = _metadataReader.GetFieldDefinition(fieldHandle);
            if (!IsExternallyVisible(field.Attributes) || field.Attributes.HasFlag(FieldAttributes.SpecialName))
                continue;

            result.Add(ReadField(typeDefinitionHandle, fieldHandle, field));
        }

        foreach (var propertyHandle in typeDefinition.GetProperties())
        {
            var property = ReadProperty(typeDefinitionHandle, propertyHandle, explicitImplementations);
            if (property is not null)
            {
                result.Add(property);
            }
        }

        foreach (var eventHandle in typeDefinition.GetEvents())
        {
            var @event = ReadEvent(typeDefinitionHandle, eventHandle, explicitImplementations);
            if (@event is not null)
            {
                result.Add(@event);
            }
        }

        foreach (var methodHandle in typeDefinition.GetMethods())
        {
            var method = _metadataReader.GetMethodDefinition(methodHandle);
            var name = _metadataReader.GetString(method.Name);
            if (string.Equals(name, ".ctor", StringComparison.Ordinal))
            {
                if (!IsExternallyVisible(method.Attributes))
                    continue;

                result.Add(ReadMethod(typeDefinitionHandle, methodHandle, PublicApiMethodKind.Constructor, explicitImplementations));
                continue;
            }

            // Accessors and static constructors are special-name methods
            var isExplicitInterfaceImplementation = IsExplicitInterfaceImplementation(method.Attributes, name);
            if ((!IsExternallyVisible(method.Attributes) && !isExplicitInterfaceImplementation) ||
                (method.Attributes.HasFlag(MethodAttributes.SpecialName) && !IsOperatorName(name)) ||
                IsUnspeakableName(name, isExplicitInterfaceImplementation))
            {
                continue;
            }

            result.Add(ReadMethod(typeDefinitionHandle, methodHandle, GetMethodKind(method, name), explicitImplementations));
        }

        return result.ToImmutable();
    }

    private static bool IsOperatorName(string name) => name.StartsWith("op_", StringComparison.Ordinal);

    // Names generated by the compiler, such as "<Clone>$", cannot be used in C#.
    // The name of an explicit implementation of a generic interface contains its type arguments (e.g. "System.IEquatable<System.String>.Equals").
    private static bool IsUnspeakableName(string name, bool isExplicitInterfaceImplementation)
    {
        if (isExplicitInterfaceImplementation)
            return name.StartsWith('<', StringComparison.Ordinal) || name[(name.LastIndexOf(".", StringComparison.Ordinal) + 1)..].Contains('<', StringComparison.Ordinal);

        return name.Contains('<', StringComparison.Ordinal);
    }

    private static bool IsExplicitInterfaceImplementation(MethodAttributes attributes, string name)
    {
        return (attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Private &&
               attributes.HasFlag(MethodAttributes.Final) &&
               attributes.HasFlag(MethodAttributes.Virtual) &&
               name.Contains('.', StringComparison.Ordinal);
    }

    private PublicApiMethodKind GetMethodKind(MethodDefinition method, string name)
    {
        if (string.Equals(name, "Finalize", StringComparison.Ordinal) &&
            !method.Attributes.HasFlag(MethodAttributes.Static) &&
            GetParameterCount(method) == 0)
        {
            return PublicApiMethodKind.Destructor;
        }

        if (method.Attributes.HasFlag(MethodAttributes.SpecialName) && IsOperatorName(name))
        {
            return name is "op_Implicit" or "op_Explicit" or "op_CheckedExplicit"
                ? PublicApiMethodKind.Conversion
                : PublicApiMethodKind.Operator;
        }

        return PublicApiMethodKind.Ordinary;
    }

    private int GetParameterCount(MethodDefinition method)
    {
        var blobReader = _metadataReader.GetBlobReader(method.Signature);
        var header = blobReader.ReadSignatureHeader();
        if (header.IsGeneric)
        {
            blobReader.ReadCompressedInteger();
        }

        return blobReader.ReadCompressedInteger();
    }

    private PublicApiField ReadField(TypeDefinitionHandle declaringTypeHandle, FieldDefinitionHandle fieldHandle, FieldDefinition field)
    {
        var customAttributes = field.GetCustomAttributes();
        var rawType = field.DecodeSignature(_typeProvider, BuildGenericContext(declaringTypeHandle));
        var isVolatile = rawType.HasIsVolatileModifier;
        var refKind = PublicApiRefKind.None;
        if (rawType is RawType.ByReference byReference)
        {
            var isRefReadOnly = HasAttribute(customAttributes, IsReadOnlyAttributeFullName) ||
                                byReference.HasIsReadOnlyModifier ||
                                byReference.ElementType.HasIsReadOnlyModifier;
            refKind = isRefReadOnly ? PublicApiRefKind.RefReadOnly : PublicApiRefKind.Ref;
            rawType = byReference.ElementType;
        }

        var type = TypeReferenceBuilder.Build(rawType, GetNullableMetadataInfo(declaringTypeHandle, customAttributes), GetTupleElementNames(customAttributes));
        var isConst = field.Attributes.HasFlag(FieldAttributes.Literal);
        var hasConstantValue = !field.GetDefaultValue().IsNil;
        var constantValue = hasConstantValue ? DecodeConstantValue(_metadataReader.GetConstant(field.GetDefaultValue())) : null;
        var modifiers = new PublicApiMemberModifiers(
            IsStatic: field.Attributes.HasFlag(FieldAttributes.Static),
            RequiresUnsafe: IsRequiresUnsafeMember(customAttributes));

        return new PublicApiField(
            _metadataReader.GetString(field.Name),
            GetAccessibility(field.Attributes),
            ReadAttributes(customAttributes),
            CreateOrigin(fieldHandle),
            modifiers,
            type,
            refKind,
            isReadOnly: field.Attributes.HasFlag(FieldAttributes.InitOnly),
            isConst,
            hasConstantValue,
            constantValue,
            isVolatile,
            isRequired: HasAttribute(customAttributes, RequiredMemberAttributeFullName));
    }

    private PublicApiProperty? ReadProperty(TypeDefinitionHandle declaringTypeHandle, PropertyDefinitionHandle propertyHandle, Dictionary<MethodDefinitionHandle, List<EntityHandle>> explicitImplementations)
    {
        var property = _metadataReader.GetPropertyDefinition(propertyHandle);
        var name = _metadataReader.GetString(property.Name);
        var accessors = property.GetAccessors();
        var getAccessorHandle = accessors.Getter;
        var setAccessorHandle = accessors.Setter;
        var getAccessor = getAccessorHandle.IsNil ? default(MethodDefinition?) : _metadataReader.GetMethodDefinition(getAccessorHandle);
        var setAccessor = setAccessorHandle.IsNil ? default(MethodDefinition?) : _metadataReader.GetMethodDefinition(setAccessorHandle);

        var includeGetter = getAccessor is not null && IsExternallyVisible(getAccessor.Value.Attributes);
        var includeSetter = setAccessor is not null && IsExternallyVisible(setAccessor.Value.Attributes);
        var isExplicitInterfaceImplementation = false;
        if (!includeGetter && !includeSetter)
        {
            // Explicit interface implementations have private accessors
            includeGetter = getAccessor is not null && IsExplicitInterfaceImplementation(getAccessor.Value.Attributes, _metadataReader.GetString(getAccessor.Value.Name));
            includeSetter = setAccessor is not null && IsExplicitInterfaceImplementation(setAccessor.Value.Attributes, _metadataReader.GetString(setAccessor.Value.Name));
            isExplicitInterfaceImplementation = includeGetter || includeSetter;
            if (!isExplicitInterfaceImplementation)
                return null;
        }

        var representativeAttributes = includeGetter && includeSetter
            ? GetAccessibilityRank(getAccessor!.Value.Attributes) >= GetAccessibilityRank(setAccessor!.Value.Attributes) ? getAccessor.Value.Attributes : setAccessor.Value.Attributes
            : includeGetter ? getAccessor!.Value.Attributes : setAccessor!.Value.Attributes;

        var propertyAttributes = property.GetCustomAttributes();
        NullableMetadataInfo nullableInfo;
        CustomAttributeHandleCollection? typeAttributes;
        if (includeGetter)
        {
            typeAttributes = GetParameterCustomAttributes(getAccessor!.Value, sequenceNumber: 0);
            nullableInfo = GetNullableMetadataInfo(declaringTypeHandle, typeAttributes, getAccessorHandle, propertyAttributes);
        }
        else
        {
            typeAttributes = GetParameterCustomAttributes(setAccessor!.Value, sequenceNumber: 1);
            nullableInfo = GetNullableMetadataInfo(declaringTypeHandle, typeAttributes, setAccessorHandle, propertyAttributes);
        }

        var signature = property.DecodeSignature(_typeProvider, BuildGenericContext(declaringTypeHandle));
        var rawType = signature.ReturnType;
        var refKind = PublicApiRefKind.None;
        if (rawType is RawType.ByReference byReference)
        {
            var isRefReadOnly = HasAttribute(propertyAttributes, IsReadOnlyAttributeFullName) ||
                                (includeGetter && HasAttribute(GetParameterCustomAttributes(getAccessor!.Value, sequenceNumber: 0), IsReadOnlyAttributeFullName)) ||
                                byReference.HasInModifier || byReference.ElementType.HasInModifier;
            refKind = isRefReadOnly ? PublicApiRefKind.RefReadOnly : PublicApiRefKind.Ref;
            rawType = byReference.ElementType;
        }

        var tupleElementNames = GetTupleElementNames(propertyAttributes);
        if (tupleElementNames.IsDefault)
        {
            tupleElementNames = GetTupleElementNames(typeAttributes);
        }

        var type = TypeReferenceBuilder.Build(rawType, nullableInfo, tupleElementNames);

        // Indexer parameters are named by the accessors
        var parameters = ImmutableArray<PublicApiParameter>.Empty;
        if (signature.ParameterTypes.Length > 0)
        {
            var accessorHandle = getAccessor is not null ? getAccessorHandle : setAccessorHandle;
            parameters = ReadParameters(declaringTypeHandle, accessorHandle, _metadataReader.GetMethodDefinition(accessorHandle), signature.ParameterTypes, isExtensionMethod: false);
        }

        var getMethod = includeGetter ? ReadMethod(declaringTypeHandle, getAccessorHandle, PublicApiMethodKind.PropertyGet, explicitImplementations) : null;
        var setMethod = includeSetter ? ReadMethod(declaringTypeHandle, setAccessorHandle, PublicApiMethodKind.PropertySet, explicitImplementations) : null;
        var modifiers = GetMethodModifiers(representativeAttributes, isExplicitInterfaceImplementation, IsRequiresUnsafeMember(propertyAttributes));
        var accessibility = isExplicitInterfaceImplementation ? PublicApiAccessibility.Private : GetAccessibility(representativeAttributes);
        var isReadOnly = (getMethod is null || getMethod.IsReadOnly) && (setMethod is null || setMethod.IsReadOnly);

        var explicitReferences = ImmutableArray.CreateBuilder<PublicApiMemberReference>();
        foreach (var accessor in (ReadOnlySpan<(MethodDefinitionHandle Handle, bool IsGetter)>)[(getAccessorHandle, true), (setAccessorHandle, false)])
        {
            if (accessor.Handle.IsNil || !explicitImplementations.TryGetValue(accessor.Handle, out var declarations))
                continue;

            foreach (var declaration in declarations)
            {
                var reference = CreateExplicitPropertyOrEventReference(declaringTypeHandle, declaration, PublicApiSymbolKind.Property, removeLastParameter: !accessor.IsGetter);
                if (reference is not null && !explicitReferences.Any(existing => string.Equals(existing.DocumentationId, reference.DocumentationId, StringComparison.Ordinal)))
                {
                    explicitReferences.Add(reference);
                }
            }
        }

        var result = new PublicApiProperty(
            name,
            accessibility,
            ReadAttributes(propertyAttributes),
            CreateOrigin(propertyHandle),
            modifiers,
            explicitReferences.ToImmutable(),
            type,
            refKind,
            parameters,
            getMethod,
            setMethod,
            isRequired: HasAttribute(propertyAttributes, RequiredMemberAttributeFullName),
            isReadOnly);
        if (getMethod is not null)
        {
            getMethod.AssociatedSymbol = result;
        }

        if (setMethod is not null)
        {
            setMethod.AssociatedSymbol = result;
        }

        return result;
    }

    private PublicApiEvent? ReadEvent(TypeDefinitionHandle declaringTypeHandle, EventDefinitionHandle eventHandle, Dictionary<MethodDefinitionHandle, List<EntityHandle>> explicitImplementations)
    {
        var eventDefinition = _metadataReader.GetEventDefinition(eventHandle);
        var accessors = eventDefinition.GetAccessors();
        if (accessors.Adder.IsNil)
            return null;

        var addMethodDefinition = _metadataReader.GetMethodDefinition(accessors.Adder);
        var isExplicitInterfaceImplementation = false;
        if (!IsExternallyVisible(addMethodDefinition.Attributes))
        {
            isExplicitInterfaceImplementation = IsExplicitInterfaceImplementation(addMethodDefinition.Attributes, _metadataReader.GetString(addMethodDefinition.Name));
            if (!isExplicitInterfaceImplementation)
                return null;
        }

        var eventAttributes = eventDefinition.GetCustomAttributes();
        var addValueAttributes = GetParameterCustomAttributes(addMethodDefinition, sequenceNumber: 1);
        var nullableInfo = GetNullableMetadataInfo(declaringTypeHandle, addValueAttributes, accessors.Adder, eventAttributes);
        var addSignature = DecodeMethodSignature(declaringTypeHandle, accessors.Adder, addMethodDefinition);
        var tupleElementNames = GetTupleElementNames(eventAttributes);
        if (tupleElementNames.IsDefault)
        {
            tupleElementNames = GetTupleElementNames(addValueAttributes);
        }

        var rawType = addSignature.Signature.ParameterTypes.Length > 0 ? addSignature.Signature.ParameterTypes[0] : _typeProvider.GetPrimitiveType(PrimitiveTypeCode.Object);
        var type = TypeReferenceBuilder.Build(rawType, nullableInfo, tupleElementNames);

        var addMethod = ReadMethod(declaringTypeHandle, accessors.Adder, PublicApiMethodKind.EventAdd, explicitImplementations);
        var removeMethod = ReadEventAccessor(declaringTypeHandle, accessors.Remover, PublicApiMethodKind.EventRemove, explicitImplementations);
        var raiseMethod = ReadEventAccessor(declaringTypeHandle, accessors.Raiser, PublicApiMethodKind.EventRaise, explicitImplementations);

        var explicitReferences = ImmutableArray.CreateBuilder<PublicApiMemberReference>();
        if (explicitImplementations.TryGetValue(accessors.Adder, out var declarations))
        {
            foreach (var declaration in declarations)
            {
                var reference = CreateExplicitPropertyOrEventReference(declaringTypeHandle, declaration, PublicApiSymbolKind.Event, removeLastParameter: false);
                if (reference is not null)
                {
                    explicitReferences.Add(reference);
                }
            }
        }

        var result = new PublicApiEvent(
            _metadataReader.GetString(eventDefinition.Name),
            isExplicitInterfaceImplementation ? PublicApiAccessibility.Private : GetAccessibility(addMethodDefinition.Attributes),
            ReadAttributes(eventAttributes),
            CreateOrigin(eventHandle),
            GetMethodModifiers(addMethodDefinition.Attributes, isExplicitInterfaceImplementation, IsRequiresUnsafeMember(eventAttributes)),
            explicitReferences.ToImmutable(),
            type,
            addMethod,
            removeMethod,
            raiseMethod);
        addMethod.AssociatedSymbol = result;
        removeMethod?.AssociatedSymbol = result;
        raiseMethod?.AssociatedSymbol = result;
        return result;
    }

    private PublicApiMethod? ReadEventAccessor(TypeDefinitionHandle declaringTypeHandle, MethodDefinitionHandle accessorHandle, PublicApiMethodKind kind, Dictionary<MethodDefinitionHandle, List<EntityHandle>> explicitImplementations)
    {
        if (accessorHandle.IsNil)
            return null;

        var accessor = _metadataReader.GetMethodDefinition(accessorHandle);
        if (!IsExternallyVisible(accessor.Attributes) && !IsExplicitInterfaceImplementation(accessor.Attributes, _metadataReader.GetString(accessor.Name)))
            return null;

        return ReadMethod(declaringTypeHandle, accessorHandle, kind, explicitImplementations);
    }

    private PublicApiMethod ReadMethod(TypeDefinitionHandle declaringTypeHandle, MethodDefinitionHandle methodHandle, PublicApiMethodKind kind, Dictionary<MethodDefinitionHandle, List<EntityHandle>>? explicitImplementations)
    {
        var method = _metadataReader.GetMethodDefinition(methodHandle);
        var name = _metadataReader.GetString(method.Name);
        var customAttributes = method.GetCustomAttributes();
        var signature = DecodeMethodSignature(declaringTypeHandle, methodHandle, method);

        var returnAttributes = GetParameterCustomAttributes(method, sequenceNumber: 0);
        var returnNullableInfo = GetNullableMetadataInfo(declaringTypeHandle, returnAttributes, methodHandle);
        var rawReturnType = signature.Signature.ReturnType;
        var returnRefKind = PublicApiRefKind.None;
        if (rawReturnType is RawType.ByReference byReference)
        {
            var isRefReadOnly = HasAttribute(returnAttributes, IsReadOnlyAttributeFullName) ||
                                byReference.HasInModifier || byReference.ElementType.HasInModifier;
            returnRefKind = isRefReadOnly ? PublicApiRefKind.RefReadOnly : PublicApiRefKind.Ref;
            rawReturnType = byReference.ElementType;
        }

        var returnType = TypeReferenceBuilder.Build(rawReturnType, returnNullableInfo, GetTupleElementNames(returnAttributes));
        var isExtensionMethod = method.Attributes.HasFlag(MethodAttributes.Static) && HasAttribute(customAttributes, ExtensionAttributeFullName);
        var parameters = ReadParameters(declaringTypeHandle, methodHandle, method, signature.Signature.ParameterTypes, isExtensionMethod);
        var genericParameters = ReadGenericParameters(method.GetGenericParameters(), BuildGenericContext(declaringTypeHandle, methodHandle), declaringTypeHandle, methodHandle);
        var isExplicitInterfaceImplementation = IsExplicitInterfaceImplementation(method.Attributes, name);

        var explicitReferences = ImmutableArray<PublicApiMemberReference>.Empty;
        if (explicitImplementations is not null && explicitImplementations.TryGetValue(methodHandle, out var declarations))
        {
            var builder = ImmutableArray.CreateBuilder<PublicApiMemberReference>(declarations.Count);
            foreach (var declaration in declarations)
            {
                var reference = CreateExplicitMethodReference(declaringTypeHandle, declaration);
                if (reference is not null)
                {
                    builder.Add(reference);
                }
            }

            explicitReferences = builder.ToImmutable();
        }

        return new PublicApiMethod(
            name,
            isExplicitInterfaceImplementation ? PublicApiAccessibility.Private : GetAccessibility(method.Attributes),
            ReadAttributes(customAttributes),
            CreateOrigin(methodHandle),
            GetMethodModifiers(method.Attributes, isExplicitInterfaceImplementation, IsRequiresUnsafeMember(customAttributes)),
            explicitReferences,
            kind,
            returnType,
            returnRefKind,
            returnAttributes is null ? [] : ReadAttributes(returnAttributes.Value),
            parameters,
            genericParameters,
            isReadOnly: IsReadOnlyMember(_metadataReader.GetTypeDefinition(declaringTypeHandle), customAttributes),
            isExtensionMethod,
            isInitOnly: kind == PublicApiMethodKind.PropertySet && signature.ContainsIsExternalInitModifier);
    }

    private static PublicApiMemberModifiers GetMethodModifiers(MethodAttributes attributes, bool isExplicitInterfaceImplementation, bool requiresUnsafe)
    {
        var isAbstract = attributes.HasFlag(MethodAttributes.Abstract);
        var isVirtual = attributes.HasFlag(MethodAttributes.Virtual);
        var isFinal = attributes.HasFlag(MethodAttributes.Final);
        var isNewSlot = attributes.HasFlag(MethodAttributes.NewSlot);
        return new PublicApiMemberModifiers(
            IsStatic: attributes.HasFlag(MethodAttributes.Static),
            IsAbstract: isAbstract,
            IsVirtual: isVirtual && !isFinal && isNewSlot && !isAbstract,
            IsOverride: isVirtual && !isNewSlot,
            IsSealed: isVirtual && isFinal && !isNewSlot && !isAbstract,
            RequiresUnsafe: requiresUnsafe,
            IsExplicitInterfaceImplementation: isExplicitInterfaceImplementation);
    }

    private ImmutableArray<PublicApiParameter> ReadParameters(TypeDefinitionHandle declaringTypeHandle, MethodDefinitionHandle methodHandle, MethodDefinition method, ImmutableArray<RawType> parameterTypes, bool isExtensionMethod)
    {
        if (parameterTypes.IsEmpty)
            return [];

        var parametersBySequence = new Dictionary<int, ParameterHandle>();
        foreach (var parameterHandle in method.GetParameters())
        {
            parametersBySequence.TryAdd(_metadataReader.GetParameter(parameterHandle).SequenceNumber, parameterHandle);
        }

        var result = ImmutableArray.CreateBuilder<PublicApiParameter>(parameterTypes.Length);
        for (var i = 0; i < parameterTypes.Length; i++)
        {
            string? name = null;
            CustomAttributeHandleCollection? customAttributes = null;
            var parameterAttributes = default(ParameterAttributes);
            var hasDefaultValue = false;
            object? defaultValue = null;
            if (parametersBySequence.TryGetValue(i + 1, out var parameterHandle))
            {
                var parameter = _metadataReader.GetParameter(parameterHandle);
                name = parameter.Name.IsNil ? null : _metadataReader.GetString(parameter.Name);
                parameterAttributes = parameter.Attributes;
                customAttributes = parameter.GetCustomAttributes();
                if (parameter.Attributes.HasFlag(ParameterAttributes.HasDefault) && !parameter.GetDefaultValue().IsNil)
                {
                    hasDefaultValue = true;
                    defaultValue = DecodeConstantValue(_metadataReader.GetConstant(parameter.GetDefaultValue()));
                }
            }

            var rawType = parameterTypes[i];
            var refKind = PublicApiRefKind.None;
            if (rawType is RawType.ByReference byReference)
            {
                var elementType = byReference.ElementType;
                if (parameterAttributes.HasFlag(ParameterAttributes.Out))
                {
                    refKind = PublicApiRefKind.Out;
                }
                else if (HasAttribute(customAttributes, "System.Runtime.CompilerServices.RequiresLocationAttribute") || byReference.HasRequiresLocationModifier || elementType.HasRequiresLocationModifier)
                {
                    refKind = PublicApiRefKind.RefReadOnly;
                }
                else if (HasAttribute(customAttributes, "System.Runtime.InteropServices.InAttribute") ||
                         HasAttribute(customAttributes, IsReadOnlyAttributeFullName) ||
                         byReference.HasInModifier || elementType.HasInModifier ||
                         byReference.HasIsReadOnlyModifier || elementType.HasIsReadOnlyModifier)
                {
                    refKind = PublicApiRefKind.In;
                }
                else
                {
                    refKind = PublicApiRefKind.Ref;
                }

                rawType = elementType;
            }

            var nullableInfo = GetNullableMetadataInfo(declaringTypeHandle, customAttributes, methodHandle);
            var type = TypeReferenceBuilder.Build(rawType, nullableInfo, GetTupleElementNames(customAttributes));
            result.Add(new PublicApiParameter(
                name,
                i,
                type,
                refKind,
                customAttributes is null ? [] : ReadAttributes(customAttributes.Value),
                isParams: HasAttribute(customAttributes, "System.ParamArrayAttribute"),
                isParamsCollection: HasAttribute(customAttributes, "System.Runtime.CompilerServices.ParamCollectionAttribute"),
                isScoped: HasAttribute(customAttributes, "System.Runtime.CompilerServices.ScopedRefAttribute"),
                isThis: isExtensionMethod && i == 0,
                isOptional: parameterAttributes.HasFlag(ParameterAttributes.Optional),
                hasDefaultValue,
                defaultValue,
                hasOutAttribute: parameterAttributes.HasFlag(ParameterAttributes.Out)));
        }

        return result.MoveToImmutable();
    }

    private bool IsReadOnlyMember(TypeDefinition declaringType, CustomAttributeHandleCollection customAttributes)
    {
        // Members of a readonly struct are implicitly readonly and carry no attribute, so this only matches per-member readonly
        if ((declaringType.Attributes & TypeAttributes.ClassSemanticsMask) == TypeAttributes.Interface)
            return false;

        if (!string.Equals(GetTypeFullName(declaringType.BaseType), "System.ValueType", StringComparison.Ordinal))
            return false;

        return HasAttribute(customAttributes, IsReadOnlyAttributeFullName);
    }

    private static int GetAccessibilityRank(MethodAttributes attributes)
    {
        return (attributes & MethodAttributes.MemberAccessMask) switch
        {
            MethodAttributes.Public => 6,
            MethodAttributes.FamORAssem => 5,
            MethodAttributes.Family => 4,
            MethodAttributes.Assembly => 3,
            MethodAttributes.FamANDAssem => 2,
            MethodAttributes.Private => 1,
            _ => 0,
        };
    }

    private CustomAttributeHandleCollection? GetParameterCustomAttributes(MethodDefinition method, int sequenceNumber)
    {
        foreach (var parameterHandle in method.GetParameters())
        {
            var parameter = _metadataReader.GetParameter(parameterHandle);
            if (parameter.SequenceNumber == sequenceNumber)
                return parameter.GetCustomAttributes();
        }

        return null;
    }

    private (MethodSignature<RawType> Signature, bool ContainsIsExternalInitModifier) DecodeMethodSignature(TypeDefinitionHandle declaringTypeHandle, MethodDefinitionHandle methodHandle, MethodDefinition method)
    {
        _typeProvider.ContainsIsExternalInitModifier = false;
        var signature = method.DecodeSignature(_typeProvider, BuildGenericContext(declaringTypeHandle, methodHandle));
        return (signature, _typeProvider.ContainsIsExternalInitModifier);
    }

    private Dictionary<MethodDefinitionHandle, List<EntityHandle>> BuildMethodImplementationMap(TypeDefinition typeDefinition)
    {
        var result = new Dictionary<MethodDefinitionHandle, List<EntityHandle>>();
        foreach (var methodImplementationHandle in typeDefinition.GetMethodImplementations())
        {
            var methodImplementation = _metadataReader.GetMethodImplementation(methodImplementationHandle);
            if (methodImplementation.MethodBody.Kind != HandleKind.MethodDefinition)
                continue;

            var body = (MethodDefinitionHandle)methodImplementation.MethodBody;
            if (!result.TryGetValue(body, out var declarations))
            {
                declarations = [];
                result.Add(body, declarations);
            }

            declarations.Add(methodImplementation.MethodDeclaration);
        }

        return result;
    }

    private PublicApiMemberReference? CreateExplicitMethodReference(TypeDefinitionHandle implementingTypeHandle, EntityHandle declaration)
    {
        if (!TryDecodeMethodDeclaration(implementingTypeHandle, declaration, out var containingType, out var name, out var signature))
            return null;

        var documentationId = DocumentationIdBuilder.GetMethodDocumentationId(
            DocumentationIdBuilder.GetTypeDefinitionName(containingType),
            name,
            signature.GenericParameterCount,
            [.. signature.ParameterTypes.Select(ToDocumentationParameter)],
            name is "op_Implicit" or "op_Explicit" or "op_CheckedExplicit" ? ToDocumentationType(signature.ReturnType) : null);
        return new PublicApiMemberReference(PublicApiSymbolKind.Method, containingType, name, documentationId);
    }

    private PublicApiMemberReference? CreateExplicitPropertyOrEventReference(TypeDefinitionHandle implementingTypeHandle, EntityHandle accessorDeclaration, PublicApiSymbolKind kind, bool removeLastParameter)
    {
        if (!TryDecodeMethodDeclaration(implementingTypeHandle, accessorDeclaration, out var containingType, out var accessorName, out var signature))
            return null;

        var separatorIndex = accessorName.IndexOf('_', StringComparison.Ordinal);
        if (separatorIndex < 0)
            return null;

        var name = accessorName[(separatorIndex + 1)..];
        var parameterTypes = signature.ParameterTypes;
        if (kind == PublicApiSymbolKind.Event)
        {
            parameterTypes = [];
        }
        else if (removeLastParameter && !parameterTypes.IsEmpty)
        {
            parameterTypes = parameterTypes.RemoveAt(parameterTypes.Length - 1);
        }

        var prefix = kind == PublicApiSymbolKind.Event ? "E:" : "P:";
        var documentationId = prefix + DocumentationIdBuilder.GetTypeDefinitionName(containingType) + "." + DocumentationIdBuilder.EscapeMemberName(name) + DocumentationIdBuilder.GetParameterList([.. parameterTypes.Select(ToDocumentationParameter)]);
        return new PublicApiMemberReference(kind, containingType, name, documentationId);
    }

    private bool TryDecodeMethodDeclaration(TypeDefinitionHandle implementingTypeHandle, EntityHandle declaration, out PublicApiNamedTypeReference containingType, out string name, out MethodSignature<RawType> signature)
    {
        switch (declaration.Kind)
        {
            case HandleKind.MemberReference:
                {
                    var memberReference = _metadataReader.GetMemberReference((MemberReferenceHandle)declaration);
                    if (memberReference.GetKind() != MemberReferenceKind.Method ||
                        TypeReferenceBuilder.Build(DecodeTypeFromEntityHandle(memberReference.Parent, BuildGenericContext(implementingTypeHandle))) is not PublicApiNamedTypeReference parent)
                    {
                        break;
                    }

                    containingType = parent;
                    name = _metadataReader.GetString(memberReference.Name);

                    // The signature refers to the generic parameters of the declaring type definition, whose names are unknown
                    signature = memberReference.DecodeMethodSignature(_typeProvider, default);
                    return true;
                }

            case HandleKind.MethodDefinition:
                {
                    var methodHandle = (MethodDefinitionHandle)declaration;
                    var method = _metadataReader.GetMethodDefinition(methodHandle);
                    var declaringTypeHandle = method.GetDeclaringType();
                    containingType = TypeReferenceBuilder.BuildNamed(_typeProvider.GetTypeFromDefinition(_metadataReader, declaringTypeHandle, IsValueTypeDefinition(declaringTypeHandle)));
                    name = _metadataReader.GetString(method.Name);
                    signature = method.DecodeSignature(_typeProvider, BuildGenericContext(declaringTypeHandle, methodHandle));
                    return true;
                }
        }

        containingType = null!;
        name = string.Empty;
        signature = default;
        return false;
    }

    private static string ToDocumentationParameter(RawType type)
    {
        return type is RawType.ByReference byReference
            ? ToDocumentationType(byReference.ElementType) + "@"
            : ToDocumentationType(type);
    }

    private static string ToDocumentationType(RawType type) => DocumentationIdBuilder.GetTypeName(TypeReferenceBuilder.Build(type));
}
