using System.Collections.Immutable;

namespace Meziantou.Framework.PublicApiGenerator;

/// <summary>A class, struct, interface, enum or delegate that is part of the public API.</summary>
/// <remarks>
/// <para>
/// <see cref="Members"/> contains the fields, properties, events, constructors, methods and operators that are visible outside the assembly
/// (<c>public</c>, <c>protected</c> and <c>protected internal</c>), as well as explicit interface implementations.
/// Members with unspeakable names generated by the compiler (e.g. <c>&lt;Clone&gt;$</c>), static constructors and accessors are not members;
/// accessors are available from their property or event. Other compiler-generated members, such as the members of records,
/// are included and can be identified with <see cref="PublicApiSymbol.IsCompilerGenerated"/>.
/// </para>
/// <para>
/// The members of a delegate are not exposed, except its <c>Invoke</c> method (see <see cref="DelegateInvokeMethod"/>).
/// C# 14 extension blocks are exposed through the static methods the compiler generates for them (e.g. <c>get_Length(string)</c>).
/// </para>
/// </remarks>
public sealed class PublicApiType : PublicApiSymbol
{
    internal PublicApiType(
        string @namespace,
        string metadataName,
        PublicApiAccessibility accessibility,
        ImmutableArray<PublicApiAttribute> attributes,
        PublicApiMetadataOrigin? origin,
        PublicApiTypeKind typeKind,
        PublicApiTypeFlags flags,
        ImmutableArray<PublicApiGenericParameter> allGenericParameters,
        int genericParameterCount,
        PublicApiTypeReference? baseType,
        ImmutableArray<PublicApiTypeReference> interfaces,
        ImmutableArray<PublicApiMember> members,
        ImmutableArray<PublicApiType> nestedTypes,
        PublicApiMethod? delegateInvokeMethod,
        PublicApiNamedTypeReference? enumUnderlyingType,
        ImmutableArray<PublicApiTypeReference> unionCaseTypes)
        : base(MetadataNameHelper.RemoveGenericArity(metadataName), accessibility, attributes, origin)
    {
        Namespace = @namespace;
        MetadataName = metadataName;
        TypeKind = typeKind;
        IsStatic = flags.IsStatic;
        IsAbstract = flags.IsAbstract;
        IsSealed = flags.IsSealed;
        IsReadOnly = flags.IsReadOnly;
        IsRefLike = flags.IsRefLike;
        IsClosed = flags.IsClosed;
        IsUnion = flags.IsUnion;
        GenericParameters = allGenericParameters[^genericParameterCount..];
        BaseType = baseType;
        Interfaces = interfaces;
        Members = members;
        NestedTypes = nestedTypes;
        DelegateInvokeMethod = delegateInvokeMethod;
        EnumUnderlyingType = enumUnderlyingType;
        UnionCaseTypes = unionCaseTypes;
    }

    public override PublicApiSymbolKind Kind => PublicApiSymbolKind.Type;

    /// <summary>Gets the namespace of the type. Nested types have the namespace of their top-level containing type.</summary>
    public string Namespace { get; }

    /// <summary>Gets the name of the type including the generic arity suffix (e.g. <c>List`1</c>).</summary>
    public override string MetadataName { get; }

    /// <summary>Gets the metadata full name of the type, using <c>+</c> to separate nested types (e.g. <c>System.Collections.Generic.Dictionary`2+Enumerator</c>).</summary>
    public string FullName => DeclaringType is null
        ? (Namespace.Length == 0 ? MetadataName : Namespace + "." + MetadataName)
        : DeclaringType.FullName + "+" + MetadataName;

    public PublicApiTypeKind TypeKind { get; }

    /// <summary>Gets a value indicating whether the type is a static class.</summary>
    public bool IsStatic { get; }

    /// <summary>Gets a value indicating whether the class is abstract. Interfaces and static classes are not reported as abstract.</summary>
    public bool IsAbstract { get; }

    /// <summary>Gets a value indicating whether the class is sealed. Structs, enums, delegates and static classes are not reported as sealed.</summary>
    public bool IsSealed { get; }

    /// <summary>Gets a value indicating whether the struct is a <c>readonly struct</c>.</summary>
    public bool IsReadOnly { get; }

    /// <summary>Gets a value indicating whether the struct is a <c>ref struct</c>.</summary>
    public bool IsRefLike { get; }

    /// <summary>Gets a value indicating whether the class is a <c>closed</c> class.</summary>
    public bool IsClosed { get; }

    /// <summary>Gets a value indicating whether the struct is a C# <c>union</c> declaration. See <see cref="UnionCaseTypes"/>.</summary>
    public bool IsUnion { get; }

    /// <summary>Gets the generic parameters declared by this type. Nested types do not repeat the generic parameters of their containing types.</summary>
    public ImmutableArray<PublicApiGenericParameter> GenericParameters { get; }

    public bool IsGenericType => !GenericParameters.IsEmpty;

    /// <summary>Gets the base class. It is <see langword="null"/> for interfaces, and for <c>System.Object</c>.</summary>
    public PublicApiTypeReference? BaseType { get; }

    /// <summary>Gets the interfaces directly implemented by the type, sorted by documentation ID. Interfaces that are not visible outside the assembly are not included.</summary>
    public ImmutableArray<PublicApiTypeReference> Interfaces { get; }

    /// <summary>Gets the members of the type, in metadata order: fields, properties, events, then methods.</summary>
    public ImmutableArray<PublicApiMember> Members { get; }

    /// <summary>Gets the nested types, sorted by metadata name.</summary>
    public ImmutableArray<PublicApiType> NestedTypes { get; }

    /// <summary>Gets the <c>Invoke</c> method of a delegate type, which describes its signature.</summary>
    public PublicApiMethod? DelegateInvokeMethod { get; }

    /// <summary>Gets the underlying type of an enum.</summary>
    public PublicApiNamedTypeReference? EnumUnderlyingType { get; }

    /// <summary>Gets the case types of a C# <c>union</c> declaration.</summary>
    public ImmutableArray<PublicApiTypeReference> UnionCaseTypes { get; }

    /// <summary>Enumerates the type and all its nested types, recursively.</summary>
    public IEnumerable<PublicApiType> GetTypeAndNestedTypes()
    {
        yield return this;
        foreach (var nestedType in NestedTypes)
        {
            foreach (var type in nestedType.GetTypeAndNestedTypes())
            {
                yield return type;
            }
        }
    }
}
