using System.Buffers.Binary;
using GifFrameData = Meziantou.Framework.SnapshotTesting.Tests.ImageTestData.GifFrameData;

namespace Meziantou.Framework.SnapshotTesting.Tests;

public sealed class ImageLoaderTests
{
    private static readonly Argb White = new(0xFFFFFFFFu);
    private static readonly Argb Black = new(0xFF000000u);

    [Fact]
    public async Task Image_LoadAsync_ThrowsWhenFormatIsNotSupported()
    {
        var ex = await Assert.ThrowsAsync<NotSupportedException>(() => Image.LoadAsync(new MemoryStream("not-a-bmp"u8.ToArray())));
        Assert.Contains("Only BMP, PNG, JPEG, and TIFF are currently supported.", ex.Message);
    }

    [Fact]
    public void GifImageLoader_AppendsTheFirstPixelOfTheCodeThatIsNotInTheTableYet()
    {
        // 4 clears the table, then 0, 1 and 6 ("01") build it up. 8 is not in the table yet: it stands for the
        // previous string followed by that string's own first pixel, so "01" + "0". Pillow decodes the same.
        var gif = CreateBlackAndWhiteGif(width: 7, height: 1, new GifFrameData(0, 0, 7, 1, []) { LzwCodes = [4, 0, 1, 6, 8, 5] });

        var frame = Assert.Single(ExtractGifFrames(gif));

        Assert.Equal([White, Black, White, Black, White, Black, White], frame.Pixels.ToArray());
    }

    [Theory]
    [InlineData("gif-checkerboard")]
    [InlineData("gif-interlaced")]
    public async Task GifImageLoader_FramesMatchPillow(string scenario)
    {
        // Generated by Pillow. gif-checkerboard: a 1-pixel checkerboard, which makes the encoder emit many codes
        // that are not in the table yet, then a frame with up to 256 colors. gif-interlaced: two interlaced
        // frames, the second one a sub-rectangle whose height is not a multiple of 8. The PNG files are Pillow's
        // decoding of each frame.
        var frames = ExtractGifFrames(ImageTestData.ReadImageFixture(scenario + ".gif"));

        Assert.HasCount(2, frames);
        for (var i = 0; i < frames.Count; i++)
        {
            var expected = await ImageTestData.LoadImageFixtureAsync(scenario + "." + i.ToString(CultureInfo.InvariantCulture) + ".from-gif.png");
            Assert.Equal(expected.Pixels.ToArray(), frames[i].Pixels.ToArray());
        }
    }

    [Fact]
    public void GifImageLoader_IgnoresDataAfterTheTrailer()
    {
        var gif = CreateBlackAndWhiteGif(width: 2, height: 1, new GifFrameData(0, 0, 2, 1, [0, 1]));

        var frame = Assert.Single(ExtractGifFrames([.. gif, 0x00]));

        Assert.Equal([White, Black], frame.Pixels.ToArray());
    }

    [Fact]
    public void GifImageLoader_AcceptsAMissingTrailer()
    {
        var gif = CreateBlackAndWhiteGif(width: 2, height: 1, new GifFrameData(0, 0, 2, 1, [0, 1]));
        Assert.Equal(0x3B, gif[^1]);

        var frame = Assert.Single(ExtractGifFrames(gif[..^1]));

        Assert.Equal([White, Black], frame.Pixels.ToArray());
    }

    [Fact]
    public void GifImageLoader_DecodesAPaletteIndexBeyondTheColorTableAsBlack()
    {
        // The color table has 2 entries while the 2-bit codes can express 4 indexes. Pillow renders them black.
        var gif = ImageTestData.CreateGif(
            width: 3,
            height: 1,
            colorTable: [0xFFFFFFu, 0xFF0000u],
            backgroundColorIndex: 0,
            new GifFrameData(0, 0, 3, 1, [1, 2, 3]));

        var frame = Assert.Single(ExtractGifFrames(gif));

        Assert.Equal([new Argb(0xFFFF0000u), Black, Black], frame.Pixels.ToArray());
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void GifImageLoader_KeepsTheCanvasWhereTheFrameDataEndsEarly(bool hasEndCode)
    {
        // The second frame only encodes its first pixel. Browsers draw what was decoded and leave the rest of the
        // canvas as the previous frame left it.
        var gif = CreateBlackAndWhiteGif(
            width: 2,
            height: 2,
            new GifFrameData(0, 0, 2, 2, [0, 0, 0, 0]),
            new GifFrameData(0, 0, 2, 2, []) { LzwCodes = hasEndCode ? [4, 1, 5] : [4, 1] });

        var frames = ExtractGifFrames(gif);

        Assert.HasCount(2, frames);
        Assert.Equal([Black, White, White, White], frames[1].Pixels.ToArray());
    }

    [Theory]
    [InlineData(65535, 65535, 1, 1)]
    [InlineData(20000, 20000, 1, 1)]
    [InlineData(1, 1, 65535, 65535)]
    public void GifImageLoader_RejectsDimensionsBeyondTheLimit(int logicalWidth, int logicalHeight, int frameWidth, int frameHeight)
    {
        var gif = CreateBlackAndWhiteGif(logicalWidth, logicalHeight, new GifFrameData(0, 0, 1, 1, [0]));

        // Header (13 bytes), 2-color table (6 bytes), graphic control extension (8 bytes), then the image
        // separator followed by left, top, width and height.
        Assert.Equal(0x2C, gif[27]);
        BinaryPrimitives.WriteUInt16LittleEndian(gif.AsSpan(32), (ushort)frameWidth);
        BinaryPrimitives.WriteUInt16LittleEndian(gif.AsSpan(34), (ushort)frameHeight);

        Assert.False(GifImageLoader.TryExtractFrames(gif, out _));
    }

    [Fact]
    public void GifImageLoader_ClipsAnInterlacedFrameToTheLogicalScreen()
    {
        // A 3x5 frame at (1, 1) on a 3x3 screen: only the first two columns of its first two rows are visible.
        // The rows are coded in the order 0, 4, 2, 1, 3, so a wrong row mapping draws the black row 4.
        var gif = CreateBlackAndWhiteGif(
            width: 3,
            height: 3,
            new GifFrameData(1, 1, 3, 5, [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]) { Interlaced = true });

        var frame = Assert.Single(ExtractGifFrames(gif));

        Assert.Equal([White, White, White, White, Black, White, White, White, Black], frame.Pixels.ToArray());
    }

    [Fact]
    public void GifImageLoader_OnlyDecodesThePartOfAFrameThatLandsOnTheScreen()
    {
        // Frames of 256 million pixels over a 1x16000 screen, one of them entirely off screen. Decoding them in
        // full allocates every pixel of every frame and visits every column of every row on the screen, which
        // takes seconds for a file of a few hundred bytes.
        var gif = CreateBlackAndWhiteGif(
            width: 1,
            height: 16000,
            new GifFrameData(0, 0, 16000, 16000, []) { LzwCodes = [4, 1, 5] },
            new GifFrameData(0, 0, 16000, 16000, []) { LzwCodes = [4, 0, 5], Interlaced = true },
            new GifFrameData(1, 0, 16000, 16000, []) { LzwCodes = [4, 1, 5] });

        var allocatedBefore = GC.GetAllocatedBytesForCurrentThread();
        var frames = ExtractGifFrames(gif);
        var allocated = GC.GetAllocatedBytesForCurrentThread() - allocatedBefore;

        Assert.Equal([Black, White, White], frames.Select(frame => frame.Pixels.Span[0]).ToArray());
        Assert.True(allocated < 1024 * 1024, $"Extracting the frames allocated {allocated} bytes.");
    }

    [Fact]
    public void IcoImageLoader_Uses32BitAlphaInsteadOfTheAndMask()
    {
        // The AND mask marks the first pixel as transparent, but its alpha channel says half transparent. Windows
        // and Pillow keep the alpha channel.
        var ico = CreateIcoWithBitmapEntry(entrySize: 2, width: 2, height: 1, xorData: [10, 20, 30, 128, 40, 50, 60, 255], andMask: [0x80, 0, 0, 0]);

        var image = Assert.Single(ExtractIcoImages(ico));

        Assert.Equal([new Argb(128, 30, 20, 10), new Argb(255, 60, 50, 40)], image.Pixels.ToArray());
    }

    [Fact]
    public void IcoImageLoader_UsesTheAndMaskWhen32BitAlphaIsAllZero()
    {
        var ico = CreateIcoWithBitmapEntry(entrySize: 2, width: 2, height: 1, xorData: [10, 20, 30, 0, 40, 50, 60, 0], andMask: [0x80, 0, 0, 0]);

        var image = Assert.Single(ExtractIcoImages(ico));

        Assert.Equal([new Argb(0u), new Argb(255, 60, 50, 40)], image.Pixels.ToArray());
    }

    [Fact]
    public void IcoImageLoader_TakesTheSizeFromTheBitmapHeaderRatherThanTheDirectoryEntry()
    {
        // Pillow warns that the image is not the expected size and decodes it anyway
        var ico = CreateIcoWithBitmapEntry(entrySize: 16, width: 2, height: 1, xorData: [10, 20, 30, 255, 40, 50, 60, 255], andMask: [0, 0, 0, 0]);

        var image = Assert.Single(ExtractIcoImages(ico));

        Assert.Equal(2, image.Width);
        Assert.Equal(1, image.Height);
    }

    [Theory]
    [InlineData(0x80000000u)]
    [InlineData(0x40000001u)]
    public void IcoImageLoader_RejectsAPaletteLargerThanTheData(uint colorsUsed)
    {
        Assert.True(IcoImageLoader.TryExtractImages(CreateIco(colorsUsed: 0), out _));
        Assert.False(IcoImageLoader.TryExtractImages(CreateIco(colorsUsed), out _));

        static byte[] CreateIco(uint colorsUsed)
        {
            return CreateIcoWithBitmapEntry(entrySize: 1, width: 1, height: 1, bitsPerPixel: 8, xorData: [0, 0, 0, 0], andMask: [0, 0, 0, 0], palette: new byte[256 * 4], colorsUsed: colorsUsed);
        }
    }

    [Fact]
    public void IcoImageLoader_RejectsACorruptPngEntry()
    {
        // The PNG signature followed by a chunk whose length exceeds the data
        byte[] png = [0x89, (byte)'P', (byte)'N', (byte)'G', 0x0D, 0x0A, 0x1A, 0x0A, 0xFF, 0xFF, 0xFF, 0xFF, (byte)'I', (byte)'H', (byte)'D', (byte)'R'];
        var ico = ImageTestData.CreateIcoWithPngEntries(png);

        Assert.False(IcoImageLoader.TryExtractImages(ico, out _));
    }

    private static List<Image> ExtractGifFrames(byte[] gif)
    {
        Assert.True(GifImageLoader.TryExtractFrames(gif, out var frames));
        return frames;
    }

    private static List<Image> ExtractIcoImages(byte[] ico)
    {
        Assert.True(IcoImageLoader.TryExtractImages(ico, out var images));
        return images;
    }

    private static byte[] CreateBlackAndWhiteGif(int width, int height, params GifFrameData[] frames)
    {
        return ImageTestData.CreateGif(width, height, colorTable: [0xFFFFFFu, 0x000000u], backgroundColorIndex: 0, frames);
    }

    private static byte[] CreateIcoWithBitmapEntry(int entrySize, int width, int height, byte[] xorData, byte[] andMask, int bitsPerPixel = 32, byte[]? palette = null, uint colorsUsed = 0)
    {
        const int DirectorySize = 6 + 16;
        const int BitmapHeaderSize = 40;

        palette ??= [];
        var imageSize = BitmapHeaderSize + palette.Length + xorData.Length + andMask.Length;
        var data = new byte[DirectorySize + imageSize];
        var span = data.AsSpan();

        BinaryPrimitives.WriteUInt16LittleEndian(span[2..], 1); // Type: icon
        BinaryPrimitives.WriteUInt16LittleEndian(span[4..], 1); // Image count
        data[6] = (byte)entrySize;
        data[7] = (byte)entrySize;
        BinaryPrimitives.WriteUInt16LittleEndian(span[10..], 1); // Planes
        BinaryPrimitives.WriteUInt16LittleEndian(span[12..], (ushort)bitsPerPixel);
        BinaryPrimitives.WriteUInt32LittleEndian(span[14..], (uint)imageSize);
        BinaryPrimitives.WriteUInt32LittleEndian(span[18..], DirectorySize);

        var header = span[DirectorySize..];
        BinaryPrimitives.WriteInt32LittleEndian(header, BitmapHeaderSize);
        BinaryPrimitives.WriteInt32LittleEndian(header[4..], width);
        BinaryPrimitives.WriteInt32LittleEndian(header[8..], height * 2); // The XOR image and the AND mask
        BinaryPrimitives.WriteUInt16LittleEndian(header[12..], 1); // Planes
        BinaryPrimitives.WriteUInt16LittleEndian(header[14..], (ushort)bitsPerPixel);
        BinaryPrimitives.WriteUInt32LittleEndian(header[32..], colorsUsed);

        palette.CopyTo(header[BitmapHeaderSize..]);
        xorData.CopyTo(header[(BitmapHeaderSize + palette.Length)..]);
        andMask.CopyTo(header[(BitmapHeaderSize + palette.Length + xorData.Length)..]);
        return data;
    }

    // The expected scores come from scikit-image 0.24:
    //   color = structural_similarity(premultiplied_rgb_expected, premultiplied_rgb_actual, data_range=255, channel_axis=-1)
    //   alpha = structural_similarity(alpha_expected, alpha_actual, data_range=255)
    //   score = min(color, alpha)
    // where the RGB channels are premultiplied as (value × alpha + 127) // 255, on the images built by CreateReferenceImages.
    [Theory]
    [InlineData("TexturedWithRedBlock", 0.9605711225224126)]
    [InlineData("TranslucentAlphaShift", 0.5393716414539776)]
    [InlineData("WhiteWithBlackSquare", 0.9891674563063622)]
    [InlineData("ScreenshotWithErrorBanner", 0.9932801453262927)]
    [InlineData("OpaqueVersusTransparentRed", 9.99900009999e-05)]
    public void SsimAccumulator_MatchesScikitImage(string name, double expectedScore)
    {
        var (width, height, expected, actual) = CreateReferenceImages(name);

        Assert.Equal(expectedScore, SsimAccumulator.Compute(expected, actual, width, height), tolerance: 1e-9);
    }

    [Fact]
    public void SsimAccumulator_LocalizedDifferenceLowersTheScoreInProportionToItsArea()
    {
        // A single SSIM over the whole image scores this pair 0.087: the black square dominates the global
        // variance even though it covers less than 1% of the image.
        var (width, height, expected, actual) = CreateReferenceImages("WhiteWithBlackSquare");

        Assert.InRange(SsimAccumulator.Compute(expected, actual, width, height), 0.98, 0.99);
    }

    [Theory]
    [InlineData(1, 1)]
    [InlineData(5, 3)]
    [InlineData(7, 7)]
    [InlineData(8, 9)]
    [InlineData(13, 4)]
    [InlineData(2, 40)]
    [InlineData(31, 17)]
    public void SsimAccumulator_MatchesABruteForceComputation(int width, int height)
    {
        // Covers images smaller than the window in either direction, where the window shrinks to the image
        var (expected, actual) = CreateRandomPixels(width * height);

        Assert.Equal(ComputeReferenceSsim(expected, actual, width, height), SsimAccumulator.Compute(expected, actual, width, height), tolerance: 1e-12);
    }

    [Fact]
    public void SsimAccumulator_IdenticalPixelsScoreExactlyOne()
    {
        var (pixels, _) = CreateRandomPixels(37 * 23);

        Assert.Equal(1d, SsimAccumulator.Compute(pixels, pixels, 37, 23));
    }

    [Fact]
    public void SsimAccumulator_TransparentPixelsScoreTheSameWhateverColorTheyHide()
    {
        var (expected, actual) = CreateRandomPixels(20 * 10);
        for (var i = 0; i < expected.Length; i++)
        {
            expected[i] &= 0x00FFFFFFu;
            actual[i] &= 0x00FFFFFFu;
        }

        Assert.Equal(1d, SsimAccumulator.Compute(expected, actual, 20, 10));
    }

    [Fact]
    public void SsimAccumulator_RequiresAllTheRows()
    {
        var accumulator = new SsimAccumulator(4, 2);
        accumulator.AddRow(new uint[4], new uint[4]);

        Assert.Throws<InvalidOperationException>(() => accumulator.ComputeMeanSsim());
        Assert.Throws<ArgumentException>(() => accumulator.AddRow(new uint[3], new uint[4]));
    }

    internal static (int Width, int Height, uint[] Expected, uint[] Actual) CreateReferenceImages(string name)
    {
        switch (name)
        {
            case "TexturedWithRedBlock":
            {
                var expected = CreatePattern(64, 48, static (_, _) => 255);
                var actual = (uint[])expected.Clone();
                for (var y = 0; y < 48; y++)
                {
                    for (var x = 0; x < 64; x++)
                    {
                        ref var pixel = ref actual[y * 64 + x];
                        if (y is >= 15 and < 21 && x is >= 20 and < 30)
                            pixel = 0xFFFF0000u;

                        var blue = Math.Min(255, (int)(pixel & 0xFF) + x * y % 5);
                        pixel = (pixel & 0xFFFFFF00u) | (uint)blue;
                    }
                }

                return (64, 48, expected, actual);
            }

            case "TranslucentAlphaShift":
                return (40, 30, CreatePattern(40, 30, static (x, y) => (x * 11 + y * 3) % 256), CreatePattern(40, 30, static (x, y) => (x * 11 + y * 3 + 40) % 256));

            case "WhiteWithBlackSquare":
            {
                var expected = CreateFilled(1024, 1024, 0xFFFFFFFFu);
                var actual = (uint[])expected.Clone();
                FillRectangle(actual, 1024, x: 462, y: 462, width: 100, height: 100, 0xFF000000u);
                return (1024, 1024, expected, actual);
            }

            case "ScreenshotWithErrorBanner":
            {
                var expected = CreateFilled(1280, 720, 0xFFFFFFFFu);
                for (var y = 0; y < 720; y++)
                {
                    for (var x = 41; x < 1240; x++)
                    {
                        if (y % 24 < 12 && x % 9 < 5)
                            expected[y * 1280 + x] = 0xFF3C3C3Cu;
                    }
                }

                var actual = (uint[])expected.Clone();
                FillRectangle(actual, 1280, x: 560, y: 340, width: 160, height: 40, 0xFFDC1E1Eu);
                return (1280, 720, expected, actual);
            }

            case "OpaqueVersusTransparentRed":
                return (16, 16, CreateFilled(16, 16, 0xFFFF0000u), CreateFilled(16, 16, 0x00FF0000u));

            default:
                throw new ArgumentOutOfRangeException(nameof(name), name, message: null);
        }

        static uint[] CreatePattern(int width, int height, Func<int, int, int> alpha)
        {
            var pixels = new uint[width * height];
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    var red = (x * 17 + y * 31 + x * y * 3) % 256;
                    var green = (x * 7 + y * 13) % 256;
                    var blue = (x * x + y * 5) % 256;
                    pixels[y * width + x] = (uint)alpha(x, y) << 24 | (uint)red << 16 | (uint)green << 8 | (uint)blue;
                }
            }

            return pixels;
        }

        static uint[] CreateFilled(int width, int height, uint color)
        {
            var pixels = new uint[width * height];
            pixels.AsSpan().Fill(color);
            return pixels;
        }

        static void FillRectangle(uint[] pixels, int imageWidth, int x, int y, int width, int height, uint color)
        {
            for (var row = y; row < y + height; row++)
            {
                pixels.AsSpan(row * imageWidth + x, width).Fill(color);
            }
        }
    }

    [SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "Generating test pixels, and the fixed seed keeps the score reproducible.")]
    private static (uint[] Expected, uint[] Actual) CreateRandomPixels(int pixelCount)
    {
        var random = new Random(42);
        var expected = new uint[pixelCount];
        var actual = new uint[pixelCount];
        for (var i = 0; i < pixelCount; i++)
        {
            expected[i] = (uint)random.Next() | (random.Next(2) is 0 ? 0xFF000000u : 0);
            // Mostly identical, so the score lands in the range a caller would actually set a threshold in
            actual[i] = random.Next(5) is 0 ? (uint)random.Next() : expected[i];
        }

        return (expected, actual);
    }

    /// <summary>
    /// Computes the score straight from its definition: every window is summed from scratch, in floating point.
    /// </summary>
    private static double ComputeReferenceSsim(uint[] expected, uint[] actual, int width, int height)
    {
        const double C1 = 0.01 * 255 * 0.01 * 255;
        const double C2 = 0.03 * 255 * 0.03 * 255;

        var windowWidth = Math.Min(7, width);
        var windowHeight = Math.Min(7, height);
        var count = windowWidth * windowHeight;
        var channelSums = new double[4];
        var windowCount = 0;
        for (var top = 0; top + windowHeight <= height; top++)
        {
            for (var left = 0; left + windowWidth <= width; left++)
            {
                for (var channel = 0; channel < 4; channel++)
                {
                    double sumExpected = 0, sumActual = 0, sumExpectedSquared = 0, sumActualSquared = 0, sumCross = 0;
                    for (var y = top; y < top + windowHeight; y++)
                    {
                        for (var x = left; x < left + windowWidth; x++)
                        {
                            var e = GetChannel(expected[y * width + x], channel);
                            var a = GetChannel(actual[y * width + x], channel);
                            sumExpected += e;
                            sumActual += a;
                            sumExpectedSquared += e * e;
                            sumActualSquared += a * a;
                            sumCross += e * a;
                        }
                    }

                    var expectedMean = sumExpected / count;
                    var actualMean = sumActual / count;
                    var normalization = count > 1 ? count - 1 : 1;
                    var expectedVariance = (sumExpectedSquared - count * expectedMean * expectedMean) / normalization;
                    var actualVariance = (sumActualSquared - count * actualMean * actualMean) / normalization;
                    var covariance = (sumCross - count * expectedMean * actualMean) / normalization;
                    channelSums[channel] += (2 * expectedMean * actualMean + C1) * (2 * covariance + C2)
                        / ((expectedMean * expectedMean + actualMean * actualMean + C1) * (expectedVariance + actualVariance + C2));
                }

                windowCount++;
            }
        }

        var color = (channelSums[0] + channelSums[1] + channelSums[2]) / (3 * windowCount);
        var alpha = channelSums[3] / windowCount;
        return Math.Min(color, alpha);

        static double GetChannel(uint pixel, int channel)
        {
            var alpha = pixel >> 24;
            if (channel is 3)
                return alpha;

            var value = (pixel >> (channel * 8)) & 0xFF;
            return (value * alpha + 127) / 255;
        }
    }
}
