<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.Globbing/Meziantou.Framework.Globbing.csproj" />
    <ProjectReference Include="../../src/Meziantou.Framework.TemporaryDirectory/Meziantou.Framework.TemporaryDirectory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="files/*" />
    <EmbeddedResource Include="files/*-conformance.*">
      <LogicalName>%(FileName)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
