namespace Meziantou.Framework.SnapshotTesting;

/// <summary>Provides global configuration for snapshot testing, including source path resolution for
/// deterministic builds.</summary>
public static class SnapshotConfiguration
{
    /// <summary>Registers the source root mappings from the MSBuild <c>$(PathMap)</c> property so that
    /// <c>[CallerFilePath]</c> values emitted by the Roslyn deterministic-build path map can be resolved
    /// back to real paths on disk.
    /// <para>
    /// The format is a comma-separated list of <c>realPath=mappedPrefix</c> pairs, e.g.
    /// <c>/home/runner/work/Repo/=/_/,/home/runner/.nuget/packages/=/_1/,</c>.
    /// </para>
    /// <para>
    /// This is called automatically via a <c>[ModuleInitializer]</c> generated by the NuGet package's
    /// MSBuild props file when deterministic builds are active. You only need to call this manually when
    /// the MSBuild props file is not imported (e.g. in projects that use <c>ProjectReference</c> without
    /// explicitly importing the props file).
    /// </para></summary>
    public static void RegisterPathMap(string pathMap)
    {
        SnapshotCallerContext.RegisterPathMap(pathMap);
    }

    /// <summary>Registers a single source root mapping so that a deterministic build path prefix
    /// (e.g. <c>/_/</c>) can be resolved back to the real path on disk.
    /// This is called automatically via a <c>[ModuleInitializer]</c> generated by the NuGet package's
    /// MSBuild props file when deterministic builds are active.</summary>
    public static void RegisterSourceRootMapping(string mappedPath, string realPath)
    {
        SnapshotCallerContext.RegisterSourceRootMapping(mappedPath, realPath);
    }
}
