namespace Meziantou.Framework.SnapshotTesting;

/// <summary>Provides global configuration for snapshot testing, including source path resolution for
/// deterministic builds.</summary>
public static class SnapshotConfiguration
{
    /// <summary>Registers a single source root mapping so that a deterministic build path prefix
    /// (e.g. <c>/_/</c>) can be resolved back to the real path on disk.
    /// This is called automatically via a <c>[ModuleInitializer]</c> generated by the NuGet package's
    /// MSBuild props file when deterministic builds are active.</summary>
    public static void RegisterSourceRootMapping(string mappedPath, string realPath)
    {
        Snapshot.RegisterSourceRootMapping(mappedPath, realPath);
    }
}
