<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>2.0.5</Version>
    <Description>Generate compilable C# public API stubs from .NET assemblies.</Description>
    <PackageTags>public-api, api-approval, api-diff, reflection, testing</PackageTags>
  </PropertyGroup>

</Project>
