using System.Text;

namespace Meziantou.Framework.PublicApiGenerator;

internal static class PublicApiEmitter
{
    public static IReadOnlyList<PublicApiGeneratedFile> Generate(PublicApiModel model, PublicApiFileLayout layout)
    {
        return layout switch
        {
            PublicApiFileLayout.SingleFile => [new PublicApiGeneratedFile("PublicApi.g.cs", BuildSingleFile(model))],
            PublicApiFileLayout.OneFilePerNamespace => BuildNamespaceFiles(model),
            PublicApiFileLayout.OneFilePerType => BuildTypeFiles(model),
            _ => throw new ArgumentOutOfRangeException(nameof(layout)),
        };
    }

    private static List<PublicApiGeneratedFile> BuildNamespaceFiles(PublicApiModel model)
    {
        var files = new List<PublicApiGeneratedFile>();
        foreach (var group in model.Types.GroupBy(static type => type.Namespace, StringComparer.Ordinal).OrderBy(static group => group.Key, StringComparer.Ordinal))
        {
            var fileName = string.IsNullOrEmpty(group.Key) ? "GlobalNamespace.g.cs" : SanitizeFileName(group.Key) + ".g.cs";
            files.Add(new PublicApiGeneratedFile(fileName, BuildFileContent(group.Key, group.OrderBy(static type => type.QualifiedName, StringComparer.Ordinal))));
        }

        return files;
    }

    private static List<PublicApiGeneratedFile> BuildTypeFiles(PublicApiModel model)
    {
        var files = new List<PublicApiGeneratedFile>(model.Types.Length);
        foreach (var type in model.Types.OrderBy(static value => value.QualifiedName, StringComparer.Ordinal))
        {
            var fileName = SanitizeFileName(type.QualifiedName) + ".g.cs";
            files.Add(new PublicApiGeneratedFile(fileName, BuildFileContent(type.Namespace, [type])));
        }

        return files;
    }

    private static string BuildSingleFile(PublicApiModel model)
    {
        var sb = CreateFileHeader();
        var groupedTypes = model.Types.GroupBy(static type => type.Namespace, StringComparer.Ordinal).OrderBy(static group => group.Key, StringComparer.Ordinal);
        foreach (var group in groupedTypes)
        {
            AppendNamespace(sb, group.Key, group.OrderBy(static type => type.QualifiedName, StringComparer.Ordinal));
        }

        return sb.ToString();
    }

    private static string BuildFileContent(string namespaceName, IEnumerable<PublicApiTypeModel> types)
    {
        var sb = CreateFileHeader();
        AppendNamespace(sb, namespaceName, types);
        return sb.ToString();
    }

    private static StringBuilder CreateFileHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        return sb;
    }

    private static void AppendNamespace(StringBuilder sb, string namespaceName, IEnumerable<PublicApiTypeModel> types)
    {
        var orderedTypes = types.OrderBy(static type => type.QualifiedName, StringComparer.Ordinal).ToList();
        if (orderedTypes.Count == 0)
            return;

        if (string.IsNullOrEmpty(namespaceName))
        {
            for (var i = 0; i < orderedTypes.Count; i++)
            {
                if (i > 0)
                {
                    sb.AppendLine();
                }

                sb.AppendLine(orderedTypes[i].Source);
            }

            return;
        }

        sb.Append("namespace ");
        sb.AppendLine(namespaceName);
        sb.AppendLine("{");
        for (var i = 0; i < orderedTypes.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }

            AppendIndented(sb, orderedTypes[i].Source, 1);
        }

        sb.AppendLine("}");
    }

    private static void AppendIndented(StringBuilder sb, string text, int indentationLevel)
    {
        using var reader = new StringReader(text);
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            if (line.Length > 0)
            {
                sb.Append(' ', indentationLevel * 4);
            }

            sb.AppendLine(line);
        }
    }

    private static string SanitizeFileName(string value)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            sanitized.Append(invalidChars.Contains(character) ? '_' : character);
        }

        return sanitized.ToString();
    }
}
