<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Description>Syntax highlighting engine for .NET</Description>
    <PackageTags>syntax-highlighting, highlighter, code, html</PackageTags>
    <Version>1.0.4</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Meziantou.Framework.SyntaxHighlighting.Tests" />
  </ItemGroup>

</Project>
