<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <!-- All the tests are skipped on macOS when running on GitHub Actions -->
    <MinimumExpectedTests>0</MinimumExpectedTests>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.NtpClient/Meziantou.Framework.NtpClient.csproj" />
  </ItemGroup>

</Project>
