// <auto-generated />
#nullable enable

using System.Collections.Concurrent;
using System.Runtime.InteropServices;

namespace Meziantou.Framework.Http;

partial class HstsDomainPolicyCollection
{
    private void LoadPreloadDomains()
    {
        // HSTS preload data source: https://raw.githubusercontent.com/chromium/chromium/7a1c43347ca9fbb5e8a2ad57630f43edfe890228/net/http/transport_security_state_static.json
        // Commit date: 2025-09-26T16:04:23.0000000+00:00
        CollectionsMarshal.SetCount(_policies, 4);

        var dict1 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 61, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[0] = dict1;
        Load(dict1, 51, "preload_1.bin");

        var dict2 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 84616, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[1] = dict2;
        Load(dict2, 84606, "preload_2.bin");

        var dict3 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 8384, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[2] = dict3;
        Load(dict3, 8374, "preload_3.bin");

        var dict4 = new ConcurrentDictionary<string, HstsDomainPolicy>(concurrencyLevel: -1, capacity: 161, comparer: StringComparer.OrdinalIgnoreCase);
        _policies[3] = dict4;
        Load(dict4, 151, "preload_4.bin");
    }
}