<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Version>2.0.4</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>robots.txt parser following RFC 9309 with Google path-wildcard extensions</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Meziantou.Framework/StringExtensions.SplitLines.cs" Link="Internals/StringExtensions.SplitLines.cs" />
  </ItemGroup>

</Project>
