using System.CommandLine;
using System.CommandLine.Invocation;
using Meziantou.Framework;
using Meziantou.Framework.PublicApiGenerator;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Meziantou.Framework.PublicApiGenerator.Tests")]

namespace Meziantou.Framework.PublicApiGenerator.Tool;

internal static class Program
{
    public static Task<int> Main(string[] args)
    {
        return MainImpl(args, configure: null);
    }

    internal static Task<int> MainImpl(string[] args, Action<InvocationConfiguration>? configure)
    {
        var inputOption = new Option<string[]>("--input")
        {
            Description = "Assembly input. Use either 'path' or 'tfm=path'. Repeat for multi-target generation.",
            Required = true,
            Arity = ArgumentArity.OneOrMore,
            AllowMultipleArgumentsPerToken = true,
        };
        var outputOption = new Option<string>("--output")
        {
            Description = "Output path (directory, or file path when --file-layout is SingleFile)",
            Required = true,
        };
        var fileLayoutOption = new Option<PublicApiFileLayout>("--file-layout")
        {
            Description = "File layout: SingleFile, OneFilePerNamespace, or OneFilePerType",
            DefaultValueFactory = _ => PublicApiFileLayout.SingleFile,
        };
        var omitAutoGeneratedCommentOption = new Option<bool>("--omit-auto-generated-comment")
        {
            Description = "Omit the // <auto-generated/> comment from generated files",
        };

        var rootCommand = new RootCommand("Generate public API stubs from a .NET assembly.");
        rootCommand.Options.Add(inputOption);
        rootCommand.Options.Add(outputOption);
        rootCommand.Options.Add(fileLayoutOption);
        rootCommand.Options.Add(omitAutoGeneratedCommentOption);

        rootCommand.SetAction(parseResult =>
        {
            var inputValues = parseResult.GetValue(inputOption);
            var output = parseResult.GetValue(outputOption);
            if (inputValues is null || inputValues.Length == 0 || string.IsNullOrWhiteSpace(output))
            {
                throw new InvalidOperationException("The --input and --output options are required.");
            }

            var options = new PublicApiOptions
            {
                FileLayout = parseResult.GetValue(fileLayoutOption),
                IncludeAutoGeneratedComment = !parseResult.GetValue(omitAutoGeneratedCommentOption),
            };

            var inputs = ParseInputs(inputValues);
            GenerateFiles(inputs, output, options);

            return 0;
        });

        var invocationConfiguration = new InvocationConfiguration();
        configure?.Invoke(invocationConfiguration);
        return rootCommand.Parse(args).InvokeAsync(invocationConfiguration);
    }

    private static void GenerateFiles(IReadOnlyList<AssemblySource> inputs, string output, PublicApiOptions options)
    {
        if (options.FileLayout is not PublicApiFileLayout.SingleFile)
        {
            PublicApi.GenerateToDirectory(inputs, output, options);
            return;
        }

        var outputPath = FullPath.FromPath(output);
        if (ShouldUseOutputAsFilePath(outputPath))
        {
            var files = PublicApi.Generate(inputs, options);
            if (files.Count != 1)
            {
                throw new InvalidOperationException($"Expected a single generated file when using {nameof(PublicApiFileLayout.SingleFile)} layout.");
            }

            outputPath.CreateParentDirectory();
            File.WriteAllText(outputPath, files[0].Content);
            return;
        }

        PublicApi.GenerateToDirectory(inputs, outputPath, options);
    }

    private static bool ShouldUseOutputAsFilePath(FullPath outputPath)
    {
        if (Directory.Exists(outputPath))
        {
            return false;
        }

        if (File.Exists(outputPath))
        {
            return true;
        }

        return !string.IsNullOrEmpty(outputPath.Extension);
    }

    private static List<AssemblySource> ParseInputs(string[] inputValues)
    {
        var result = new List<AssemblySource>(inputValues.Length);
        foreach (var inputValue in inputValues)
        {
            if (string.IsNullOrWhiteSpace(inputValue))
            {
                throw new InvalidOperationException("The --input option cannot be empty.");
            }

            var trimmedInputValue = inputValue.Trim();
            var separatorIndex = trimmedInputValue.IndexOf('=', StringComparison.Ordinal);
            if (separatorIndex < 0)
            {
                result.Add(trimmedInputValue);
                continue;
            }

            if (separatorIndex == 0 || separatorIndex == trimmedInputValue.Length - 1)
            {
                throw new InvalidOperationException($"Invalid --input value '{inputValue}'. Use either 'path' or 'tfm=path'.");
            }

            var targetFramework = trimmedInputValue[..separatorIndex].Trim();
            var assemblyPath = trimmedInputValue[(separatorIndex + 1)..].Trim();
            if (string.IsNullOrEmpty(targetFramework) || string.IsNullOrEmpty(assemblyPath))
            {
                throw new InvalidOperationException($"Invalid --input value '{inputValue}'. Use either 'path' or 'tfm=path'.");
            }

            result.Add(new AssemblySource(assemblyPath, targetFramework));
        }

        return result;
    }
}
