<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.Language.Regex.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Corpus/*.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.Language.Regex/Meziantou.Framework.Language.Regex.csproj" />
  </ItemGroup>

</Project>
