<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.Language.Ini.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.Language.Ini/Meziantou.Framework.Language.Ini.csproj" />
  </ItemGroup>

</Project>
