<Project Sdk="Meziantou.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <IncludeDefaultTestReferences>false</IncludeDefaultTestReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Meziantou.Framework.FullPath\Meziantou.Framework.FullPath.csproj" />
    <ProjectReference Include="..\..\src\Meziantou.Framework.Imaging\Meziantou.Framework.Imaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Prebuilt" Version="3.3.0" />
  </ItemGroup>
</Project>
