//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GitVersion
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meziantou.Framework
{
    partial struct ByteSize
    {
        public static ByteSize FromByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.Byte);
        public static ByteSize FromByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.Byte);
        public static ByteSize FromByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.Byte);
        public static ByteSize FromByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.Byte);
        public static ByteSize FromByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.Byte));
        public static ByteSize FromByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.Byte));
        public static ByteSize FromKiloByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.KiloByte);
        public static ByteSize FromKiloByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.KiloByte);
        public static ByteSize FromKiloByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.KiloByte);
        public static ByteSize FromKiloByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.KiloByte);
        public static ByteSize FromKiloByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.KiloByte));
        public static ByteSize FromKiloByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.KiloByte));
        public static ByteSize FromMegaByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.MegaByte);
        public static ByteSize FromMegaByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.MegaByte);
        public static ByteSize FromMegaByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.MegaByte);
        public static ByteSize FromMegaByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.MegaByte);
        public static ByteSize FromMegaByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.MegaByte));
        public static ByteSize FromMegaByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.MegaByte));
        public static ByteSize FromGigaByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.GigaByte);
        public static ByteSize FromGigaByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.GigaByte);
        public static ByteSize FromGigaByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.GigaByte);
        public static ByteSize FromGigaByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.GigaByte);
        public static ByteSize FromGigaByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.GigaByte));
        public static ByteSize FromGigaByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.GigaByte));
        public static ByteSize FromTeraByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.TeraByte);
        public static ByteSize FromTeraByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.TeraByte);
        public static ByteSize FromTeraByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.TeraByte);
        public static ByteSize FromTeraByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.TeraByte);
        public static ByteSize FromTeraByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.TeraByte));
        public static ByteSize FromTeraByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.TeraByte));
        public static ByteSize FromPetaByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.PetaByte);
        public static ByteSize FromPetaByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.PetaByte);
        public static ByteSize FromPetaByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.PetaByte);
        public static ByteSize FromPetaByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.PetaByte);
        public static ByteSize FromPetaByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.PetaByte));
        public static ByteSize FromPetaByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.PetaByte));
        public static ByteSize FromExaByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.ExaByte);
        public static ByteSize FromExaByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.ExaByte);
        public static ByteSize FromExaByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.ExaByte);
        public static ByteSize FromExaByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.ExaByte);
        public static ByteSize FromExaByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.ExaByte));
        public static ByteSize FromExaByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.ExaByte));
        public static ByteSize FromKibiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.KibiByte);
        public static ByteSize FromKibiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.KibiByte);
        public static ByteSize FromKibiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.KibiByte);
        public static ByteSize FromKibiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.KibiByte);
        public static ByteSize FromKibiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.KibiByte));
        public static ByteSize FromKibiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.KibiByte));
        public static ByteSize FromMebiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.MebiByte);
        public static ByteSize FromMebiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.MebiByte);
        public static ByteSize FromMebiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.MebiByte);
        public static ByteSize FromMebiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.MebiByte);
        public static ByteSize FromMebiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.MebiByte));
        public static ByteSize FromMebiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.MebiByte));
        public static ByteSize FromGibiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.GibiByte);
        public static ByteSize FromGibiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.GibiByte);
        public static ByteSize FromGibiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.GibiByte);
        public static ByteSize FromGibiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.GibiByte);
        public static ByteSize FromGibiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.GibiByte));
        public static ByteSize FromGibiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.GibiByte));
        public static ByteSize FromTebiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.TebiByte);
        public static ByteSize FromTebiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.TebiByte);
        public static ByteSize FromTebiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.TebiByte);
        public static ByteSize FromTebiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.TebiByte);
        public static ByteSize FromTebiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.TebiByte));
        public static ByteSize FromTebiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.TebiByte));
        public static ByteSize FromPebiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.PebiByte);
        public static ByteSize FromPebiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.PebiByte);
        public static ByteSize FromPebiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.PebiByte);
        public static ByteSize FromPebiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.PebiByte);
        public static ByteSize FromPebiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.PebiByte));
        public static ByteSize FromPebiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.PebiByte));
        public static ByteSize FromExbiByte(byte value) => new ByteSize((long)value * (long)ByteSizeUnit.ExbiByte);
        public static ByteSize FromExbiByte(short value) => new ByteSize((long)value * (long)ByteSizeUnit.ExbiByte);
        public static ByteSize FromExbiByte(int value) => new ByteSize((long)value * (long)ByteSizeUnit.ExbiByte);
        public static ByteSize FromExbiByte(long value) => new ByteSize((long)value * (long)ByteSizeUnit.ExbiByte);
        public static ByteSize FromExbiByte(float value) => new ByteSize((long)(value * (long)ByteSizeUnit.ExbiByte));
        public static ByteSize FromExbiByte(double value) => new ByteSize((long)(value * (long)ByteSizeUnit.ExbiByte));
    }
}
