name: 'Setup .NET'

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
        dotnet-version: |
          9.0.x
          8.0.x
