using System.Reflection;
using System.Runtime.CompilerServices;
using Meziantou.Framework;
using Meziantou.Framework.InlineSnapshotTesting;
using Meziantou.Framework.PublicApiGenerator;
using Meziantou.Framework.PublicApiGenerator.Tool;
using Xunit.Sdk;

namespace Meziantou.Framework.PublicApiGenerator.Tests;

[Collection("Tool")] // Ensure tests run sequentially
public sealed class PublicApiGeneratorTests
{
    [Fact]
    public async Task EmptyClass()
    {
        await Validate("""
            public class Sample
            {
            }
            """, """
            #nullable enable

            public class Sample
            {
            }
            """);
    }

    [Fact]
    public async Task Namespace_EmptyClass()
    {
        await Validate("""
            namespace Demo;

            public class Sample
            {
            }
            """, """
            #nullable enable

            namespace Demo
            {
                public class Sample
                {
                }
            }
            """);
    }

    [Fact]
    public async Task EmptyInterface()
    {
        await Validate("""
            public interface ISample
            {
            }
            """, """
            #nullable enable

            public interface ISample
            {
            }
            """);
    }

    [Fact]
    public async Task Struct_Empty()
    {
        await Validate("""
            public struct Sample
            {
            }
            """, """
            #nullable enable

            public struct Sample
            {
            }
            """);
    }

    [Fact]
    public async Task RefStruct_Empty()
    {
        await Validate("""
            public ref struct Sample
            {
            }
            """, """
            #nullable enable

            public ref struct Sample
            {
            }
            """);
    }

    [Fact]
    public async Task RefStruct_RefFields()
    {
        await Validate("""
            public ref struct Sample
            {
                public ref int A;
                public readonly ref int B;
                public ref readonly int C;
                public readonly ref readonly int D;
            }
            """, """
            #nullable enable

            public ref struct Sample
            {
                public ref int A;
                public readonly ref int B;
                public ref readonly int C;
                public readonly ref readonly int D;
            }
            """);
    }

    [Fact]
    public async Task EmptyClass_WithoutAutoGeneratedComment()
    {
        await Validate("""
            public class Sample
            {
            }
            """, """
            // <auto-generated/>
            #nullable enable

            public class Sample
            {
            }
            """, new PublicApiGeneratorOptions
        {
            IncludeAutoGeneratedComment = true,
        });
    }

    [Fact]
    public async Task Methods_InstanceAndStatic()
    {
        await Validate("""
            public class Sample
            {
                public int GetValue() => 42;
                public static void Reset() { }
            }
            """, """
            #nullable enable

            public class Sample
            {
                public int GetValue() => throw null;
                public static void Reset() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Method_ParameterModifiers()
    {
        await Validate("""
            public class Sample
            {
                public void M(in int p0, ref int p1, out int p2, ref readonly int p3)
                {
                    p2 = default;
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                public void M(in int p0, ref int p1, out int p2, ref readonly int p3) => throw null;
            }
            """);
    }

    [Fact]
    public async Task Method_NullableReferenceTypes()
    {
        await Validate("""
            public class Sample
            {
                public string? A(string? value) => value;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public string? A(string? value) => throw null;
            }
            """);
    }

    [Fact]
    public async Task Method_NullableGenericArguments()
    {
        await Validate("""
            using System.Collections.Generic;

            public class Sample
            {
                public Dictionary<object, string?> A() => null;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public global::System.Collections.Generic.Dictionary<object, string?> A() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Method_NestedNullableGenericArguments()
    {
        await Validate("""
            using System.Collections.Generic;

            public class Sample
            {
                public Dictionary<object, HashSet<string?>?> A() => null;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public global::System.Collections.Generic.Dictionary<object, global::System.Collections.Generic.HashSet<string?>?> A() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Event_Basic()
    {
        await Validate("""
            using System;

            public class Sample
            {
                public event EventHandler? Changed;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public event global::System.EventHandler? Changed;
            }
            """);
    }

    [Fact]
    public async Task Properties_GetSetInitRequired()
    {
        await Validate("""
            public class Sample
            {
                public int GetOnly { get; }
                public int SetOnly { set { } }
                public int InitOnly { get; init; }
                public required int RequiredValue { get; set; }
            }
            """, """
            #nullable enable

            public class Sample
            {
                public int GetOnly { get => throw null; }
                public int SetOnly { set => throw null; }
                public int InitOnly { get => throw null; init => throw null; }
                public required int RequiredValue { get => throw null; set => throw null; }
            }
            """);
    }

    [Fact]
    public async Task Fields_InstanceAndStaticReadonly()
    {
        await Validate("""
            public class Sample
            {
                public int Field;
                public static readonly int StaticReadonlyField = 42;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public int Field;
                public static readonly int StaticReadonlyField;
            }
            """);
    }

    [Fact]
    public async Task InterfaceMembers_StaticAndDefault()
    {
        await Validate("""
            public interface ISample
            {
                void M();
                static abstract int Counter { get; set; }
                static virtual int StaticMethod() => 1;
                int DefaultMethod() => 42;
            }
            """, """
            #nullable enable

            public interface ISample
            {
                public static int Counter { get; set; }
                public abstract void M();
                public static virtual int StaticMethod() => throw null;
                public virtual int DefaultMethod() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Constructor_Explicit()
    {
        await Validate("""
            public class Sample
            {
                public Sample()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
            }
            """);
    }

    [Fact]
    public async Task Constructor_BaseWithoutDefaultConstructor()
    {
        await Validate("""
            public class SampleBaseClass
            {
                public SampleBaseClass(int value)
                {
                }
            }

            public class Sample : SampleBaseClass
            {
                public Sample() : base(default(int))
                {
                }
            }
            """, """
            #nullable enable

            public class Sample : SampleBaseClass
            {
            }


            public class SampleBaseClass
            {
            }
            """);
    }

    [Fact]
    public async Task Destructor_Explicit()
    {
        await Validate("""
            public class Sample
            {
                ~Sample()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                ~Sample() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Class_ImplementsInterface()
    {
        await Validate("""
            using System;

            public class Sample : IDisposable
            {
                public void Dispose()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample : global::System.IDisposable
            {
                public void Dispose() => throw null;
            }
            """);
    }

    [Fact]
    public async Task MethodParameter_DefaultValues()
    {
        await Validate("""
            public class Sample
            {
                public void M(int value = 42, string? text = null)
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                public void M(int value = 42, string? text = null) => throw null;
            }
            """);
    }

    [Fact]
    public async Task Method_WithCLSCompliantAttribute()
    {
        await Validate("""
            public class Sample
            {
                [System.CLSCompliantAttribute(false)]
                public void M()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                [global::System.CLSCompliant(false)]
                public void M() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Nullable_DisabledAndRestored()
    {
        await Validate("""
            #nullable enable

            public class Sample
            {
            #nullable disable
                public string M(string value) => value;
            #nullable restore
                public string? N(string? value) => value;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public string M(string value) => throw null;
                public string? N(string? value) => throw null;
            }
            """);
    }

    [Fact]
    public async Task Attributes_SkippedAndPreserved()
    {
        await Validate("""
            using System.CodeDom.Compiler;

            public class Sample
            {
                [GeneratedCode("generator", "1.0")]
                [System.CLSCompliantAttribute(false)]
                public void M()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                [global::System.CLSCompliant(false)]
                public void M() => throw null;
            }
            """);
    }

    [Fact]
    public async Task Enum_Basic()
    {
        await Validate("""
            public enum Sample
            {
                A,
                B,
            }
            """, """
            #nullable enable

            public enum Sample
            {
                A = 0,
                B = 1
            }
            """);
    }

    [Fact]
    public async Task Enum_ExplicitValues()
    {
        await Validate("""
            public enum Sample
            {
                A = 1,
                B = 3,
            }
            """, """
            #nullable enable

            public enum Sample
            {
                A = 1,
                B = 3
            }
            """);
    }

    [Fact]
    public async Task Enum_WithFlagsAttribute()
    {
        await Validate("""
            [System.FlagsAttribute]
            public enum Sample
            {
                A = 1,
                B = 2,
            }
            """, """
            #nullable enable

            [global::System.Flags]
            public enum Sample
            {
                A = 1,
                B = 2
            }
            """);
    }

    [Fact]
    public async Task NullableInt_SystemNullable()
    {
        await Validate("""
            public class Sample
            {
                public System.Nullable<int> M(System.Nullable<int> value) => value;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public int? M(int? value) => throw null;
            }
            """);
    }

    [Fact]
    public async Task GenericClass()
    {
        await Validate("""
            public class Sample<T0>
            {
                public T0 Value => default;
            }
            """, """
            #nullable enable

            public class Sample<T0>
            {
                public T0 Value { get => throw null; }
            }
            """);
    }

    [Fact]
    public async Task GenericClass_ImplementsGenericInterface()
    {
        await Validate("""
            using System.Collections;
            using System.Collections.Generic;

            public class Sample<T0> : IEnumerable<T0>
            {
                public IEnumerator<T0> GetEnumerator() => null;
                IEnumerator IEnumerable.GetEnumerator() => null;
            }
            """, """
            #nullable enable

            public class Sample<T0> : global::System.Collections.Generic.IEnumerable<T0>, global::System.Collections.IEnumerable
            {
                public global::System.Collections.Generic.IEnumerator<T0> GetEnumerator() => throw null;
                global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => throw null;
            }
            """);
    }

    [Fact]
    public async Task GenericMembers()
    {
        await Validate("""
            public class Sample
            {
                public TMethod0 M<TMethod0>(TMethod0 value) => value;
            }
            """, """
            #nullable enable

            public class Sample
            {
                public TMethod0 M<TMethod0>(TMethod0 value) => throw null;
            }
            """);
    }

    [Fact]
    public async Task GenericMembers_WithConstraints()
    {
        await Validate("""
            public class SampleBaseClass
            {
            }

            public class Sample
            {
                public void M<TAllowNull, TNew, TStruct, TClass, TEnum, TBase>()
                    where TAllowNull : class?
                    where TNew : new()
                    where TStruct : struct
                    where TClass : class
                    where TEnum : System.Enum
                    where TBase : SampleBaseClass
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                public void M<TAllowNull, TNew, TStruct, TClass, TEnum, TBase>()
                    where TAllowNull : class
                    where TNew : new()
                    where TStruct : struct
                    where TClass : class
                    where TEnum : global::System.Enum
                    where TBase : SampleBaseClass
                => throw null;
            }


            public class SampleBaseClass
            {
            }
            """);
    }

    [Fact]
    public async Task Member_WithObsoleteAttribute()
    {
        await Validate("""
            public class Sample
            {
                [System.ObsoleteAttribute("Use M2 instead")]
                public void M()
                {
                }
            }
            """, """
            #nullable enable

            public class Sample
            {
                [global::System.Obsolete("Use M2 instead")]
                public void M() => throw null;
            }
            """);
    }

#if NET10_0_OR_GREATER
    [Fact]
    public async Task GenericConstraint_AllowsRefStruct()
    {
        await Validate("""
            public class Sample<T0>
                where T0 : allows ref struct
            {
            }
            """, """
            #nullable enable

            public class Sample<T0>
                where T0 : allows ref struct
            {
            }
            """, compilerOptions: new CompilerOptions
        {
            TargetFramework = "net10.0",
        });
    }
#endif

    [InlineSnapshotAssertion(nameof(expected))]
    private static async Task Validate(string source, string expected, PublicApiGeneratorOptions options = null, CompilerOptions compilerOptions = null, [CallerFilePath] string filePath = null, [CallerLineNumber] int lineNumber = -1)
    {
        await using var temporaryDirectory = TemporaryDirectory.Create();
        compilerOptions ??= new CompilerOptions();
        options ??= new PublicApiGeneratorOptions
        {
            FileLayout = PublicApiFileLayout.SingleFile,
            IncludeAutoGeneratedComment = false,
        };

        // Build the project
        var sourceProjectDirectory = temporaryDirectory / "source";
        temporaryDirectory.CreateTextFile(sourceProjectDirectory / "project.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>{{compilerOptions.TargetFramework}}</TargetFramework>
                <LangVersion>preview</LangVersion>
                <Nullable>{{(compilerOptions.Nullable ? "enable" : "disable")}}</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
              </PropertyGroup>
            </Project>
            """);
        temporaryDirectory.CreateTextFile(sourceProjectDirectory / "Sample.cs", source);

        var assemblyPath = await Compile(sourceProjectDirectory);

        // Generate the API files using both reflection and metadata
        var reflectionFiles = PublicApiStubGenerator.GenerateFiles(
            Assembly.LoadFile(assemblyPath),
            options);
        var metadataFiles = PublicApiStubGenerator.GenerateFiles(
            assemblyPath,
            options);

        var reflectionContent = SerializeFiles(reflectionFiles);
        var metadataContent = SerializeFiles(metadataFiles);
        Assert.Equal(reflectionContent, metadataContent);
        InlineSnapshot.Validate(reflectionContent, expected, filePath, lineNumber);

        // Ensure the generated files are compilable
        var generatedDirectory = temporaryDirectory / "generated";
        temporaryDirectory.CreateTextFile(generatedDirectory / "project.csproj", $$"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>{{compilerOptions.TargetFramework}}</TargetFramework>
                <LangVersion>preview</LangVersion>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
              </PropertyGroup>
            </Project>
            """);
        foreach (var file in reflectionFiles)
        {
            temporaryDirectory.CreateTextFile(generatedDirectory / file.RelativePath, file.Content);
        }

        await Compile(generatedDirectory);

        static string SerializeFiles(IReadOnlyList<PublicApiGeneratedFile> files)
        {
            return string.Join(
                "\n\n",
                files
                    .OrderBy(file => file.RelativePath, StringComparer.Ordinal)
                    .Select(file => file.Content.TrimEnd('\r', '\n')));
        }
    }

    private static async Task<FullPath> Compile(FullPath temporaryDirectory)
    {
        var projectPath = Assert.Single(Directory.EnumerateFiles(temporaryDirectory, "*.csproj", SearchOption.TopDirectoryOnly));

        var outputPath = temporaryDirectory / "bin";

        await RunDotNetAsync(temporaryDirectory, ["restore", projectPath, "-nologo", "--disable-build-servers"]);
        await RunDotNetAsync(temporaryDirectory, ["build", projectPath, "-nologo", "--disable-build-servers", "--no-restore", "--output", outputPath, "/p:AssemblyName=Source"]);
        return outputPath / "Source.dll";

        static async Task RunDotNetAsync(string workingDirectory, IReadOnlyList<string> arguments)
        {
            var processResult = await ProcessWrapper.Create("dotnet")
                .WithArguments(arguments)
                .WithWorkingDirectory(workingDirectory)
                .WithEnvironmentVariables(env => env.Set("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1"))
                .WithValidation(ProcessValidationMode.None)
                .ExecuteBufferedAsync(XunitCancellationToken);

            if (!processResult.ExitCode.IsSuccess)
            {
                var standardOutput = string.Join('\n', processResult.Output.StandardOutput.Select(line => line.Text));
                var standardError = string.Join('\n', processResult.Output.StandardError.Select(line => line.Text));
                throw new XunitException($"Command failed: dotnet {string.Join(' ', arguments)}\nstdout:\n{standardOutput}\nstderr:\n{standardError}");
            }
        }
    }

    public sealed class CompilerOptions
    {
        public bool Nullable { get; set; } = true;
        public string TargetFramework { get; set; } = "net8.0";
    }
}
