<Project Sdk="Meziantou.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <Description>Enables verification of SkiaSharp images using file-based snapshots</Description>
    <Version>1.0.4</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Meziantou.Framework.SnapshotTesting/Images/SsimAccumulator.cs" Link="Images/SsimAccumulator.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Meziantou.Framework.SnapshotTesting/Meziantou.Framework.SnapshotTesting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
  </ItemGroup>

</Project>
