<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <IsTrimmable>false</IsTrimmable>
    <Version>2.0.6</Version>
    <Description>CLI tool to approve Meziantou.Framework.SnapshotTesting snapshots</Description>
    <PackageTags>snapshot-testing, testing, cli, dotnet-tool</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Meziantou.Framework.FullPath/Meziantou.Framework.FullPath.csproj" />
  </ItemGroup>

</Project>
