<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework</RootNamespace>
    <Version>3.0.3</Version>
    <IsTrimmable>true</IsTrimmable>
    <Description>TemporaryDirectory and TemporaryFile allow to create a disposable directory or file to store temporary data</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Meziantou.Framework/IOUtilities.Delete.cs" Link="IOUtilities.Delete.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Meziantou.Framework.FullPath/Meziantou.Framework.FullPath.csproj" />
  </ItemGroup>

</Project>
