using Meziantou.Framework.Imaging.TestHarness.Adapters;
using Meziantou.Framework.Imaging.TestHarness.Bmp;
using Meziantou.Framework.Imaging.TestHarness.Fixtures;
using Meziantou.Framework.Imaging.TestHarness.Golden;
using Meziantou.Framework.Imaging.TestHarness.Pixels;

namespace Meziantou.Framework.Imaging.Tests.Conformance;

/// <summary>
/// BMP decoding against the corpus generated by <c>tools/Meziantou.Framework.Imaging.CorpusGenerator/BmpCorpus.cs</c>: files assembled
/// byte by byte with literal pixels, plus files produced by FFmpeg's independent BMP encoder. The eager, sequential and
/// identify suites already compare every fixture; these tests check that the fixtures cover every supported header, bit
/// depth, mask and orientation, that decoding is exact in every representation, that unspecified alpha is never read as
/// transparency, and that the independent harness reader agrees with the corpus and rejects every malformed fixture.
/// </summary>
public sealed class BmpDecoderConformanceTests
{
    public static TheoryData<string> ValidFixtures => [.. GoldenCorpus.Default.GetIds(format: "bmp", kind: FixtureKinds.Valid)];

    public static TheoryData<string> InvalidFixtures => [.. GoldenCorpus.Default.GetIds(format: "bmp", kind: FixtureKinds.Invalid)];

    [Fact]
    public void FixturesCoverEveryDocumentedVariant()
    {
        var fixtures = GoldenCorpus.Default.GetIds(format: "bmp", kind: FixtureKinds.Valid).Select(GoldenCorpus.Default.Get).ToList();
        var features = fixtures.SelectMany(fixture => fixture.Entry.Features ?? []).ToHashSet(StringComparer.Ordinal);
        foreach (var feature in new[]
        {
            "bmp.bpp=1", "bmp.bpp=4", "bmp.bpp=8", "bmp.bpp=16", "bmp.bpp=24", "bmp.bpp=32",
            "bmp.header=40", "bmp.header=56", "bmp.header=108",
            "bmp.compression=rgb", "bmp.compression=bitfields", "bmp.alphaMask=yes", "bmp.alphaMask=no",
            "bmp.rowOrder=bottom-up", "bmp.rowOrder=top-down", "bmp.rowPadding", "bmp.gapBeforePixels", "bmp.resolution",
            "bmp.width=odd",
        })
        {
            Assert.Contains(feature, features);
        }

        // Both an independent encoder and hand-assembled files, and every comparison is exact (BMP is lossless)
        Assert.Contains(fixtures, fixture => fixture.Entry.Provenance.Origin == "hand-authored");
        Assert.Contains(fixtures, fixture => fixture.Entry.Provenance.Commands?.Any(command => command.StartsWith("ffmpeg", StringComparison.Ordinal)) == true);
        Assert.All(fixtures, fixture => Assert.True(fixture.Policy.IsExact, fixture.Id));
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void DecodingIsExactInEveryRepresentation(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        var data = fixture.ReadInput();

        using (var image = Image.Load<Rgba32>(data))
        {
            var actual = ImageSnapshots.CaptureFrame(image.Frames[0]);
            Assert.True(fixture.GetFrame(0, RawPixelLayout.Rgba8).Span.SequenceEqual(actual.Span), $"{id}: differs from the reference.");
        }

        // The default representation holds the declared samples exactly
        using (var image = Image.Load(data))
        {
            Assert.Equal(fixture.Expected.PixelFormat, image.PixelFormat.ToString());
            var layout = image.PixelFormat == PixelFormat.Rgb24 ? RawPixelLayout.Rgb8 : RawPixelLayout.Rgba8;
            var bytes = new byte[image.Width * image.Height * layout.BytesPerPixel];
            image.Frames[0].CopyPixelBytesTo(bytes);
            Assert.True(fixture.GetFrame(0, layout).Span.SequenceEqual(bytes), $"{id}: the {layout.Name} samples differ from the reference.");
        }
    }

    [Fact]
    public void AnUnspecifiedFourthByteIsNotTransparency()
    {
        // The same 32-bit payload decodes to Rgba32 with an alpha mask and to opaque Rgb24 without one
        var withMask = GoldenCorpus.Default.Get("bmp/bgra32-v4-alpha");
        var withoutMask = GoldenCorpus.Default.Get("bmp/bgrx32-unspecified-alpha");
        var masked = Image.Identify(withMask.ReadInput());
        var unmasked = Image.Identify(withoutMask.ReadInput());
        Assert.Equal(PixelFormat.Rgba32, masked.PixelFormat);
        Assert.Equal(PixelFormat.Rgb24, unmasked.PixelFormat);
        Assert.True(masked.MayHaveTransparency);
        Assert.False(unmasked.MayHaveTransparency);

        using var image = Image.Load<Rgba32>(withoutMask.ReadInput());
        image.Frames[0].ProcessPixelRows(rows =>
        {
            for (var y = 0; y < rows.Height; y++)
            {
                foreach (var pixel in rows.GetRowSpan(y))
                {
                    Assert.Equal(byte.MaxValue, pixel.A);
                }
            }
        });
    }

    [Fact]
    public void TheResolutionIsDecodedFromPixelsPerMeter()
    {
        var info = Image.Identify(GoldenCorpus.Default.Get("bmp/bgr24-resolution").ReadInput());
        var resolution = Assert.IsType<Metadata.ImageResolution>(info.Metadata.Resolution);
        Assert.Equal(2835 * 0.0254, resolution.HorizontalDpi);
        Assert.Equal(5670 * 0.0254, resolution.VerticalDpi);
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void TheReferenceReaderAgreesWithTheCorpus(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        var reference = ReferenceBmp.Parse(fixture.ReadInput());
        Assert.Equal((fixture.Expected.Width, fixture.Expected.Height), (reference.Width, reference.Height));
        Assert.True(fixture.GetFrame(0, RawPixelLayout.Rgba8).Span.SequenceEqual(reference.Rgba.Span), $"{id}: the harness reader differs from the corpus reference.");
    }

    [Theory]
    [MemberData(nameof(InvalidFixtures))]
    public void TheReferenceReaderRejectsEveryMalformedFixture(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        Assert.Throws<InvalidDataException>(() => ReferenceBmp.Parse(fixture.ReadInput()));
        var exception = Assert.Throws<InvalidImageContentException>(() => Image.Load(fixture.ReadInput()));
        Assert.Equal(ImageFormat.Bmp, exception.Format);
    }
}
