using Meziantou.Framework.Imaging.Metadata;
using Meziantou.Framework.Imaging.TestHarness.Adapters;
using Meziantou.Framework.Imaging.TestHarness.Fixtures;
using Meziantou.Framework.Imaging.TestHarness.Golden;
using Meziantou.Framework.Imaging.TestHarness.Pixels;
using Meziantou.Framework.Imaging.TestHarness.Qoi;

namespace Meziantou.Framework.Imaging.Tests.Conformance;

/// <summary>
/// QOI decoding against the corpus generated by <c>tools/Meziantou.Framework.Imaging.CorpusGenerator/QoiCorpus.cs</c>: hand-assembled
/// chunk streams with literal pixels and patterns encoded by the qoi.h reference encoder and FFmpeg, every one decoded exactly
/// by qoi.h and FFmpeg when the corpus was generated. The eager, sequential and identify suites already compare every fixture;
/// these tests check that the fixtures cover every chunk form and boundary, that decoding is exact in every typed and untyped
/// representation, that the colorspace field is reported as a label (never applied), and that the independent harness reader
/// (used to verify the encoder) agrees with the corpus and rejects every malformed fixture.
/// </summary>
public sealed class QoiDecoderConformanceTests
{
    public static TheoryData<string> ValidFixtures => [.. GoldenCorpus.Default.GetIds(format: "qoi", kind: FixtureKinds.Valid)];

    public static TheoryData<string> InvalidFixtures => [.. GoldenCorpus.Default.GetIds(format: "qoi", kind: FixtureKinds.Invalid)];

    [Fact]
    public void FixturesCoverEveryChunkFormAndBoundary()
    {
        var fixtures = GoldenCorpus.Default.GetIds(format: "qoi", kind: FixtureKinds.Valid).Select(id => GoldenCorpus.Default.Get(id)).ToList();
        var features = fixtures.SelectMany(fixture => fixture.Entry.Features ?? []).ToHashSet(StringComparer.Ordinal);
        foreach (var feature in new[]
        {
            "qoi.channels=3", "qoi.channels=4", "qoi.colorspace=srgb", "qoi.colorspace=linear", "qoi.op=rgb", "qoi.op=rgba",
            "qoi.op=index", "qoi.op=diff", "qoi.op=luma", "qoi.op=run", "qoi.run=1", "qoi.run=62", "qoi.run.crossesRow",
            "qoi.run.atStart", "qoi.run.atEnd", "qoi.diff.wrap", "qoi.luma.wrap", "qoi.index.unset", "qoi.index.initialPixel",
            "qoi.alpha.kept", "qoi.rgbStream.alphaChunks", "qoi.width=odd",
        })
        {
            Assert.Contains(feature, features);
        }

        // A 1x1 image, transparent pixels with defined colors, and both independent encoders and hand-assembled streams
        Assert.Contains(fixtures, fixture => fixture.Expected.Width == 1 && fixture.Expected.Height == 1);
        Assert.Contains(fixtures, fixture => HasHiddenColors(fixture.GetFrame(0, RawPixelLayout.Rgba8)));
        Assert.Contains(fixtures, fixture => fixture.Entry.Provenance.Origin == "hand-authored");
        Assert.Contains(fixtures, fixture => fixture.Entry.Provenance.Commands?.Any(command => command.StartsWith("qoi_driver encode", StringComparison.Ordinal)) == true);
        Assert.Contains(fixtures, fixture => fixture.Entry.Provenance.Commands?.Any(command => command.StartsWith("ffmpeg", StringComparison.Ordinal)) == true);
        Assert.All(fixtures, fixture => Assert.True(fixture.Policy.IsExact, fixture.Id));
        Assert.All(fixtures, fixture => Assert.All(fixture.Entry.Reference!.CrossChecks!, check => Assert.Equal(FixtureCrossCheck.Exact, check.Result)));
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void DecodingIsExactAndTheColorspaceIsALabel(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        var data = fixture.ReadInput();
        var expectedTransfer = fixture.Expected.EffectiveTransferFunction == "linear" ? ColorTransferFunction.Linear : ColorTransferFunction.Srgb;

        using (var image = Image.Load<Rgba32>(data))
        {
            var actual = ImageSnapshots.CaptureFrame(image.Frames[0]);
            Assert.True(fixture.GetFrame(0, RawPixelLayout.Rgba8).Span.SequenceEqual(actual.Span), $"{id}: differs from the reference (hidden colors included).");
            Assert.Equal(expectedTransfer, image.Metadata.TransferFunction);
        }

        // The default representation holds the declared samples exactly: RGB streams in Rgb24, RGBA streams in Rgba32
        using (var image = Image.Load(data))
        {
            Assert.Equal(fixture.Expected.PixelFormat, image.PixelFormat.ToString());
            var layout = image.PixelFormat == PixelFormat.Rgb24 ? RawPixelLayout.Rgb8 : RawPixelLayout.Rgba8;
            var bytes = new byte[image.Width * image.Height * layout.BytesPerPixel];
            image.Frames[0].CopyPixelBytesTo(bytes);
            Assert.True(fixture.GetFrame(0, layout).Span.SequenceEqual(bytes), $"{id}: the {layout.Name} samples differ from the reference.");
        }

        Assert.Equal(expectedTransfer, Image.Identify(data).Metadata.TransferFunction);
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void TheReferenceReaderAgreesWithTheCorpus(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        var reference = ReferenceQoi.Parse(fixture.ReadInput());
        Assert.Equal(((uint)fixture.Expected.Width, (uint)fixture.Expected.Height), (reference.Width, reference.Height));
        Assert.Equal(fixture.Expected.PixelFormat == "Rgba32" ? 4 : 3, reference.Channels);
        Assert.Equal(fixture.Expected.EffectiveTransferFunction == "linear" ? 1 : 0, reference.ColorSpace);
        var layout = reference.Channels == 4 ? RawPixelLayout.Rgba8 : RawPixelLayout.Rgb8;
        Assert.True(fixture.GetFrame(0, layout).Span.SequenceEqual(reference.GetDeclaredPixels()), $"{id}: the harness reader differs from the corpus reference.");
    }

    [Theory]
    [MemberData(nameof(InvalidFixtures))]
    public void TheReferenceReaderRejectsEveryMalformedFixture(string id)
    {
        // The defects were confirmed by the generator's strict transcription; the harness reader is a second, independent check
        var fixture = GoldenCorpus.Default.Get(id);
        Assert.Throws<InvalidDataException>(() => ReferenceQoi.Parse(fixture.ReadInput()));
        var exception = Assert.Throws<InvalidImageContentException>(() => Image.Load(fixture.ReadInput()));
        Assert.Equal(ImageFormat.Qoi, exception.Format);
    }

    private static bool HasHiddenColors(RawPixelBuffer frame)
    {
        var span = frame.Span;
        for (var i = 0; i < span.Length; i += 4)
        {
            if (span[i + 3] == 0 && (span[i] | span[i + 1] | span[i + 2]) != 0)
                return true;
        }

        return false;
    }
}
