using Meziantou.Framework.Imaging.TestHarness.Adapters;
using Meziantou.Framework.Imaging.TestHarness.Fixtures;
using Meziantou.Framework.Imaging.TestHarness.Golden;
using Meziantou.Framework.Imaging.TestHarness.Pixels;

namespace Meziantou.Framework.Imaging.Tests.Conformance;

/// <summary>
/// WebP decoding (still images and animations) against the corpus generated by
/// <c>tools/Meziantou.Framework.Imaging.CorpusGenerator/WebPCorpus.cs</c>. The eager, sequential and identify suites already compare every
/// fixture under its policy; these tests check that the fixtures cover the decoder features, that lossless decoding is
/// exact, and pin each lossy policy to the measurement: the tolerance must be exactly the one
/// the generator derives from the library's measured maximum and mean errors against the libwebp dwebp reference
/// (<c>LibraryWebPMeasurements</c>: max(1, measured max), measured mean + 0.01 rounded up to 0.01, never above what the
/// independent cross-checks justify), so a numerical change of the decoder is noticed and reviewed.
/// </summary>
public sealed class WebPDecoderConformanceTests
{
    public static TheoryData<string> LossyFixtures => [.. GoldenCorpus.Default.GetIds(format: "webp", kind: FixtureKinds.Valid, feature: "webp.bitstream=vp8")];

    public static TheoryData<string> LosslessFixtures => [.. GoldenCorpus.Default.GetIds(format: "webp", kind: FixtureKinds.Valid).Where(id => !GoldenCorpus.Default.Get(id).Entry.HasFeature("webp.bitstream=vp8"))];

    [Fact]
    public void FixturesCoverTheDecoderFeatures()
    {
        var fixtures = GoldenCorpus.Default.GetIds(format: "webp", kind: FixtureKinds.Valid).Select(id => GoldenCorpus.Default.Get(id)).ToList();
        var features = fixtures.SelectMany(fixture => fixture.Entry.Features ?? []).ToHashSet(StringComparer.Ordinal);
        foreach (var feature in new[]
        {
            "webp.layout=simple", "webp.layout=extended", "webp.bitstream=vp8", "webp.bitstream=vp8l", "webp.alpha=alph", "webp.alpha=vp8l",
            "webp.alph.compression=none", "webp.alph.compression=vp8l", "webp.vp8.filter=simple", "webp.vp8.filter=normal",
            "webp.vp8.filterLevel=0", "webp.vp8.segmentation", "webp.vp8l.transform=predictor", "webp.vp8l.transform=color-indexing",
            "webp.chunk=ICCP", "webp.chunk=EXIF", "webp.chunk=XMP", "webp.chunk=unknown", "webp.animation", "webp.blend=alpha",
            "webp.blend=none", "webp.dispose=background", "webp.dispose=none", "webp.frame=partial", "webp.frames=mixed",
            "webp.loop=infinite", "webp.loop=finite",
        })
        {
            Assert.Contains(feature, features);
        }

        // Odd dimensions (partial macroblocks, odd chroma planes), a 1x1 image, transparent pixels with defined colors
        Assert.Contains(fixtures, fixture => fixture.Entry.HasFeature("webp.bitstream=vp8") && fixture.Expected.Width % 2 == 1 && fixture.Expected.Height % 2 == 1);
        Assert.Contains(fixtures, fixture => fixture.Expected.Width == 1 && fixture.Expected.Height == 1);
        Assert.Contains(fixtures, fixture => fixture.Entry.HasFeature("webp.bitstream=vp8l") && !fixture.Entry.HasFeature("webp.animation") && HasHiddenColors(fixture.GetFrame(0, RawPixelLayout.Rgba8)));
    }

    [Theory]
    [MemberData(nameof(LosslessFixtures))]
    public void LosslessDecodingIsExact(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        Assert.True(fixture.Policy.IsExact);
        using var image = Image.Load<Rgba32>(fixture.ReadInput());
        var snapshot = ImageSnapshots.Capture(image);
        Assert.Equal(fixture.Expected.FrameCount, snapshot.Frames.Count);
        for (var i = 0; i < snapshot.Frames.Count; i++)
        {
            var expected = fixture.GetFrame(i, RawPixelLayout.Rgba8);
            Assert.True(expected.Span.SequenceEqual(snapshot.Frames[i].Pixels.Span), $"{id} frame {i} differs from the reference (hidden colors included).");
        }
    }

    [Theory]
    [MemberData(nameof(LossyFixtures))]
    public void ToleranceIsTheMeasuredDisagreementWithTheReference(string id)
    {
        var fixture = GoldenCorpus.Default.Get(id);
        using var image = Image.Load(fixture.ReadInput()); // Rgb24 (opaque still) or Rgba32 (alpha, animation)
        var snapshot = ImageSnapshots.Capture(image);
        Assert.Equal(fixture.Expected.FrameCount, snapshot.Frames.Count);
        var max = 0;
        var sum = 0.0;
        var location = "(none)";
        for (var i = 0; i < snapshot.Frames.Count; i++)
        {
            var actual = snapshot.Frames[i].Pixels;
            var (frameMax, frameMean, frameLocation) = Measure(fixture.GetFrame(i, actual.Layout), actual);
            sum += frameMean;
            if (frameMax > max)
            {
                max = frameMax;
                location = string.Create(CultureInfo.InvariantCulture, $"frame {i} {frameLocation}");
            }
        }

        var mean = sum / snapshot.Frames.Count;
        TestContext.Current.TestOutputHelper?.WriteLine(string.Create(CultureInfo.InvariantCulture, $"{id}: max {max} at {location}, mean {mean:F4}"));

        var policy = fixture.Policy;
        var checks = fixture.Entry.Reference?.CrossChecks?.Where(check => check.ExcludedFromTolerance != true && check.MaxAbsoluteError is not null && check.Decoder.Contains("vp8 decoder", StringComparison.Ordinal)).ToList() ?? [];
        Assert.NotEmpty(checks);
        var (justifiedMax, justifiedMean) = ComparisonPolicy.GetMaximumJustifiedTolerance(checks.Max(check => check.MaxAbsoluteError!.Value), checks.Max(check => check.MeanAbsoluteError!.Value));
        var expectedMax = Math.Min(justifiedMax, Math.Max(1, max));
        var expectedMean = Math.Min(justifiedMean, Math.Ceiling(Math.Round((Math.Round(mean, 4, MidpointRounding.AwayFromZero) + 0.01) * 100, 6, MidpointRounding.AwayFromZero)) / 100);
        Assert.False(policy.IsExact);
        Assert.True(policy.MaxAbsoluteError == expectedMax && Math.Abs(policy.MaxMeanAbsoluteError - expectedMean) < 1e-9,
            string.Create(CultureInfo.InvariantCulture, $"The policy of '{id}' (max {policy.MaxAbsoluteError}, mean {policy.MaxMeanAbsoluteError}) is not the one derived from the measured disagreement (max {max} at {location}, mean {mean:F4}: max {expectedMax}, mean {expectedMean}). Update LibraryWebPMeasurements in tools/Meziantou.Framework.Imaging.CorpusGenerator/WebPCorpus.cs after reviewing the change."));

        // The VP8 reconstruction is exact; only the rounding of the color conversion differs (one unit)
        Assert.True(max <= 1, $"Maximum error {max} at {location}.");
    }

    private static bool HasHiddenColors(RawPixelBuffer frame)
    {
        var span = frame.Span;
        for (var i = 0; i < span.Length; i += 4)
        {
            if (span[i + 3] == 0 && (span[i] | span[i + 1] | span[i + 2]) != 0)
                return true;
        }

        return false;
    }

    private static (int Max, double Mean, string Location) Measure(RawPixelBuffer expected, RawPixelBuffer actual)
    {
        Assert.Equal(expected.Layout, actual.Layout);
        Assert.Equal((expected.Width, expected.Height), (actual.Width, actual.Height));
        var channels = expected.Layout.ChannelCount;
        var max = 0;
        var sum = 0L;
        var count = 0;
        var location = "(none)";
        for (var y = 0; y < expected.Height; y++)
        {
            for (var x = 0; x < expected.Width; x++)
            {
                for (var c = 0; c < channels; c++)
                {
                    var difference = Math.Abs(expected.GetSample(x, y, c) - actual.GetSample(x, y, c));
                    if (c == 3)
                    {
                        Assert.Equal(0, difference); // alpha is exact
                        continue;
                    }

                    sum += difference;
                    count++;
                    if (difference > max)
                    {
                        max = difference;
                        location = string.Create(CultureInfo.InvariantCulture, $"({x}, {y}) channel {c}");
                    }
                }
            }
        }

        return (max, (double)sum / count, location);
    }
}
