namespace Meziantou.Framework.Analyzers.Assertions;

internal static class RuleIdentifiers
{
    internal const string AssertionArgumentOrderDiagnosticId = "MFAS0001";
    internal const string ReferenceEqualsDiagnosticId = "MFAS0002";
    internal const string IsTypeInvalidTypeDiagnosticId = "MFAS0003";
    internal const string UseEmptyAssertionDiagnosticId = "MFAS0004";
    internal const string UseHasCountAssertionDiagnosticId = "MFAS0005";
    internal const string UseNullAssertionDiagnosticId = "MFAS0006";
    internal const string UseNotNullAssertionDiagnosticId = "MFAS0007";
    internal const string NullWithValueTypeDiagnosticId = "MFAS0008";
    internal const string NotNullWithValueTypeDiagnosticId = "MFAS0009";
    internal const string SameWithValueTypeDiagnosticId = "MFAS0010";
    internal const string NotSameWithValueTypeDiagnosticId = "MFAS0011";
    internal const string UseIsAssignableToDiagnosticId = "MFAS0012";
    internal const string UseIsNotAssignableToDiagnosticId = "MFAS0013";
    internal const string UseMatchesDiagnosticId = "MFAS0014";
    internal const string UseDoesNotMatchDiagnosticId = "MFAS0015";
    internal const string UseStringContainsDiagnosticId = "MFAS0016";
    internal const string UseStringDoesNotContainDiagnosticId = "MFAS0017";
    internal const string UseStringStartsWithDiagnosticId = "MFAS0018";
    internal const string UseStringDoesNotStartWithDiagnosticId = "MFAS0019";
    internal const string UseStringEndsWithDiagnosticId = "MFAS0020";
    internal const string UseStringDoesNotEndWithDiagnosticId = "MFAS0021";
    internal const string UseCollectionContainsDiagnosticId = "MFAS0022";
    internal const string UseCollectionDoesNotContainDiagnosticId = "MFAS0023";
    internal const string UseCollectionAnyContainsDiagnosticId = "MFAS0024";
    internal const string UseCollectionAnyDoesNotContainDiagnosticId = "MFAS0025";
    internal const string UseCollectionAllDiagnosticId = "MFAS0026";
    internal const string UseCollectionDoesNotAllDiagnosticId = "MFAS0027";
    internal const string UseNotEmptyForAnyDiagnosticId = "MFAS0028";
    internal const string UseEmptyForAnyDiagnosticId = "MFAS0029";
    internal const string UseEmptinessAssertionDiagnosticId = "MFAS0030";
    internal const string UseEqualForEqualityOperatorDiagnosticId = "MFAS0031";
    internal const string UseNotEqualForEqualityOperatorDiagnosticId = "MFAS0032";
    internal const string UseEqualForEqualsMethodDiagnosticId = "MFAS0033";
    internal const string UseNotEqualForEqualsMethodDiagnosticId = "MFAS0034";
    internal const string UseEqualForSequenceEqualDiagnosticId = "MFAS0035";
    internal const string UseNotEqualForSequenceEqualDiagnosticId = "MFAS0036";
    internal const string UseSameForReferenceEqualsDiagnosticId = "MFAS0037";
    internal const string UseNotSameForReferenceEqualsDiagnosticId = "MFAS0038";
    internal const string UseInRangeDiagnosticId = "MFAS0039";
    internal const string UseNotInRangeDiagnosticId = "MFAS0040";
    internal const string UseProperSubsetDiagnosticId = "MFAS0041";
    internal const string UseNotProperSubsetDiagnosticId = "MFAS0042";
    internal const string UseProperSupersetDiagnosticId = "MFAS0043";
    internal const string UseNotProperSupersetDiagnosticId = "MFAS0044";
    internal const string UseNegatedConditionAssertionDiagnosticId = "MFAS0045";
    internal const string UseIsTypeForRuntimeTypeDiagnosticId = "MFAS0046";
    internal const string UseIsNotTypeForRuntimeTypeDiagnosticId = "MFAS0047";
}
