<Project Sdk="Meziantou.NET.Sdk.Test">
  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Specs/GfmPipeTableDifferential.json" LogicalName="Meziantou.Framework.Markdown.Tests.Specs.GfmPipeTableDifferential.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.FullPath/Meziantou.Framework.FullPath.csproj" />
    <ProjectReference Include="../../src/Meziantou.Framework.Markdown/Meziantou.Framework.Markdown.csproj" />
  </ItemGroup>
</Project>
