<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <TargetFrameworks>$(LatestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Meziantou.Framework.LanguageTool.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../common/ConsoleHelper.cs" Link="ConsoleHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Meziantou.Framework.Language.Tool/Meziantou.Framework.Language.Tool.csproj" />
    <ProjectReference Include="../../src/Meziantou.Framework.TemporaryDirectory/Meziantou.Framework.TemporaryDirectory.csproj" />
  </ItemGroup>

</Project>
