name: 'Setup .NET'

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
      with:
        global-json-file: global.json
        dotnet-version: |
          9.0.x
          8.0.x
