using System.Text;
using System.Text.RegularExpressions;
using Meziantou.Framework.Imaging.CorpusGenerator.Common;
using Meziantou.Framework.Imaging.CorpusGenerator.Infrastructure;

namespace Meziantou.Framework.Imaging.CorpusGenerator;

/// <summary>
/// Generates the PNG, APNG, GIF and JPEG fixtures of the golden corpus (tests/Meziantou.Framework.Imaging.Fixtures).
/// It does not use the library under test: expected pixels are either hand-defined (patterns and literal frame grids) or
/// decoded by pinned, independent tools (libjpeg-turbo djpeg), and are cross-checked with a second independent decoder
/// (FFmpeg/libavcodec) whenever possible.
/// Requirements: macOS, ffmpeg, cjpeg and djpeg (libjpeg-turbo) and sips (Apple ImageIO: JPEG cross-checks, and PNG
/// features FFmpeg does not implement) at the pinned versions below (override with --accept-tool-versions after reviewing
/// the differences), and swift (Xcode command line tools) to run imageio_frames.swift, the Apple ImageIO APNG and GIF
/// cross-check.
/// </summary>
internal static partial class GoldenCorpus
{
    public const string ScriptPath = "tools/Meziantou.Framework.Imaging.CorpusGenerator/GoldenCorpus.cs";
    private const int SchemaVersion = 2;

    // Formats whose fixtures are produced by their own generators (any OS): WebPCorpus, QoiCorpus, BmpCorpus, TgaCorpus and
    // PnmCorpus
    private static readonly HashSet<string> ExternalFormats = new(StringComparer.Ordinal) { "webp", "qoi", "bmp", "tga", "pnm" };

    public static int Run(GeneratorOptions options)
    {
        var tools = new GoldenTools(options.AcceptToolVersions);
        return CorpusDriver.Run(options, "mfi-corpus-", output => Generate(output, tools),
            (fixtures, files, bytes) => $"{fixtures} fixtures, {files} files, {bytes} bytes",
            "The committed corpus is reproducible.");
    }

    private static int Generate(FullPath outDir, GoldenTools tools)
    {
        List<Obj> fixtures;
        using (var corpus = new Corpus<GoldenTools>(outDir, tools, ScriptPath))
        {
            BuildPngFfmpeg(corpus);
            BuildPngFfmpegDecoding(corpus);
            BuildPngHand(corpus);
            BuildInvalidPng(corpus);
            BuildInvalidApng(corpus);
            BuildApngHand(corpus);
            BuildApngCompositing(corpus);
            BuildApngFfmpeg(corpus);
            BuildApngFfmpegDecoding(corpus);
            BuildGifHand(corpus);
            BuildGifFfmpeg(corpus);
            BuildGifFfmpegDecoding(corpus);
            BuildGifDecoding(corpus);
            BuildJpeg(corpus);
            BuildInvalidJpeg(corpus);
            BuildInvalidProgressiveJpeg(corpus);
            BuildLimits(corpus);
            fixtures = [.. corpus.Fixtures.Concat(PreserveExternalFixtures(outDir)).OrderBy(f => (string)f["id"]!, StringComparer.Ordinal)];
        }

        var manifest = new Obj
        {
            ["$schema"] = "./manifest.schema.json",
            ["schemaVersion"] = SchemaVersion,
            ["generator"] = new Obj
            {
                ["script"] = ScriptPath,
                ["command"] = "dotnet run --project tools/Meziantou.Framework.Imaging.CorpusGenerator -- golden --write",
                ["tools"] = new List<string>
                {
                    tools.FfmpegLabel,
                    $"libjpeg-turbo {tools.CjpegVersion} cjpeg",
                    $"libjpeg-turbo {tools.DjpegVersion} djpeg",
                    $"Apple ImageIO {tools.MacOS} {tools.SipsVersion}",
                    ToolSet.RuntimeLabel,
                },
            },
            ["fixtures"] = fixtures,
        };
        CorpusDriver.WriteManifest(outDir, manifest);
        return fixtures.Count;
    }

    /// <summary>The WebP, QOI, BMP, TGA and PNM fixtures are generated by WebPCorpus (libwebp tools), QoiCorpus (the qoi.h
    /// reference implementation), BmpCorpus, TgaCorpus and PnmCorpus: this generator keeps their committed manifest entries and
    /// files unchanged.</summary>
    private static List<Obj> PreserveExternalFixtures(FullPath outDir)
    {
        var fixtures = CorpusDriver.Fixtures(CorpusDriver.LoadCommittedManifest()).Where(f => ExternalFormats.Contains((string)f["format"]!)).ToList();
        CorpusDriver.CopyCommittedFiles(outDir, fixtures);
        return fixtures;
    }

    // -----------------------------------------------------------------------------------------------------------------
    // Independent cross-checks
    // -----------------------------------------------------------------------------------------------------------------

    /// <summary>Decodes every displayed frame with Apple ImageIO (CGImageSource, straight alpha; imageio_frames.swift) and
    /// compares with the hand-defined frames: the second independent APNG and GIF decoder. binaryAlpha (GIF) also accepts the
    /// lossless ImageIO layouts of frames whose alpha is only 0 or 255 (see imageio_frames.swift).</summary>
    private static (Obj Check, List<byte[]>? Decoded) ImageioCrossCheck(Corpus<GoldenTools> c, FullPath path, IReadOnlyList<Img> expectedFrames, string layout, bool binaryAlpha = false)
    {
        var t = c.Tools;
        var script = CorpusDriver.RepoRoot / "tools" / "Meziantou.Framework.Imaging.CorpusGenerator" / "imageio_frames.swift";
        List<string> command = [t.Swift, script.Value, .. (binaryAlpha ? ["--binary-alpha"] : Array.Empty<string>()), path.Value];
        var result = Proc.Exec(command);
        var check = new Obj
        {
            ["decoder"] = $"Apple ImageIO ({t.MacOS}, CGImageSource)",
            ["command"] = CommonCorpus.Display(command, t, [(path.Value, "{input}"), (script.Value, "tools/Meziantou.Framework.Imaging.CorpusGenerator/imageio_frames.swift")]),
        };
        if (result.ExitCode != 0)
        {
            check["result"] = "differs";
            check["notes"] = "ImageIO failed: " + Encoding.UTF8.GetString(result.Stderr).Trim();
            return (check, null);
        }

        var sample = layout == "rgba8" ? 1 : 2;
        var header = Encoding.UTF8.GetString(result.Stderr).Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        if (header[4] != CommonCorpus.Str(8 * sample))
        {
            check["result"] = "differs";
            check["notes"] = $"ImageIO decoded {header[4]}-bit frames, {8 * sample}-bit expected.";
            return (check, null);
        }

        var expectedRaw = expectedFrames.Select(f => f.Raw(layout)).ToList();
        var length = expectedRaw[0].Length;
        var output = result.Stdout;
        var decoded = CommonCorpus.Chunks(output, length);
        if (output.Length % length != 0 || decoded.Count != expectedRaw.Count)
        {
            check["result"] = "differs";
            check["notes"] = $"ImageIO produced {output.Length} bytes ({header[1]} frames), {expectedRaw.Count} frames expected.";
            return (check, decoded);
        }

        CommonCorpus.CompareFrames(check, expectedRaw, decoded, sample, "ImageIO keeps a different color in fully transparent pixels");
        return (check, decoded);
    }

    /// <summary>Decodes an 8-bit input with Apple ImageIO (sips, 32-bit BMP with straight alpha) and compares it with the
    /// expected RGBA pixels: the second independent decoder when FFmpeg does not implement a feature.</summary>
    private static Obj SipsCrossCheck(Corpus<GoldenTools> c, FullPath path, Img img, string? notes = null)
    {
        var t = c.Tools;
        var bmp = CommonCorpus.WithSuffix(path, ".sips.bmp");
        List<string> command = [t.Sips, "-s", "format", "bmp", path.Value, "--out", bmp.Value];
        Proc.Run(command);
        var decoded = CommonCorpus.ReadBmp(File.ReadAllBytes(bmp));
        File.Delete(bmp);
        var decodedRaw = decoded.Model == "rgba" ? decoded.Raw("rgba8") : new Img(decoded.Width, decoded.Height, "rgba", 8, decoded.Rgba()).Raw("rgba8");
        var (m, mean, _) = CommonCorpus.Compare(img.Raw("rgba8"), decodedRaw, 1);
        var check = new Obj
        {
            ["decoder"] = $"Apple ImageIO ({t.MacOS}, {t.SipsVersion})",
            ["command"] = CommonCorpus.Display(command, t, [(path.Value, "{input}"), (bmp.Value, "{output}.bmp")]),
            ["maxAbsoluteError"] = m,
            ["meanAbsoluteError"] = Py.Round(mean, 4),
            ["result"] = m == 0 ? "exact" : "differs",
        };
        if (!string.IsNullOrEmpty(notes))
            check["notes"] = notes;
        return check;
    }

    // -----------------------------------------------------------------------------------------------------------------
    // Limits
    // -----------------------------------------------------------------------------------------------------------------

    private static Obj ExistingInput(Obj fixture)
    {
        var input = (Obj)fixture["input"]!;
        return new Obj { ["path"] = input["path"], ["sha256"] = input["sha256"] };
    }

    private static void BuildLimits(Corpus<GoldenTools> c)
    {
        var t = c.Tools;
        var byId = c.Fixtures.ToDictionary(f => (string)f["id"]!, StringComparer.Ordinal);
        Obj Limit(string kind) => new() { ["exception"] = "ImageResourceLimitException", ["limitKind"] = kind };
        Obj Limits(string name, long value) => new() { ["limits"] = new Obj { [name] = value } };

        var gif = byId["gif/disposal-transparency"];
        c.AddError("limit/gif/frames-over-limit", "limit", null, null, "gif",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("Frames"), decodeOptions: Limits("MaxFrames", 3), existingInput: ExistingInput(gif),
            notes: "Reuses the 4-frame gif/disposal-transparency input with MaxFrames = 3: the limit is a safety bound, never a successful truncation.");
        c.AddError("limit/gif/total-pixels-over-limit", "limit", null, null, "gif",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("TotalPixels"), decodeOptions: Limits("MaxTotalPixels", 63), existingInput: ExistingInput(gif),
            notes: "Reuses gif/disposal-transparency (4 full-canvas 4x4 displayed frames, 64 pixels, partial rectangles) with " +
                   "MaxTotalPixels = 63: displayed frames are charged with the full canvas when produced, so only decoding reaches the limit.");
        var png = byId["png/rgba8-corner-markers"];
        c.AddError("limit/png/width-over-limit", "limit", null, null, "png",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("Width"), decodeOptions: Limits("MaxWidth", 4), existingInput: ExistingInput(png),
            notes: "Reuses the 5x4 png/rgba8-corner-markers input with MaxWidth = 4.");
        c.AddError("limit/png/frame-pixels-over-limit", "limit", null, null, "png",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("FramePixels"), decodeOptions: Limits("MaxFramePixels", 19), existingInput: ExistingInput(png),
            notes: "Reuses the 5x4 (20 pixels) png/rgba8-corner-markers input with MaxFramePixels = 19.");
        var poster = byId["apng/poster-rgba16-dispose"];
        c.AddError("limit/png/apng-frames-over-limit", "limit", null, null, "png",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("Frames"), features: ["apng"], decodeOptions: Limits("MaxFrames", 5), existingInput: ExistingInput(poster),
            notes: "Reuses apng/poster-rgba16-dispose (separate poster + 5 frames) with MaxFrames = 5: the poster counts toward the limit.");
        var over8 = byId["apng/over-alpha-rgba8"];
        c.AddError("limit/png/apng-total-pixels-over-limit", "limit", null, null, "png",
            c.Provenance("hand-authored", "BuildLimits", null, [ToolSet.RuntimeLabel]),
            Limit("TotalPixels"), features: ["apng"], decodeOptions: Limits("MaxTotalPixels", 59), existingInput: ExistingInput(over8),
            notes: "Reuses apng/over-alpha-rgba8 (5 full-canvas 4x3 displayed frames, 60 pixels) with MaxTotalPixels = 59: " +
                   "displayed pixels are charged when each frame is produced (full canvas, whatever the encoded region size), " +
                   "so only decoding reaches the limit.");
        var adam7 = byId["png/rgba8-adam7"];
        var size = new FileInfo(c.Out / (string)((Obj)adam7["input"]!)["path"]!).Length;
        c.AddError("limit/png/encoded-bytes-over-limit", "limit", null, null, "png",
            c.Provenance("hand-authored", "BuildLimits", new Obj { ["inputBytes"] = size }, [ToolSet.RuntimeLabel]),
            Limit("EncodedBytes"), decodeOptions: Limits("MaxEncodedBytes", size - 1), existingInput: ExistingInput(adam7),
            notes: "Reuses png/rgba8-adam7 with MaxEncodedBytes one byte below its size: the limit is reached at IEND, after the header.");
    }
}

/// <summary>The pinned tools of the golden generator.</summary>
internal sealed partial class GoldenTools : ToolSet
{
    public GoldenTools(bool acceptVersions)
        : base(RequireAll("ffmpeg", "cjpeg", "djpeg"))
    {
        Cjpeg = ExecutableFinder.GetFullExecutablePath("cjpeg")!;
        Djpeg = ExecutableFinder.GetFullExecutablePath("djpeg")!;
        CjpegVersion = VersionRegex().Match(Proc.RunText([Cjpeg, "-version"], stderr: true)).Groups["version"].Value;
        DjpegVersion = VersionRegex().Match(Proc.RunText([Djpeg, "-version"], stderr: true)).Groups["version"].Value;
        var actual = new Dictionary<string, string>(StringComparer.Ordinal) { ["ffmpeg"] = FfmpegVersion, ["cjpeg"] = CjpegVersion, ["djpeg"] = DjpegVersion };
        var mismatches = PinnedVersions.Where(p => actual.ContainsKey(p.Name) && actual[p.Name] != p.Version).Select(p => $"{p.Name} {actual[p.Name]} (pinned {p.Version})").ToList();
        if (mismatches.Count > 0 && !acceptVersions)
        {
            throw new FatalException("Tool versions differ from the pinned versions: " + string.Join(", ", mismatches) +
                ". Review the impact and rerun with --accept-tool-versions (then update PinnedVersions).");
        }

        Sips = ExecutableFinder.GetFullExecutablePath("sips") ?? throw new FatalException("sips (macOS Apple ImageIO) is required for the independent JPEG and PNG cross-checks.");
        SipsVersion = Proc.RunText([Sips, "--version"]).Trim().Split('\n')[0];
        MacOS = "macOS " + Proc.RunText(["sw_vers", "-productVersion"]).Trim();
        var pinnedSips = PinnedVersions.Single(p => p.Name == "sips").Version;
        if (SipsVersion != pinnedSips && !acceptVersions)
            throw new FatalException($"sips version {SipsVersion} differs from the pinned {pinnedSips}; rerun with --accept-tool-versions after review.");
        Swift = ExecutableFinder.GetFullExecutablePath("swift") ?? throw new FatalException("swift (Xcode command line tools) is required for the Apple ImageIO APNG and GIF cross-checks (imageio_frames.swift).");
        LibjpegLabel = $"libjpeg-turbo {CjpegVersion} (cjpeg/djpeg)";
        DisplayNames = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [Ffmpeg] = "ffmpeg",
            [Cjpeg] = "cjpeg",
            [Djpeg] = "djpeg",
            [Sips] = "sips",
            [Swift] = "swift",
        };
    }

    // Tool versions used to produce the committed corpus. Regenerating with other versions is allowed only explicitly
    // (--accept-tool-versions) and must be reviewed: encoded inputs and decoded references may change.
    private static readonly (string Name, string Version)[] PinnedVersions =
    [
        ("ffmpeg", "9.0.2"),
        ("cjpeg", "3.2.0"),
        ("djpeg", "3.2.0"),
        ("sips", "sips-316"), // Apple ImageIO: independent JPEG cross-check, and arbiter when FFmpeg lacks a PNG feature
    ];

    public string Cjpeg { get; }

    public string Djpeg { get; }

    public string CjpegVersion { get; }

    public string DjpegVersion { get; }

    public string Sips { get; }

    public string SipsVersion { get; }

    public string MacOS { get; }

    public string Swift { get; }

    public string LibjpegLabel { get; }

    public override IReadOnlyDictionary<string, string> DisplayNames { get; }

    /// <summary>Checks every tool at once (one message lists all the missing ones) and returns the FFmpeg path.</summary>
    private static string RequireAll(params string[] names)
    {
        var missing = names.Where(n => ExecutableFinder.GetFullExecutablePath(n) is null).ToList();
        if (missing.Count > 0)
            throw new FatalException("Missing required tools: " + string.Join(", ", missing));
        return ExecutableFinder.GetFullExecutablePath(names[0])!;
    }

    [GeneratedRegex(@"version (?<version>\S+)", RegexOptions.ExplicitCapture)]
    private static partial Regex VersionRegex();
}
