name: build_and_test_matrix_entry
on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      configuration:
        required: true
        type: string
      additional_arguments:
        required: true
        type: string
      is_pull_request:
        required: true
        type: boolean
      enable_code_coverage:
        required: false
        type: boolean
        default: false
      test_target_frameworks:
        required: true
        type: string

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 90
    env:
      RUNS_ON: ${{ inputs.runs_on }}
    steps:
      - id: compute-artifact-name
        name: Compute artifact name
        run: |
          $Name = "build-output-${{ inputs.runs_on }}-${{ inputs.configuration }}-${{inputs.additional_arguments}}".Replace(":", "_").Replace("/", "_")
          "artifact-name=$Name" >> $env:GITHUB_OUTPUT
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ case(inputs.is_pull_request, 0, 1) }}
      - run: git config --global protocol.file.allow always

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Generate delta build file
        id: build-project
        uses: ./.github/actions/deltabuild
        with:
          input-project: eng/build.proj
          output-project: eng/delta.proj
          run-generate: ${{ case(inputs.is_pull_request, 'true', 'false') }}
          full-rebuild-triggers: |
            .github/workflows/ci.yml
            .github/workflows/build-and-test-matrix-entry.yml
            eng/**/*.proj
            eng/test-target-frameworks.json

      - name: Build
        if: steps.build-project.outputs.has-project == 'true'
        run: dotnet build ${{ steps.build-project.outputs.project }} --configuration ${{ inputs.configuration }} /bl ${{ inputs.additional_arguments }}

      - id: pack-build-output
        name: Archive build outputs
        if: steps.build-project.outputs.has-project == 'true'
        run: |
          $ArchivePath = Join-Path $env:RUNNER_TEMP "build-output.tar"
          if (Test-Path $ArchivePath) {
            Remove-Item $ArchivePath -Force
          }

          tar -cf $ArchivePath artifacts/bin artifacts/obj
          "archive-path=$ArchivePath" >> $env:GITHUB_OUTPUT

      - uses: actions/upload-artifact@v7
        if: always() && steps.build-project.outputs.has-project == 'true'
        with:
          name: ${{ steps.compute-artifact-name.outputs.artifact-name }}
          if-no-files-found: ${{ case(steps.build-project.outputs.project == 'eng/delta.proj', 'warn', 'error') }}
          retention-days: 3
          path: ${{ steps.pack-build-output.outputs.archive-path }}

  test:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 90
    needs: [build]
    strategy:
      matrix:
        target_framework: ${{ fromJSON(inputs.test_target_frameworks) }}
      fail-fast: false
    env:
      RUNS_ON: ${{ inputs.runs_on }}
      TestResultsDirectory: ${{ github.workspace}}/TestResults
      EnableCodeCoverage: ${{ case(inputs.enable_code_coverage, 'true', 'false') }}
    steps:
      - id: compute-artifact-name
        name: Compute artifact name
        run: |
          $SanitizedName = "${{ inputs.runs_on }}-${{ inputs.configuration }}-${{inputs.additional_arguments}}-${{ matrix.target_framework }}".Replace(":", "_").Replace("/", "_")
          "artifact-name=test-results-$SanitizedName" >> $env:GITHUB_OUTPUT
          $BuildArtifactName = "build-output-${{ inputs.runs_on }}-${{ inputs.configuration }}-${{inputs.additional_arguments}}".Replace(":", "_").Replace("/", "_")
          "build-artifact-name=$BuildArtifactName" >> $env:GITHUB_OUTPUT
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ case(inputs.is_pull_request, 0, 1) }}
      - run: git config --global protocol.file.allow always

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Generate delta build file
        id: build-project
        uses: ./.github/actions/deltabuild
        with:
          input-project: eng/build.proj
          output-project: eng/delta.proj
          run-generate: ${{ case(inputs.is_pull_request, 'true', 'false') }}
          full-rebuild-triggers: |
            .github/workflows/ci.yml
            .github/workflows/build-and-test-matrix-entry.yml
            eng/**/*.proj
            eng/test-target-frameworks.json

      - name: Enable ProjFS
        if: startsWith(inputs.runs_on, 'windows') && steps.build-project.outputs.has-project == 'true'
        run: |
          $feature = Get-WindowsOptionalFeature -Online -FeatureName Client-ProjFS
          if ($feature.State -ne 'Enabled') {
            Enable-WindowsOptionalFeature -Online -FeatureName Client-ProjFS -NoRestart
          }

      - uses: actions/download-artifact@v8
        if: steps.build-project.outputs.has-project == 'true'
        with:
          name: ${{ steps.compute-artifact-name.outputs.build-artifact-name }}
          path: ${{ runner.temp }}/build-output

      - name: Extract build outputs
        if: steps.build-project.outputs.has-project == 'true'
        run: tar -xf "${{ runner.temp }}/build-output/build-output.tar" -C ${{ github.workspace }}

      - name: List environment variables
        if: steps.build-project.outputs.has-project == 'true'
        run: "Get-ChildItem env: | Sort-Object Name"

      - name: Restore test dependencies
        if: steps.build-project.outputs.has-project == 'true'
        run: dotnet restore ${{ steps.build-project.outputs.project }} ${{ inputs.additional_arguments }}

      - name: Run tests
        if: steps.build-project.outputs.has-project == 'true'
        run: dotnet test ${{ steps.build-project.outputs.project }} --configuration ${{ inputs.configuration }} --framework ${{ matrix.target_framework }} --no-build --results-directory "${{ env.TestResultsDirectory }}" /p:EnableCodeCoverage=${{ env.EnableCodeCoverage }} ${{ inputs.additional_arguments }}

      - uses: actions/upload-artifact@v7
        if: always() && steps.build-project.outputs.has-project == 'true'
        with:
          name: ${{ steps.compute-artifact-name.outputs.artifact-name }}
          if-no-files-found: ${{ case(steps.build-project.outputs.project == 'eng/delta.proj', 'warn', 'error') }}
          retention-days: 3
          path: |
            !**/*.coverage
            **/*.binlog
            ${{ env.TestResultsDirectory }}/**/*

      - uses: actions/upload-artifact@v7
        if: always() && steps.build-project.outputs.has-project == 'true' && env.EnableCodeCoverage == 'true'
        with:
          name: ${{ steps.compute-artifact-name.outputs.artifact-name }}-coverage
          if-no-files-found: ${{ case(steps.build-project.outputs.project == 'eng/delta.proj', 'warn', 'error') }}
          retention-days: 3
          path: |
            **/*.coverage
