on:
  workflow_dispatch:
    inputs:
      force_bump_all:
        description: Force bumping all package versions
        type: boolean
        default: false
  schedule:
  - cron: '0 0 * * 0' # once a week

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  update_file:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet
      - run: dotnet run ./eng/update-versions.cs -- --create-pull-request ${{ inputs.force_bump_all && '--force-bump-all' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
